### ISSUE TITLE
COMException (0x800704EC) When launching Monitorian on Windows 10

### ISSUE THREAD

**Issue by TheFragen** [emoacht/Monitorian#1]
Hi there,

Upon launching Monitorian on my computer I get an instant error, that outputs the following log file:
[log.txt](https://github.com/emoacht/Monitorian/files/1006997/log.txt).

The error is present on the Store version, and when installing with the provider installer in the README.

My system:
Windows 10 x64 Home Edition
Version: 1703
Build: 15063.296

Regards,
Christian

**Comment by emoacht** [comment]
Hi Christian,
The log indicates that an error happened in the process for checking whether an ambient light sensor exists. Does your system have an ambient light sensor?
I am going to suppress the error and handle such case as if there is no ambient light sensor.
Regards,
emoacht

**Comment by TheFragen** [comment]
Hi there,

I do not have an ambient light sensor no.

Regards

**Comment by emoacht** [comment]
Hi Christian,
Okay. So I suppressed the exception at issue and released Ver 1.2.3.
Regards,
emoacht

**Comment by TheFragen** [comment]
Hi,

I can confirm the issue is in order now. Closing issue.

Regards
