### ISSUE TITLE
ver 2.7.3.0 can no longer adjust slider by dragging on a touch display

### ISSUE THREAD

**Issue by DrRZ** [emoacht/Monitorian#101]
Up until now I could drag the brightness sliders using touch on the display of my Surface Pro tablet. As of 2.7.3.0 this no longer is working. Touching anywhere on the slider will move the slider to that point but I can't drag anymore. Dragging with a mouse still works.

**Comment by emoacht** [comment]
Thank you for reporting.
It's a minor but critical bug.
