### ISSUE TITLE
"This monitor is not controllable" after monitor turned off

### ISSUE THREAD

**Issue by sbcarp** [emoacht/Monitorian#103]
This issue is directly related to #50 

I got this problem as well, 
Code: -1071241843, Message: The operating system asynchronously destroyed the monitor which corresponds to this handle because the operating system's state changed. This error typically occurs because the monitor PDO associated with this handle was removed, the monitor PDO associated with this handle was stopped, or a display mode change occurred. A display mode change occurs when windows sends a WM_DISPLAYCHANGE windows message to applications.

I've found a solution for that, in AppControllerCore.cs, line 303, change the code to
`var updateResults = await Task.WhenAll(Monitors
						.Where(x => x.IsTarget)
						.Select(x => Task.Run(() => x.UpdateBrightness())));
					if (updateResults.Any((result) => result == false)) await ScanAsync(TimeSpan.Zero);`

I don't know if this is a good fix but it works, hope it will help

**Comment by emoacht** [comment]
Thank you for reporting.
Could you provide the complete error message and operation.log when it happens?
A resume event is supposed to trigger scan operations several times if it works as expected.

**Comment by sbcarp** [comment]
What I did, 

1, Run Monitorian, turn on operation log
2, Turn monitor power off
3, Turn monitor power on
4, Adjust brightness until error shows up

The log doesn't tell much info, 

[Date: 11/7/2020 1:29:25 AM Ver: 2.7.5.0]
Enabled

[Date: 11/7/2020 1:29:44 AM Ver: 2.7.5.0]
Initiated

[Date: 11/7/2020 1:29:46 AM Ver: 2.7.5.0]
ScanAsync [11/7/2020 1:29:44 AM]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\ACI27A7\5&34fdf778&4&UID4356",
      "Description": "ASUS MG279",
      "DisplayIndex": 6,
      "MonitorIndex": 0,
      "IsReachable": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\ACI27A7\5&34fdf778&4&UID4356",
        "Description": "ASUS MG279",
        "DisplayIndex": 6,
        "MonitorIndex": 0,
        "IsReachable": true,
        "Brightness": 85,
        "BrightnessSystemAdjusted": -1
      },
      "Name": "ASUS MG279",
      "IsUnison": false,
      "IsControllable": true,
      "IsLikelyControllable": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 11/7/2020 1:30:23 AM Ver: 2.7.5.0]
Enabled

**Comment by sbcarp** [comment]
The complete error message, MonitorConfiguration.cs Line 382:
Failed to set brightness (Low level). Code: -1071241843, Message: The operating system asynchronously destroyed the monitor which corresponds to this handle because the operating system's state changed. This error typically occurs because the monitor PDO associated with this handle was removed, the monitor PDO associated with this handle was stopped, or a display mode change occurred. A display mode change occurs when windows sends a WM_DISPLAYCHANGE windows message to applications.

**Comment by sbcarp** [comment]
It does work when I turn PC into sleep which will trigger powerChange, but turning monitor off and on wasn't detected

**Comment by emoacht** [comment]
I see. So you ran this app in debug mode.
So what is your real issue from it? You want the monitor disappear from this app's window?

**Comment by sbcarp** [comment]
Turn monitor off and on will cause "This monitor is not controllable" issue, so I downloaded the source code to debug what went wrong. I want to fix that.

**Comment by sbcarp** [comment]
`private readonly DisplayWatcher _displayWatcher;
private readonly PowerWatcher _powerWatcher;
private readonly BrightnessWatcher _brightnessWatcher;`

There are three watchers, first one watches display setting changes, second one watches Computer power changes, third one is for brightness changes.

However, none of those watches for power changes of Display itself, I guess that's the issue?

**Comment by emoacht** [comment]
You are right.
`SystemEvents.DisplaySettingsChanged` event which internally captures `WM_DISPLAYCHANGE` message seems to catch only monitor's turn on but not turn off.

**Comment by 205g0** [comment]
FWIW, I might have the same issue: My Notebook goes to sleep, the monitor then goes off (triggered by not getting any signal anymore) and when everything is awake again Monitorian doesn't work, even after rescanning monitors.

**Comment by sbcarp** [comment]
> FWIW, I might have the same issue: My Notebook goes to sleep, the monitor then goes off (triggered by not getting any signal anymore) and when everything is awake again Monitorian doesn't work, even after rescanning monitors.

Have you tried Twinkle Tray? I found it does better job handling those kind of situations.

**Comment by emoacht** [comment]
@205g0 Your case looks not the same one discussed here. It is caused by the fundamental restriction where a monitor turn-off is not automatically detectable. In your case, the system resume is detectable and automatically triggers a series of rescans. It seems to be a common rescan after resume issue. Could you provide [operation.log](https://github.com/emoacht/Monitorian#operations) when it happens? It is essential to look into the issue.

@sbcarp Do you mean that that app can detected monitor turn-off? I am very interested if so.

**Comment by emoacht** [comment]
@sbcarp This issue has been solved, maybe.
