### ISSUE TITLE
Change step on brigthness using mouse wheel

### ISSUE THREAD

**Issue by minik460** [emoacht/Monitorian#104]
Would it be able to change step when changing brigthness using mouse wheel ? Now it is 6. It would be really good if it was customizable or just the step would be 5 or 10 (not 6).
Thank you.

**Comment by emoacht** [comment]
Thank you for the suggestion.
Now I understand your intention.
The current calculation is done by the following formula:

    +- 120 (given rotation delta) * 0.05 (reduction factor) = +- 6

In theory, the given rotation delta can be any other number depending on the mouse device. It is the source of difficulty to handle this delta. However, 120 seems to have been the default rotation delta for years and probably we can reasonably ignore the number other than a multiple of 120.
I have no strong view on the factor and 5 would be reasonable one. So the modified formula would be the following:

    A multiple of +- 120 (given rotation delta) / 120.0 * 5 (factor) = A multiple of +- 5

In addition, some people want to adjust the factor for their mouse devices. It would be included in add-on features.

**Comment by emoacht** [comment]
Implemented in https://github.com/emoacht/Monitorian/commit/b519040b460b3f4ba15bb0889565fd6be4a4ea7a

**Comment by minik460** [comment]
Thank you very much! love it
