### ISSUE TITLE
Unexpected problem

### ISSUE THREAD

**Issue by gurangurkan** [emoacht/Monitorian#105]
Hello. Recently reset my PC and my favorit app isn't working anymore. 
I get "An unexpected problem happened".

HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)). HResult: -2147221164 ErrorCode: -2147221164

**Comment by emoacht** [comment]
Thank you for reporting.
But I have no idea.

**Comment by gurangurkan** [comment]
> 
> 
> Thank you for reporting.
> But I have no idea. It might be caused by something related to installation.

Actually now it works.. I have installed windows media features as I have Windows 10 Pro N version.. Might be related to that. Thanks anyways for an awesome app!
