### ISSUE TITLE
Lagging mouse pointer and not working brightness setting on Acer Predator XB1

### ISSUE THREAD

**Issue by UDPSendToFailed** [emoacht/Monitorian#108]
Thanks for the app, it's a great idea. However, it's not working for me, when I launch Monitorian, the mouse cursor starts lagging for like 10 seconds, also the app is not able to change the brightness on my Acer Predator XB1. 
I have tried other softwares like softMCCS, they all had the same problems. I'm using Intel UHD620 and a HDMI cable.

[probe.log](https://github.com/emoacht/Monitorian/files/5682938/probe.log)

**Comment by emoacht** [comment]
Hello,
According to the proble.log, your monitor does not accept a command to set the brightness.

```
"SetBrightness": "Success: True, Match: False (Expected: 7, Actual: 0)"
```

**Comment by UDPSendToFailed** [comment]
Well, I should use the hardware keys then. :/ Anyway, it's not a problem, I just wanted to find an option to dim the monitor below the minimal brightness, now I see it's not possible, basically I'm stuck with software screen-overlays like f.lux.

Thanks for the help!
