### ISSUE TITLE
[Feature Request] Hotkey to power off the display

### ISSUE THREAD

**Issue by Darthagnon** [emoacht/Monitorian#111]
I was wondering if it would be possible to implement a customisable global hotkey to switch all screens off into Monitorian? I've used a few freeware screen-off applications in the past, with varying success (most are a bit junky and don't work properly), as my keyboards never have a dedicated screen-off button.

(NB not full "power-down" off, but black and resumable with mouse movement or keyboard, how it goes just before going to sleep)

**Comment by emoacht** [comment]
Thank you for the suggestion.
But I don't understand what your actually want. Do you wish the PC suspended?

**Comment by Darthagnon** [comment]
I don't think it's "suspended" or "sleep" or "hibernate". Something like [Screen Off](https://www.thewindowsclub.com/screenoff-turn-off-windows-laptop-screen) (works okayish) or [Sordum Monitor Off](https://www.sordum.org/10104/sordum-monitor-off-v1-1/) (DO NOT USE! glitched out horribly on my PC) or [Monitor Off](https://sourceforge.net/projects/monitoroff/) (FOSS, but I haven't used it).

**Comment by emoacht** [comment]
Thank you for the explanation.
I am not sure that there would be value to add the suggested function because it has nothing to do with the current functions of this app.
Said that, there seems not much room for those apps to create troubles since they are so simple. It will be accomplished by single window message and global hot key is quite common technique. What is your actual problem about them?

**Comment by Darthagnon** [comment]
Not much, I guess. I currently use Turn Off LCD. 

It was just a thought I had, thinking "Monitorian controls screen brightness. What if it could make brightness go completely to 0? Then I could ditch this extra EXE I have sitting around".

I understand if it's not useful. Best wishes, and merry Christmas!

**Comment by emoacht** [comment]
In terms of internal functionality, powering off the display is essentially a part of power management and completely different from changing the brightness of a monitor. 0 (percent) brightness does not mean a power off but just the lowest point of usable brightness range.

I am neither negative nor positive to adding the function. In any case, it will not be a part of integral part of this app.

**Comment by emoacht** [comment]
The hot key is experimentally added in Ver 2.14.
