### ISSUE TITLE
Support for Samsung LU28R55

### ISSUE THREAD

**Issue by j005u** [emoacht/Monitorian#112]
Hi. What if any info can I provide in addition to my probe log to try to help add support for the Samsung LU28R55 model?

It works fine under ClickMonitorDDC 7.2 on Windows 10 and MonitorControl on OS X.

The latter is also open source: https://github.com/MonitorControl/MonitorControl

[probe.log](https://github.com/emoacht/Monitorian/files/5741136/probe.log)

**Comment by emoacht** [comment]
Thank you for reporting.
Your monitor does not respond to any of DDC/CI commands. I have no idea.
