### ISSUE TITLE
Scrolling is not as fast anymore

### ISSUE THREAD

**Issue by LGXerxes** [emoacht/Monitorian#119]
Since one of the newest update the scrolling over the slider is much slower.
Each scroll "tick" is now 1%, I think in previous versions it was 4%.

Is this intended?

**Comment by emoacht** [comment]
Have you changed `Change per wheel roll` in `Key Settings`?

**Comment by LGXerxes** [comment]
> 
> 
> Have you changed `Change per wheel roll` in `Key Settings`?

I don't seem to be able to find that setting, I've reinstalled the app through github and it works now with 5% increments.

**Comment by emoacht** [comment]
It's one of add-on features and I thought you are using it.
Without it, the value should be 5. See #104. It should never be other than that.

**Comment by emoacht** [comment]
If you try add-on features and cancel it (it is perfectly okay), the last value will remain. I thought it is not a big problem but probably it should be reverted to 5.

**Comment by emoacht** [comment]
Fixed.
