### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by Jorijn-VD-Graaf** [emoacht/Monitorian#120]
The icon appears in the taskbar but disappears shortly after, this also affects the Microsoft store version.
Connected to 2 3840x2160 screens via dp, DDC/CI is turned on.

Asus VP28U
windows 10 pro 64bit
version 20H2

**Comment by emoacht** [comment]
Have you checked the overflow area of taskbar?

**Comment by Jorijn-VD-Graaf** [comment]
yes

**Comment by emoacht** [comment]
I see. So how about Task Manager? This app is still running after it disappears from the taskbar?

**Comment by Jorijn-VD-Graaf** [comment]
it is not in task manager also small edit the icon disappears as soon as I hover over it and not after a certain amount of time

**Comment by emoacht** [comment]
I see. Honestly, I have no idea at all.

**Comment by Jorijn-VD-Graaf** [comment]
Apparently, rivatuner statistics server causes the issues disabling it fixes the problem

**Comment by emoacht** [comment]
Thank you for the information.
I cannot image how that software kills this app though.
