### ISSUE TITLE
Monitorian should always be on top

### ISSUE THREAD

**Issue by sandorex** [emoacht/Monitorian#123]
For example when im in a game monitorian appears below the game so i cannot use it without minimizing the game

**Comment by emoacht** [comment]
In such case, I would suggest to use hot keys.

**Comment by sandorex** [comment]
Welp using hot keys is not an option for me as it's a paid feature, gotta look for some other solution

**Comment by N1ftyB1z** [comment]
I would like this feature too, as Monitorian appears below certain windows (Firefox video pop-out, Media Player mini-player) when the taskbar icon is clicked, meaning you have to minimise them or drag them out of the way, then re-click the monitorian icon to use it.

Hot keys could work, but I have enough of them to remember already, lol! A built-in option for always on top would be great, as using PowerToys to make the windows always on top doesn't carry over the next time that the window is opened.
