### ISSUE TITLE
Add feature to decrease brightness with percentage button

### ISSUE THREAD

**Issue by Cyberdroid1** [emoacht/Monitorian#132]
Please add the feature so that when we shift-click this button, brightness is reduced. It can be customisable.
![image](https://user-images.githubusercontent.com/51435948/107210356-07628580-6a2a-11eb-970f-2e2e057a062f.png)

**Comment by emoacht** [comment]
Thank you for the suggestion.
But if you don't mind a key with a mouse, I think just hitting shortcut key (combination of keys) would be faster and common.

**Comment by Cyberdroid1** [comment]
Keyboard shortcuts are great, but this can be used as some type of alternative to that too.

**Comment by emoacht** [comment]
Could you describe the concrete scenario where this feature will be useful? What input method is in your mind? If you are using a mouse, mouse wheel will be much faster.

**Comment by Cyberdroid1** [comment]
Sorry for the late reply, I didn't get a notification for your message.

I use a touchpad, and sometimes, clicking a single button to decrease brightness seems more easier, rather than fine tuning with the slider.

**Comment by emoacht** [comment]
It's okay. Regarding the touch input, I enabled to increase/decrease by a flick on the button in Ver 2.13.
Flick right direction -> increase
Flick left  direction -> decrease
I tested several ways of the touch for this purpose and they are the easiest and most intuitive.

**Comment by Cyberdroid1** [comment]
What i meant by touchpad, is a trackpad which is present on a laptop device, not a touchscreen display 😄.

**Comment by emoacht** [comment]
Oh I see. I don't know how to treat the input from track pad differently.

**Comment by Cyberdroid1** [comment]
It would treated as a mouse click.

I request you to add this functionality that when we shift-left click the percentage button, it decreases brightness instead of increases.

It can be used as alternative to the shortcut keys (say, someone does not want to pay  ¯\_(ツ)_/¯ )

**Comment by emoacht** [comment]
As already explained, I will never implement that feature.
I think I should not spend my time any further and so I am going to lock this issue.
