### ISSUE TITLE
Error at every update

### ISSUE THREAD

**Issue by Joonel** [emoacht/Monitorian#135]
Updating Monitorian through Microsoft Store ends error every time and I have to open Monitorian again. 
[exception.log](https://github.com/emoacht/Monitorian/files/5977494/exception.log)

**Comment by emoacht** [comment]
Thank you for the report.
An error when downloading from Microsoft Store is an issue of the Store and there is not much I can do.
The exception you posted is supposed to have been fixed by https://github.com/emoacht/Monitorian/commit/a25be407172d819cbc8a308d496b8207182106e6
