### ISSUE TITLE
Monitorian "misses" secondary monitor

### ISSUE THREAD

**Issue by vivalabadila** [emoacht/Monitorian#136]
Hi guys!
After first install it worked ok for a while, then it missed the secondary monitor (on display port, display no.1, positioned on the left, vertically).
Closing and reopening, uninstalling and reinstalling, sometimes made reappear the secondary monitor for a while.
Just now I found that setting to main the secondary monitor made the second setting reappear.
I switched again the main monitor turning back to the original setting (main monitor is on HDMI, display no.2, positioned on the right, horizontally). Second slider still shown, I suppose it will not last, let's see.

Thank you, best regards and have a nice work and day!

Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.03752

Windows 10 Pro
Version 1909
Build 18363.1379

**Comment by vivalabadila** [comment]
Good morning guys!
As expected, after restarting Windows, Monitorian shows me just the slider of the main monitor.

Thank you for paying attention, best regards and have a nice work and day.
Cheers!
Paolo, Italia

**Comment by emoacht** [comment]
Hello.
The visibility of a monitor depends on the OS and its hardware conditions. I am sorry to say but there are not much I can do.
