### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by CadetKosmov** [emoacht/Monitorian#14]
Being able to launch the app via command line using arguments could be useful for hooking it with hotkey utilities. For example, using argument 1 10 could turn the brightness  of the first monitor up by 10 and 2 -10 would turn the brightness of the second monitor down by 10, etc.

**Comment by emoacht** [comment]
Implementing command line interface is not so simple task and would require some design decisions and coding. I personally don't think it would be worth doing.
Maybe you can fork and make console version using the codes in Monitorian/Models/Monitor.
