### ISSUE TITLE
Daisy Chained monitors are not recognized

### ISSUE THREAD

**Issue by stlorenz** [emoacht/Monitorian#140]
Only one monitor is recognized despite three installed
I have a Surface Pro 6 docked with windows 10 20H2.

On this Dock a Dell U2413 and two Dell U2412M, one of them via Daisy Chain on the 2413. 
DD/CI Enabled on all three.

![image](https://user-images.githubusercontent.com/5159308/108588130-de11f580-7357-11eb-98f1-dfe3d882dcb4.png)

Only the non-daisy-chained U2412 is recognized 
![image](https://user-images.githubusercontent.com/5159308/108588024-50cea100-7357-11eb-8ab1-b39a77bb8d89.png)

**Comment by emoacht** [comment]
Thank you for the report.
I have not tested a daisy chain but in this case, the monitors connected by the daisy chain seem not be able to communicate with this app through DDC/CI. I can confirm it if you proved [probe.log](https://github.com/emoacht/Monitorian#probe).
