### ISSUE TITLE
Monitorian will not open on vertical taskbar

### ISSUE THREAD

**Issue by ljcorsa3** [emoacht/Monitorian#142]
I have Monitorian running at startup.  The icon appears in the notification tray, but clicking (L/R) does nothing when I have my normal vertical/left side taskbar.  If I move the taskbar to the bottom or top of my display, everything is fine.

**Comment by emoacht** [comment]
Is that the same issue as #77?
I cannot reproduce this issue. Could you explain your monitors configurations (the placement of each screen on the desktop or so) as detailed as possible?
Just out of curiosity, the attacked library, which is the replacement of  packaged one, makes difference? 
[ScreenFrame2132.zip](https://github.com/emoacht/Monitorian/files/6019849/ScreenFrame2132.zip)

**Comment by ljcorsa3** [comment]
In issue #77, the app opened but was not placed correctly.  Currently, nothing happens at all when I click while taskbar is vertical.  I will gather the information you requested and try the replacement library this evening.

Thanks!

**Comment by ljcorsa3** [comment]
I cannot rename/move the replacement DLL into place...  Sorry, I am stumped by the permissions on C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.13.1.0_neutral__0q7myvhtpbc7w\MonitorianPlus

Here is the monitor/graphics configuration (from Speccy):
Monitor 1
	Name	BenQ SW2700 on NVIDIA GeForce GTX 1060 6GB
	Current Resolution	2560x1440 pixels
	Work Resolution	2437x1440 pixels
	State	Enabled
	Multiple displays	Extended, Primary, Enabled
	Monitor Width	2560
	Monitor Height	1440
	Monitor BPP	32 bits per pixel
	Monitor Frequency	59 Hz
	Device	\\.\DISPLAY1\Monitor0
Monitor 2
	Name	BenQ GW2270 on NVIDIA GeForce GTX 1060 6GB
	Current Resolution	1080x1920 pixels
	Work Resolution	1080x1859 pixels
	State	Enabled
	Multiple displays	Extended, Secondary, Enabled
	Monitor Width	1080
	Monitor Height	1920
	Monitor BPP	32 bits per pixel
	Monitor Frequency	60 Hz
	Device	\\.\DISPLAY2\Monitor0
NVIDIA GeForce GTX 1060 6GB
	Manufacturer	NVIDIA
	Model	GeForce GTX 1060 6GB
	Device ID	10DE-1C03
	Revision	A2
	Subvendor	ASUStek Computer Inc (1043)
	Current Performance Level	Level 0
	Current GPU Clock	139 MHz
	Current Memory Clock	405 MHz
	Current Shader Clock	405 MHz
	Voltage	0.625 V
	Technology	16 nm
	Bus Interface	PCI Express x16
	Temperature	44 °C
	Driver version	27.21.14.5671
	BIOS Version	86.06.0e.00.41
	Physical Memory	2047 MB
	Virtual Memory	2048 MB

**Comment by emoacht** [comment]
Thank you for the information but I am particularly interested in how these monitors are placed in the desktop.
I think you can easily replace library file of [executables](https://github.com/emoacht/Monitorian/releases/tag/2.13.1-Executables) not that of Microsoft Store version.

**Comment by ljcorsa3** [comment]
I removed the Windows Store version and installed from the executables link you provided.  No change in behavior.  Replaced the library file, also no change in behavior.  Photo of computer monitors showing main taskbar vertical on left, secondary horizontal at top.  Let me know if there is any other information I can provide.

I also installed Visual Studio but have not yet succeeded in building the code from the cloned source.  I'll keep trying that route so that I may be able to help you debug at some point.  All suggestions welcome!

![PXL_20210227_172018168](https://user-images.githubusercontent.com/11082181/109398349-69682980-790a-11eb-9313-635a46f5a7dd.jpg)

**Comment by emoacht** [comment]
Thank you for the report.
I am sorry but I don't mean physical settings of monitor but virtual one like 
![Placement](https://user-images.githubusercontent.com/7205690/109402850-89482d80-799c-11eb-98da-c67862a93ff8.png)
Anyways, I tried similar physical settings but could not reproduce the issue.

To run this app on Visual Studio, make sure the components referred in [Setup](https://github.com/emoacht/Monitorian#setup) section are installed.
Then, probably you can start by checking if ScreenFrame.NotifyIconContainer.OnMouseClick method is called when you click the notification icon. If it's okay, go to ScreenFrame.BasicWindowMover.HandleWindowPosChanging method and comment out all the content. If this app's window is shown somewhere on the desktop, revert the comment out and check each step one by one.

**Comment by ljcorsa3** [comment]
Sorry for the long delay. First, here is the "rearrange" window:
![image](https://user-images.githubusercontent.com/11082181/111922489-6fb47600-8a70-11eb-98b8-c9503c8eb70c.png)

I finally have VS2019 set up properly and was able to set breakpoints at the locations you named.  Commenting out the content as suggested does bring up the app windows when mouse is clicked on tray icon. I am not quite sure what values to report back to you, but here are some candidates:
WindowHelper.SWP.SWP_NOSIZE    SWP_NOSIZE    ScreenFrame.WindowHelper.SWP
adjacentLocation    {123,-23.96,360,23.96}    System.Windows.Rect
adjacentLocation.Height    23.96    double
adjacentLocation.Width    360    double
height    23.96    double
lParam    0x00afe904    System.IntPtr
ScreenFrame.WindowHelper.WINDOWPOS
    cx    0    int
    cy    0    int
    flags    65    ScreenFrame.WindowHelper.SWP
    hwnd    0x00160a28    System.IntPtr
    hwndInsertAfter    0x00050bc4    System.IntPtr
    x    123    int
    y    -23    int
position.flags    65    ScreenFrame.WindowHelper.SWP
width    360    double

I am curious about two things: height and width values are different by a factor of 15, and position.y is negative.  No idea if that is normal...

**Comment by emoacht** [comment]
Thank you for the report.
The negative value of Y is possible but odd in this case. This issue looks similar to #118 and in both cases this app's 
icon is at the edge of taskbar and sticks out a little from taskbar. It suggests that the function to get overflow area could return wrong value and it cause wrong location of window.
Could you try to change the width of taskbar so that this app's icon (including vacant background area) could have enough space to be shown and check it any difference?
BTW, I could not understand "height and width values are different by a factor of 15".

**Comment by ljcorsa3** [comment]
I agree, it does sound very similar to #118.  My scale factors are both 1, with 96dpi.  I was trying to understand the units of width and height since they seemed inconsistent to me.  (ie, if height is 23.96 inches (which it might be on the portrait monitor), then the 360 cannot be inches (wider than my room!))

I'm currently running with a return statement as the first line of ScreenFrame.Movers.BasicWindowMover.HandleWindowPosChanging.  It's a little odd, but works as a stopgap!

I will tinker with taskbar geometry some more tonight and report back.  

Thanks!

**Comment by emoacht** [comment]
I think d75d089574e81c7e1cc5d22ef7536a0e2d155be8 solved this issue.
BTW, the unit of width and height is pixel and if the scale factor is 1, it matches actual pixel of the monitor. The origin of coordinates is at left-top corner of primary monitor.

**Comment by ljcorsa3** [comment]
Looks resolved to me!

Thank you!
