### ISSUE TITLE
App aliase wont run shortcut command

### ISSUE THREAD

**Issue by schroef** [emoacht/Monitorian#143]
Im not 100% sure this is related to the app or a windows issue. When you make a shortcut or alias and assign a shortcut, normally this would trigger the app. Currently nothing happens.

I make these shortcuts from the application folder>right click exe file > show on desktop. Then right click icon > properties > assign shortcut.

**Comment by emoacht** [comment]
Thank you for the explanation.
I cannot remember `show on desktop` menu item in right click menu. I think you can simply select `Create shortcut` in right click menu and then move the created shortcut anywhere you wish.

**Comment by emoacht** [comment]
If this is a general question on creating a shortcut to executable, here is not right place and so I will close this issue.
