### ISSUE TITLE
App listing name in startup list not following suit with others

### ISSUE THREAD

**Issue by Cyberdroid1** [emoacht/Monitorian#147]
![image](https://user-images.githubusercontent.com/51435948/109291239-bd153d00-784e-11eb-8395-88a0dcc14037.png)

Instead of being named Monitorian, it is named Monitorian Startup. Though most other apps just have the app name in the entry. Can you please fix this?

**Comment by emoacht** [comment]
The string is intentionally added to startup task of Microsoft Store version to distinguish from that of ordinary version.
I would reconsider the wording when a better idea comes up sometime in future.

**Comment by Cyberdroid1** [comment]
Oh ok, I see.
