### ISSUE TITLE
App icon has its own background box

### ISSUE THREAD

**Issue by Cyberdroid1** [emoacht/Monitorian#148]
![image](https://user-images.githubusercontent.com/51435948/109291401-f2ba2600-784e-11eb-94dc-60d66a452599.png)

![image](https://user-images.githubusercontent.com/51435948/109291486-0c5b6d80-784f-11eb-8fb6-8d6f89271cdb.png)

In above 2, you can see that the app has a back tile as icon background.
Please remove the black background tile.

------------------------------------------

![image](https://user-images.githubusercontent.com/51435948/109291528-19785c80-784f-11eb-807a-f3a6e1127c7b.png)
(sorry for the app icon replaced with a generic icon, it is a Windows bug and I don't know how to fix it)
You can see that the app background for Monitorian is black, while for others it is either blue or the accent color (yellow). Can you please make it that the background follows how other apps follow (accent color)?

**Comment by Cyberdroid1** [comment]
I was going through other issues and saw that the reason you gave for having a black background tile is for visibility in light mode. 
Apparently, Windows has this nifty feature whichich converts full white icons in dark mode to full black in light mode for start menu.

**Comment by emoacht** [comment]
The outline color and tile background color are different thing.
Said that, I would reconsider overall color design when ever-changing Windows 10 UI colors are stabilized sometime in future.

**Comment by Cyberdroid1** [comment]
I was saying that if you remove the background black tile from the icon, it won't affect visibility of the icon in start menu.
