### ISSUE TITLE
Native screen brightness keys on keyboard cannot be hotkeys

### ISSUE THREAD

**Issue by RalpH-himself** [emoacht/Monitorian#153]
My keyboard has native keys to change the screen brightness (Fn+F7, Fn+F8), but I cannot configure them to be the hotkeys to change the screen brightness. If I press them in the hotkey configuration window, Windows shows that the screen brightness has changed, but they won't become hotkeys. I could configure F7 and F8, but those keys are used for too many things in too many programs.

**Comment by emoacht** [comment]
As far as I know, such key combinations with Fn are hardware dependent and cannot be reproduced programmatically.
