### ISSUE TITLE
Monitorian has multiple 'Tray icon preference' entries in Registry key IconStreams 

### ISSUE THREAD

**Issue by aSemy** [emoacht/Monitorian#154]
Firstly, thanks for Monitorian! It's incredibly useful and easy to use, and it makes my life much better.

So, on to this report. It's a bit of a weird one. It's not something that's caused problems, I only noticed it in passing while investigating an issue with my Dropbox notification, but it's not correct so I thought I'd explain and you can decide what to do with it :)

Some info: I'm on Windows 10, and I installed Monitorian through the Microsoft store.

---

In short, Monitorian isn't registering its notification icon (the one in the taskbar, on the right next to the clock) correctly.

![image](https://user-images.githubusercontent.com/897017/111083134-2dd57e00-850c-11eb-95a5-90e39851b44a.png)

Functionally it all works fine, no problems. I always see the icon, there's only ever one icon, and I can click on it just fine. The issue is about how Monitorian is registering its notification icon - after upgrading versions, it isn't reusing an existing registration, but creating a new one.

I can see this in my registry key, `Computer\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify\IconStreams`. This persists all registered notification icons. (It's a byte array of each notification, with a path to the exe, and the letters are ROT13'd.) 

I've wrote a Powershell script to decode the information in the registry key, and I can see lots of entries, and Monitorian has multiple.

```
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.10.0.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.10.1.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.11.2.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.12.1.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.13.0.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.13.1.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.13.2.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.13.3.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.6.0.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.7.3.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.7.5.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.8.0.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe
C:\Program Files\WindowsApps\10186emoacht.Monitorian_2.9.0.0_neutral__0q7myvhtpbc7w\MonitorianPlus\MonitorianPlus.exe     
```

Some programs, like `explorer.exe`, have multiple (part of the data I haven't parsed shows this has something to do with different functions of `explorer.exe`).

I think Monitorian is in error though, because it's pointing to install paths that have since been uninstalled removed.

---

So, while there's no obvious problems caused by this, maybe it's something to investigate in cause other people have issues, or it might cause issues down the line.

I'm not even sure if it's Monitorian's fault - maybe it's something to do with the Microsoft store?

Here's a similar bug ticket that might be relevant https://github.com/electron/electron/issues/2468#issuecomment-142684129

And here's the code I based my Powershell script on https://tmintner.wordpress.com/2011/07/08/windows-7-notification-area-automation-falling-back-down-the-binary-registry-rabbit-hole/

Powershell script: It reads, parses, and prints the `IconStreams` regex key.

<details>
  <summary>Click to show Powershell script</summary>
  

```ps1
[CmdletBinding()]
param()

$IsVerbose = $PSCmdlet.MyInvocation.BoundParameters["Verbose"].IsPresent
$IsDebug = $PSCmdlet.MyInvocation.BoundParameters["Debug"].IsPresent

# inspiration / info
# https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/TrayHelper.cs
# https://github.com/electron/electron/issues/2468
# https://gist.github.com/anaisbetts/c4e3412262324b551dda
# https://tmintner.wordpress.com/2011/07/08/windows-7-notification-area-automation-falling-back-down-the-binary-registry-rabbit-hole/
# https://superuser.com/questions/318088/make-specific-tray-icon-always-show-for-all-profiles-in-windows-7
# https://social.technet.microsoft.com/Forums/windows/fr-FR/677c0753-92ef-46ba-b239-437c3c6a38aa/where-are-the-system-tray-customizations-stored?forum=w7itproinstall
# https://www.geoffchappell.com/studies/windows/shell/explorer/interfaces/notifyitem.htm
# https://www.codeproject.com/Articles/4768/Basic-use-of-Shell-NotifyIcon-in-Win32

# map each a-Z char to rot13'd char
$rot13Map = @{};
(0..25).ForEach( { 
        $rotated = (($_ + 13) % 26);
        $rot13Map[$_ + [char]'a'] = $rotated + [char]'a'
        $rot13Map[$_ + [char]'A'] = $rotated + [char]'A'
    }
);

Function qRot13ASCIIBytes([byte[]]$bytes) {
    # byte[]->int[]->rot13->byte[]
    return [byte[]](([int[]]$bytes).ForEach( {
                return $rot13Map.Contains($_) ? $rot13Map[$_] : $_ ;
            }));
};

# get value of RegKey IconStreams, that describes the notification icons
$IconStreamsBytes = $(Get-ItemProperty $(Get-Item 'HKCU:\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify').PSPath).IconStreams

Write-Debug "Type: $($IconStreamsBytes.GetType())"
Write-Debug "Length: $($IconStreamsBytes.Length)"
# Write-Verbose $iconString -replace '[*\\~;(%?.:@/]', '`$&'


########################################
# IconStreams always starts with a header, length 20
# The first byte also descripes the header length, so get and use that.
$headerLength = [System.BitConverter]::ToUInt32($IconStreamsBytes, 0)
$headerVals = @()
for ($i = 0; $i -lt $headerLength; $i += 4) { 
    $headerVal = [System.BitConverter]::ToUInt32($IconStreamsBytes, $i)
    $headerVals += $headerVal
}
Write-Debug "HeaderVals: $headerVals"

$Header = New-Object -TypeName psobject
$Header | Add-Member -MemberType NoteProperty -Value $headerVals[0] -Name length 
# Header.count is what we're interested in - it defines how many entries are in IconStreams
$Header | Add-Member -MemberType NoteProperty -Value $headerVals[3] -Name count

##############################################

# magic values from tmintner.wordpress.com (it would be nice to see an official definition...)
# maybe in here...
# https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa
# size info
# CHAR  szTip[128] - 128 chars, 2 bytes per char = 512 bytes
# 16 bytes??
# 2 bytes - notification preference 


$magicHeaderLength = 20
$magicEntryLength = 528 + 1112
$expectedIconStreamsLength = $magicHeaderLength + ($Header.count * $magicEntryLength)
Write-Debug "Expected IconStreams length: $expectedIconStreamsLength "
Write-Debug "Actual length:               $($IconStreamsBytes.Length)"
if ($IconStreamsBytes.Length -ne $expectedIconStreamsLength) {
    throw "Unexpected IconStreams length. Expected $expectedIconStreamsLength, but was $($IconStreamsBytes.Length)"
}

###############################################

# skip the header, get the bytes of the entries
$entriesBytes = $IconStreamsBytes | Select-Object -Skip $Header.length
Write-Verbose "entriesBytes length: $($entriesBytes.Length)"

$EntryObjs = @()
for ($i = 0; $i -lt $entriesBytes.Length; $i += $magicEntryLength) {

    $entryRawBytes = $entriesBytes[$i..($i + $magicEntryLength - 1)]
    Write-Verbose "entryRawBytes $($entryRawBytes)"
    $entryRawBytes | Format-Hex | Write-Verbose
    Write-Debug "entryRawBytes.Length $($entryRawBytes.Length)"
        
    if ($entryRawBytes.Length -ne $magicEntryLength) {
        throw "Unexpected IconStreams length. Expected $magicEntryLength, but was $($entryRawBytes.Length)"
    }

    $EntryObj = New-Object -TypeName psobject
    $EntryObj | Add-Member -MemberType NoteProperty -Value $entryRawBytes -Name rawBytes 

    $rawByteIterator = $entryRawBytes.GetEnumerator()

    # exe path (null terminated)
    $exeBytes = @()
    while ($rawByteIterator.MoveNext()) {
        $byte = $rawByteIterator.Current
        if ($byte -eq [byte]0) {
            Write-Verbose "Reached null byte"
            break;
        }
        $exeBytes += $byte
        # utf16 bytes, by ascii chars. So skip empty byte.
        if (!$rawByteIterator.MoveNext()) {
            break;
        }
    }
    $exePath = -join ([char[]][int[]] (qRot13ASCIIBytes($exeBytes)))
    $EntryObj | Add-Member -MemberType NoteProperty -Value $exePath -Name exePath 
    Write-Debug "exePath $($exePath)"

    $notifyPreference = $entryRawBytes[528]
    Write-Debug "notifyPreference: $notifyPreference"
    $EntryObj | Add-Member -MemberType NoteProperty -Value $notifyPreference -Name notifyPreference 

    if ($IsVerbose -or $IsDebug) {
        Read-Host "Press ENTER to continue..."
    }
    $EntryObjs += $EntryObj
}

$EntryObjs | Sort-Object -Property exePath | Format-Table -AutoSize  -Property  notifyPreference, exePath


```

</details>

**Comment by emoacht** [comment]
Thank you for very informative report and script.

> I'm not even sure if it's Monitorian's fault - maybe it's something to do with the Microsoft store?

You are right. Install/Uninstall of a Store app including install path is managed by the Store and the OS. It will be nice if such old icon path would be cleaned but in fact, there is even no chance for each app to know when it is about to be uninstalled or upgraded.

**Comment by aSemy** [comment]
Okay so I've had a dig through the code, and I think this is what's going on...

Monitorian is creating a new NotifyIcon here: https://github.com/emoacht/Monitorian/blob/master/Source/ScreenFrame/NotifyIconContainer.cs#L83 

NotifyIcon is a Windows Forms class, and if we look in the source code for Windows Forms...

https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs

We can see that at some point it creates the icon:

``` C#
Shell_NotifyIconW(NIM.ADD, ref data);
```

That's a call to [Shell_NotifyIconW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shell_notifyiconw), and that `data` arg is basically what gets stored in the registry key `IconStreams` (I think.... it's very confusing because the data format doesn't quite match and the Windows documentation could not be more vague). 

So the structure of the `data` arg is `NOTIFYICONDATA`. In the [docs](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa) for that struct, it has `uID`. 

> `uID`
>
> The application-defined identifier of the taskbar icon. The Shell uses either (hWnd plus uID) or guidItem to identify which icon to operate on when Shell_NotifyIcon is invoked. 

`guidItem` isn't set by Windows Forms†, so that can be ignored. But it does set `uID` from `id`, and that is essentially random in [one of the constructors](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs#L63), and.... not specifically set [in the other](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs#L73)?  I can't really connect the dots for this one. My absolutely massive guess is that the constructor with `IContainer container` somehow re-uses an existing ID? 

It kind of makes sense that using the IContainer constructor is the right way of doing it, because that's what the example for NotifyIcon does. 


https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.notifyicon?view=net-5.0

```c#
        this.components = new System.ComponentModel.Container();
        //...
        // Create the NotifyIcon.
        this.notifyIcon1 = new System.Windows.Forms.NotifyIcon(this.components);
```

But also maybe the Microsoft docs suck and it's something else.

I see that Monitorian doesn't use the IContainer constructor (although [it did in the past](https://github.com/emoacht/Monitorian/commit/9fbe46f8c67bad3717cefe4add557cc50a2579ef#diff-a8260d46b004987cf723f0ab12a8165e51a7b5f3542058650b6fe0e84b37fc8fR59)?). Maybe changing https://github.com/emoacht/Monitorian/blob/master/Source/ScreenFrame/NotifyIconContainer.cs#L83 to use the IContainer constructor will fix it..... 

What do you think? Might using the `new NotifyIcon(container)` help? 

Anyway, I think I'll share this over on the Windows Forms repo and see what the best solution is. 

Cheers!


---

† It seems a lot of apps use the GUID approach, and in the docs it says it's the 'done thing' now, so it's a shame that Windows Forms don't seem to support it. Here are some example entries in my `IconStreams` reg key that start with a GUID.

```
{6D809377-6AF0-444B-8957-A3773F02200E}\Docker\Docker\Docker Desktop.exe
{6D809377-6AF0-444B-8957-A3773F02200E}\VideoLAN\VLC\vlc.exe
{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Steam\steam.exe
```

**Comment by emoacht** [comment]
As far as I understand, the function of `System.ComponentModel.Container` is to dispose all associated components when the Form which owns the container is disposed. When this app closes, it will dispose the NotifyIcon and so I thought the container is not necessary. I have not heard the container has such function you suggsested.

**Comment by emoacht** [comment]
I walked around a bit and decided to leave it because the remedy to clean up old entries in IconStreams involves undocumented APIs and there is a risk to destroy it while there is substantially no benefit to take such a risk.
