### ISSUE TITLE
No RTL of UI :/

### ISSUE THREAD

**Issue by Mozyiko** [emoacht/Monitorian#156]
Hey!

First of all, thank you all for this great function!

I have Windows 10 with Hebrew (RTL) as default language which causing the menu not to fully show up (see [attached photo](https://ibb.co/6BnZbzJ)).

Can you fix it? :)

Thank you!!!

**Comment by emoacht** [comment]
Thank you for the report.
I have never seen the taskbar under RTL settings. It looks interesting.
I will fix it.

**Comment by Mozyiko** [comment]
Cool, Thanks!! 👍 

I have an idea for a feature that can be a supplement for a light sensor.

Usually we change the monitor brightness when the lighting in the room changing. It's happening every day during & after sunset, which means it can be good if the brightness will change for a user preference level, according to the sunset/sunrise times by user location.

What do you think about it?

**Comment by emoacht** [comment]
I have rejected similar ideas before. I don't think it would be useful as some people might imagine.
In the modern world, people don't live in natural cycle of sunrise/sunset. It might sound interesting but not practical.

**Comment by emoacht** [comment]
Solved by 736f50e348b428a26d277da12703b22e1477d9b5
