### ISSUE TITLE
Description in Microsoft Store - USB-DP converter

### ISSUE THREAD

**Issue by ireun** [emoacht/Monitorian#164]
Hello!

I just want to tell You, that "In contrast, an USB to HDMI/DisplayPort converter which supports DDC/CI is not yet known to exist." is not true, I'm using "HP USB-C to DP Adapter P/N 831119-001 ( KSC0044-D25 )" which is working with DDC/CI, and even DaisyChaining. ;)

**Comment by emoacht** [comment]
It's a good news! I will change it in the future update.
I am moving this topic to Discussions for reference to other users.
