### ISSUE TITLE
Option to change the vertical order of the monitors

### ISSUE THREAD

**Issue by AstonDB** [emoacht/Monitorian#166]
I have an external monitor on top of my laptop and I use this app to adjust the brightness on both (and it works great).
Although in the Monitorian menu, the laptop monitor is displayed above the external monitor. Is there any registry setting or any other way that would enable changing the vertical order in the Monitorian menu?
Could it be a possible future new setting in the app?

Thanks in advance.

**Comment by emoacht** [comment]
Thank you for the suggestion.
The order of monitors in this app is designed to be synchronous with the order which the OS internally uses. That order seems to be reflected to index numbers in `Customize your display` settings of the OS. I have no idea whether a user can change that order.
As for this app, it is technically possible but nit sure there is a strong need.

**Comment by emoacht** [comment]
Added by https://github.com/emoacht/Monitorian/commit/2b661bd764c72634847b142772c542a2595d93e1
