### ISSUE TITLE
[Suggestion] Sync adjusted brightness of SP4 to external monitor

### ISSUE THREAD

**Issue by ireun** [emoacht/Monitorian#17]
Hello!

First at all, thank You very much, i find it very helpful! Do you think, that You could add a feature I've described in the title?

![image](https://user-images.githubusercontent.com/695818/48032622-aff15300-e158-11e8-9707-85002179ff9b.png)

1. You know the 'adjusted brightness' of SP4 display
2. You can change the brightness via DDC on external display
3. Combine these two together!

I know there is 'move together' feature in you app, though it doesn't account for the sunlight sensor of SP4.

**Comment by ireun** [comment]
Also, when I would enable only 'external display' as output in Windows, thus 'Surface Display' becomes not available - Moving together than does not work, as well as changing the brightness via Type Cover shortcuts.

**Comment by ireun** [comment]
You know, 'moving together' also doesn't use ALR curves, i know it won't be perfect, but it's better than anything. Though I thought about something simpler. 

![image](https://user-images.githubusercontent.com/695818/48032622-aff15300-e158-11e8-9707-85002179ff9b.png)

I suggested, to use Surface Display 'adjusted brightness' ( the grey line ) to adjust external display's brightness.

**Comment by emoacht** [comment]
I don't agree such approach is the right direction to achieve the expected goal. It might look simple at a glance but integrating such tricky algorithm will lead a lot of complicated coding not only for the algorithm itself but also UI settings to help users to get their expected results.
If there were a generic ALR curve data, which I haven't found to date, it might be the solution.
