### ISSUE TITLE
Set keys option not available

### ISSUE THREAD

**Issue by PLACEBO92** [emoacht/Monitorian#170]
I am new to this, so forgive me if this is a stupid question, but it seems like the Set keys option is not available? I would very much like to find a way to link the brightness control to my external Lenovo keyboard existing shortcut keys, but can't seem to find the shortcut keys option in Monitorian. 

Any help appreciated. Thanks. 

<img width="144" alt="Screenshot 2021-04-15 220705" src="https://user-images.githubusercontent.com/79737445/114931758-f02f8200-9e36-11eb-84db-b0970ad295e8.png">

**Comment by emoacht** [comment]
As written in [Add-on features](https://github.com/emoacht/Monitorian#add-on-features) section, hot keys & shortcut keys are available on a subscription basis for Microsoft Store version.
