### ISSUE TITLE
Request - Add support for changing monitor input via DDC

### ISSUE THREAD

**Issue by Wyattsb** [emoacht/Monitorian#171]
Would make this perfect if you could also switch monitor inputs along with brightness.

**Comment by emoacht** [comment]
Thank you for the suggestion.
But I don't see a strong merit to incorporate input switching into this app's core functionality, brightness control.

**Comment by jtbrough** [comment]
I think input control might be a powerful feature. And given that Monitorian is a DDC/CI wrapper of sorts, input control is a common use case. Many folks, like myself. find our home offices now being dual use. That being work and personal. 

Being able to drive a software-based KVM solution using keyboard/mouse sharing apps like Mouse Without Borders, Synergy, Logitech Flow, etc - combined with a DDC/CI capable application is the unicorn I'm hunting for. Not only does this feature obviate expensive KVM switching hardware (meaning it could be a valuable paid feature in your app), but it also simplifies the hardware configuration and reduces desk clutter. 

I came across your application while specifically looking for a robust DDC/CI configuration application that provides brightness, contrast, power, and input control - along with some sort of hotkey/event system.

**Comment by Wyattsb** [comment]
+1 to the explanation there, those were my thoughts as well. This was the ONLY DDC/CI wrapper I could find that looked to be a solid application.

**Comment by electronicm** [comment]
+1

**Comment by Kshitiz-Sharma** [comment]
I have a quad-monitor setup that I need to switch between a work laptop and a personal workstation PC.

I wouldn't mind paying for a software solution to avoid the hassle of using the physical controls on each monitor, or to avoid having to buy an expensive KVM switch (the ones that can switch multiple 4K monitors are expensive).

I signed up for a subscription to try the input-switching hotkey available under the add-on features, and then immediately cancelled it. The hotkey only seems to switch one of the monitors, and that part of the interface isn't intuitive.

Brightness control alone is not worth paying for, as there are several applications in the Microsoft Store - such as Twinkle Tray - that do the same job just as well.

**Comment by emoacht** [comment]
@Kshitiz-Sharma "The hotkey only seems to switch one of the monitors"

It changes the input source of last selected monitor. You will need to focus or change any value of a monitor you want to change the input source.

**Comment by Kshitiz-Sharma** [comment]
> [@Kshitiz-Sharma](https://github.com/Kshitiz-Sharma) "The hotkey only seems to switch one of the monitors"
> 
> It changes the input source of last selected monitor. You will need to focus or change any value of a monitor you want to change the input source.

The point is that it is not easily usable for its intended purpose, i.e. changing inputs for multiple monitors easily in a single click/keypress. 

I'm currently trying to build a script using CLI tools for sending DDC code.

**Comment by emoacht** [comment]
For that purpose,  [KeyCommand](https://github.com/emoacht/Monitorian/blob/master/docs/COMMANDS.md#key-commands) should work. It is designed to be flexible and versatile.

**Comment by Kshitiz-Sharma** [comment]
> For that purpose, [KeyCommand](https://github.com/emoacht/Monitorian/blob/master/docs/COMMANDS.md#key-commands) should work. It is designed to be flexible and versatile.

Ah! Well I didn't see that, and now my custom script based on https://github.com/markdwags/DDCSwitch is working.

That should be a simplified UI option for what is a paid subscription software.

Thanks anyway.
