### ISSUE TITLE
Change brightness with scroll wheel when hovering the icon

### ISSUE THREAD

**Issue by AlexZeGamer** [emoacht/Monitorian#174]
Hi,

I suggest to be able to change the brighness by spining the scroll wheel when hovering the icon on taskbar, just as we can do with [EarTrumpet](https://www.microsoft.com/store/productId/9NBLGGH516XP).

![image](https://cdn.discordapp.com/attachments/734384786327732304/844324402296258581/20210518_232214.gif)

**Comment by emoacht** [comment]
Thank you for suggestion.
Technically, it is not impossible but not easy.
Maybe sometime in future.

**Comment by konhi** [comment]
I think https://github.com/markbrents/VolumeScroller could be used as a code example for anyone interested!

**Comment by emoacht** [comment]
@konhi Thanks for the link.
I am geneally reluntanct to use global hook and I don't think this feature has a value enough to resort such a approach.

**Comment by mustafatoktas** [comment]
Learning that this feature won't be coming disappointed me. However, if it will affect performance, it's better not to have it.

I like Monitorian because it's lightweight.

The juice should be worth the squeez

**Comment by mustafatoktas** [comment]
@VVispy 
A very smart idea. The setting may even be disabled by default. Users who wish can activate this.

**Comment by emoacht** [comment]
It sounds like XY problem. What is your actual issue? Is it too tedious for you guys to click the notification area icon to open this app's window?

**Comment by emoacht** [comment]
@VVispy Referencing other apps' behavior is the least convincing reason to add a feature.
