### ISSUE TITLE
Stuck in "adjust range" mode

### ISSUE THREAD

**Issue by AlexZeGamer** [emoacht/Monitorian#175]
* Enable "Change adjustable range"
* Edit a monitor's range without leaving properly this mode
* Right click on the icon
* Disable "Change adjustable range"
* The slider is stuck in "adjust range" mode

![Image](https://media.discordapp.net/attachments/734384786327732304/844326442145808414/unknown.png)

**Comment by emoacht** [comment]
Thank you for reporting.
Indeed it is not nice.
I will change that behavior.

**Comment by emoacht** [comment]
Fixed by a07a5785d3042c26b615d99d1d02fa87a76ccf59
