### ISSUE TITLE
Keys setting not available in Ver 2.18.1 

### ISSUE THREAD

**Issue by sharicov** [emoacht/Monitorian#182]
Cannot set keys in Ver 2.18.1, option not showing in menu
![image](https://user-images.githubusercontent.com/1933626/120108187-bf987300-c16c-11eb-9887-d4ef6ac88be6.png)

**Comment by emoacht** [comment]
As written in readme, key settings for hot keys and shortcut keys are offered in the Microsoft Store version.

**Comment by sharicov** [comment]
Thanks for clarification, wasn't that clear from the readme even after you pointed that out.
