### ISSUE TITLE
Monitor connected via HDMI is not detected

### ISSUE THREAD

**Issue by momanatorz** [emoacht/Monitorian#183]
I switched the connection of my external monitor from
USB -C to USB- C 
TO
HDMI to mini HDMI

OS WIndows 10
Device: MSI Prestige A10SC

Now the monitor is not detected by Monitarian anymore. I have tried to restart the app/re-install and reboot my WIndows 10 laptop as well with no luck.

Any logs I can provide to assist I am happy to help troubleshooting as I am subscribed to this great app.

Mo

![1](https://user-images.githubusercontent.com/85713893/121610649-78c24b80-ca91-11eb-898e-284784937369.png)
![22](https://user-images.githubusercontent.com/85713893/121610656-79f37880-ca91-11eb-9d03-07f1bff25e9f.png)

**Comment by emoacht** [comment]
I guess USB-C to USB-C connection was in DisplayPort Alt Mode. Have you checked DDC/CI is enabled for both HDMI ports?
You can confirm the current state by [Probe.log](https://github.com/emoacht/Monitorian/blob/master/README.md#probe).

**Comment by emoacht** [comment]
@momanatorz Do you have any additional information? If no, I will close this issue shortly.
