### ISSUE TITLE
Same monitor not controllable from 1 of the 2 laptops

### ISSUE THREAD

**Issue by PalashBansal** [emoacht/Monitorian#184]
BenQ GW2780 monitor is connected using HDMI cable to 1 laptop(ASUS) and monitorian allows controlling brightness.
Unplugging from ASUS and plugging to Dell(Office laptop) and monitorian shows error-
![image](https://user-images.githubusercontent.com/6822117/121647476-13338680-cab4-11eb-8efb-3407678a996d.png)

Tried changing monitor settings- toggling of bright intelligence and DDC/CI settings from monitor hardware buttons but not help.

Please tell steps to debug this issue?
Where to find debug data from monitorian installation directory?
What steps can be taken to resolve this issue?

**Comment by emoacht** [comment]
Thank you for reporting.
Is this message shown in Monitorian on ASUS (leaving) or that on Dell (coming)?
Please read [Reporting](https://github.com/emoacht/Monitorian/blob/master/README.md#reporting) and post Probe.log and Operation.log.

**Comment by PalashBansal** [comment]
> Thank you for reporting.
> Is this message shown in Monitorian on ASUS (leaving) or that on Dell (coming)?
> Please read [Reporting](https://github.com/emoacht/Monitorian/blob/master/README.md#reporting) and post Probe.log and Operation.log.

Sry, Can't understand meaning of 'leaving' and 'coming'
Issue never comes in my ASUS but always comes in DELL laptop
As Dell is office laptop with restrictions, couldn't get monitorian from microsoft store but downloaded from github releases. And can't access Add-on features. (Monitorian in ASUS is also from github releases just FYI)

PFA log files.
[probe.log](https://github.com/emoacht/Monitorian/files/6639631/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/6639632/operation.log)
They just state that monitor is unreachable, but no detailed info. I wonder if that's the case then how is it able to tell monitor name correctly.
Also, noticed that when clicking "Rescan" button for the first time, it made beep sound and changed external monitor brightness to lowest(behavior is as weird as office laptop)

**Comment by PalashBansal** [comment]
Just connected to ASUS and took logs too incase want to compare-
[probe.log](https://github.com/emoacht/Monitorian/files/6640588/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/6640589/operation.log)

**Comment by emoacht** [comment]
Thanks for the logs.
DDC/CI is not enabled or unusable in the connection with Dell.
