### ISSUE TITLE
很好的应用，如果能自定义快捷键调节就更好了

### ISSUE THREAD

**Issue by maojinbing** [emoacht/Monitorian#19]
很好的应用，如果能自定义快捷键调节就更好了

**Comment by emoacht** [comment]
Unfortunately I don't understand Chinese.
Anyway, I am quite negative to implement keyboard shortcut.

**Comment by geekyouth** [comment]
<https://translate.google.com/?source=gtx#view=home&op=translate&sl=auto&tl=en&text=很好的应用，如果能自定义快捷键调节就更好了>

![image](https://user-images.githubusercontent.com/12899262/51720529-f89a1780-2088-11e9-8f32-aa769ed75596.png)
