### ISSUE TITLE
Suggestion: new menu command: `Refresh Monitor List`

### ISSUE THREAD

**Issue by schittli** [emoacht/Monitorian#191]
Good evening

thank you for this great tool!
_I would have even bought the update, but of course not in the M$ Store because it's almost impossible to manage M$ Store software (extremely annoying UI, no scriptable API) and the M$ Store now also 'offers' malware._

Anyway, 
### I have a suggestion for improvement: a tray menu command to re-detect the connected monitors
Every few days it happens that one has to quit and restart Monitorian because not all monitors are recognized.

So it would be great if Monitorian would provide a tray menu command to re-detect the connected monitors.

Thanks a lot, kind regards,
Thomas

**Comment by emoacht** [comment]
As I have responded to similar suggestions several times, it is not a preferable solution.
I have continuously improved the detection process and it is not expected to happen. Once a monitor is found controllable, it will never simply disappear as long as the monitor is connected. If it disappears, the monitor or its connection would be problematic.

If you have experiencing the detection issue regularly, you can provide a good sample of operation.log which I can look into. Please see [reporting](https://github.com/emoacht/Monitorian#reporting) section.
