### ISSUE TITLE
Fast access to night light feature fo each monitor

### ISSUE THREAD

**Issue by iJahangard** [emoacht/Monitorian#192]
I like the windows ability of night light to protect eyes from Blue light (idk if it is actually does or not:)

But a quick icon in monitorian is a great option that makes the app more valuable

**Comment by emoacht** [comment]
Thanks for the suggestion but I am not interested in night mode.
In the first place, it can be set for each monitor independently?

**Comment by iJahangard** [comment]
> Thanks for the suggestion but I am not interested in night mode.
>
For you not ! But for people with glasses is a big help!
> In the first place, it can be set for each monitor independently?
>
I guess yes but for people who disabled action center
This will not easy

**Comment by emoacht** [comment]
Let me know when you find the way to do so.
Until then, I close this issue.
