### ISSUE TITLE
when I open the app this comes up. Nothing happens, please help. Thanks in advanced.

### ISSUE THREAD

**Issue by cheesedog13** [emoacht/Monitorian#2]
![screenshot 4](https://user-images.githubusercontent.com/35661399/35195733-c30a824c-ff02-11e7-8fc6-6c734beed63b.png)

**Comment by emoacht** [comment]
Hello, cheesedog13.
Is your monitor is external (connected to desktop PC) or internal (notebook or tablet PC)?
If an external monitor, the monitor must be capable of DDC/CI as noted in the remarks section of readme.
emoacht
