### ISSUE TITLE
Feature Request: Keyboard shortcut 

### ISSUE THREAD

**Issue by shramanshraman** [emoacht/Monitorian#20]
Hi, in my HP Probook fn+brightness keys are not working and I want to use Monitorian as a substitute for that can u please add a feature such that using keyboard shortcut we can control screen brightness...Some thing like control+n for screen brightness up and control+m for brightness down
percentage wise....

Would be very handy because for me everytime i have to right click on desktop and open display settings to change brightness or I have to click monitorian for slider to show up and then change...

**Comment by emoacht** [comment]
To be clear, I am quite negative to implement keyboard shortcut.

**Comment by shramanshraman** [comment]
I would even pay u money if you can implement keyboard shortcuts

**Comment by mashed-potatoes** [comment]
> I would even pay u money if you can implement keyboard shortcuts

Hi, please contact me :smile:

**Comment by teatua** [comment]
Hi, are there keyboard shortcuts for this awesome tool please ?

**Comment by emoacht** [comment]
Please check [Hot keys & Shortcut keys](https://github.com/emoacht/Monitorian#hot-keys--shortcut-keys)
