### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by bzumik1** [emoacht/Monitorian#201]
Hello, I could help you with Czech translation if you are interested.

**Comment by emoacht** [comment]
Thanks for you help.
You can create Czech language resources file copying English one.
https://github.com/emoacht/Monitorian/blob/master/Source/Monitorian.Core/Properties/Resources.resx

**Comment by bzumik1** [comment]
I will start working on it ASAP, I am just quite busy at the moment.

**Comment by emoacht** [comment]
I am closing this issue but feel free to send the PR when it is ready.
