### ISSUE TITLE
Store doesnt show update

### ISSUE THREAD

**Issue by schroef** [emoacht/Monitorian#204]
v2.16.0
win 11 22000.100

Im running v2.16 and i notice the windows store doesnt show an update version. Out of curiosity i check the github and noticed its at v3.0 then check the updated Microsoft store and noticed it doesnt show an update button.

**Comment by emoacht** [comment]
Ver 3.0 has been already published in Microsoft Store. I have no idea but somehow reloading the contents of Microsoft Store app can help.

**Comment by schroef** [comment]
Not sure how to do that, i uninstalled and reinstalled. got it solved now. though it looks like app doesnt respond from a restart. I have now need to active the menu from toolbar and then it works.

**Comment by emoacht** [comment]
As of Ver 3.1, I experimentally added the function to update this app directly from Microsoft Store without using Microsoft Store app. It will appear under the top of menu window when updated versions are available.
So far It seems to work well.
