### ISSUE TITLE
Exception at start

### ISSUE THREAD

**Issue by shmykelsa** [emoacht/Monitorian#22]
[exception.log](https://github.com/emoacht/Monitorian/files/2578307/exception.log)

**Comment by emoacht** [comment]
Hi shemyklsa,
Thank you for reporting.
Although it is not clear from the log where the cause is, I guess it lies not inside the app but outside of the app. Does your system fulfill the requirements?

**Comment by emoacht** [comment]
Without further information, I will close this issue shortly.
