### ISSUE TITLE
Microsoft Store is blocked - how can I license it anyway?

### ISSUE THREAD

**Issue by schittli** [emoacht/Monitorian#222]
Hello

because of the really bad quality, even worse usability and missing features for professional IT Departments in M$ Store, it is blocked.

Is there another way to buy the license?

Thanks a lot, kind regards,
Thomas

**Comment by emoacht** [comment]
I see. I agree that Microsoft Store app on Windows 11 is not so good. It might be changed on Windows 11.
I will think about it.
