### ISSUE TITLE
Problem in the display of a dark background in Monitorian 3.5.0.

### ISSUE THREAD

**Issue by radio222** [emoacht/Monitorian#226]
The configuration of two computers and monitors is the same, Windows 10 (1809).
On one computer when installed Monitorian 3.5.0 displays settings and adjustments on a dark background,
As in and in the Windows 10 itself - a dark topic.
On another computer when installed Monitorian 3.5.0 displays settings and adjustments on a white background,
Although in Windows 10 is a dark topic.
On the same computer, if you install the old version of Monitorian 2.1.9.0 - then the dark background will be displayed,
Like on the first computer.
How can I fix the problem on the second computer, what would the background be dark?

![Screenshot 12-09-2021, 16-21-27 = Black](https://user-images.githubusercontent.com/90560555/132989241-e2c23a2a-d47e-4215-b1ae-0c9a9d41831b.jpg)
![Screenshot 12-09-2021, 16-23-22 = Black Option](https://user-images.githubusercontent.com/90560555/132989289-ddd5f8e5-ae6f-42cd-a631-f0e45a62c193.jpg)
![Screenshot 12-09-2021, 16-24-20](https://user-images.githubusercontent.com/90560555/132989474-cc1364e7-da37-4892-8b86-55b6a0cac034.jpg)
![Screenshot 12-09-2021, 16-26-02](https://user-images.githubusercontent.com/90560555/132989475-994a84e5-c156-4d9f-8c23-7430d9d55159.jpg)
![Screenshot 12-09-2021, 16-26-11](https://user-images.githubusercontent.com/90560555/132989476-b71b961d-747e-4dbc-a04f-dd68de1ed752.jpg)

**Comment by emoacht** [comment]
Thanks for the reporting.
Regarding the system which show the light theme,
- what is the settings of "Personalize" -> "Colors" -> "Choose your default windows mode"?
- what are the values in `KEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize` in Registry Editor?

**Comment by radio222** [comment]
Answer:

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize]
"ColorPrevalence"=dword:00000000
"EnableTransparency"=dword:00000000
"AppsUseLightTheme"=dword:00000000

**Comment by radio222** [comment]
What is the settings of "personalize" -> "Colors" -> "Choose Your Default Windows Mode"?

**Comment by emoacht** [comment]
Thanks for the information.
I found the default value when checking the color theme is inappropriate.
I will fix it.

**Comment by emoacht** [comment]
Fixed by c75406a00fa97dfa518e73d933f8c24a4f61d4e2

**Comment by radio222** [comment]
We will wait, thanks!
The Monitorian program itself is the best that I found for Windows 10.

**Comment by emoacht** [comment]
Published as Ver 3.5.1
