### ISSUE TITLE
Random Detection of External Monitor

### ISSUE THREAD

**Issue by atk3402** [emoacht/Monitorian#228]
I usually can't use the app for my external monitor(Samsung Odyssey G5) which is connected with mini-DP to DP cable to my laptop. It detects randomly. When it detects, I can set brightness without any problem.

[operation.log](https://github.com/emoacht/Monitorian/files/7155491/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/7155492/probe.log)

**Comment by emoacht** [comment]
Thanks for the reporting and logs.
According operation.log, the Samsung monitor in question does not to respond to DDC/CI command most time, while sometimes it responds.
If I were you, I will check the connection between the system and monitor and change the way of connection. It may or may not change the situation.
