### ISSUE TITLE
Unison function does not work before this app is shown for the first time

### ISSUE THREAD

**Issue by schroef** [emoacht/Monitorian#232]
v3.5.1.0
Windows 11 22468.1000

For a while now my second monitor will not respond to the input of Monitorian. It will only respond once i click the taskbar icon. If dont this only main monitor will react to the app.

**Comment by emoacht** [comment]
Thanks for the report.
From the viewpoint of this app, there should be no difference between primary and secondary monitors.
If you provide operation.log, I could look into the issue. Otherwise, I have no idea.

**Comment by schroef** [comment]
Okay got the log attached
[operation.log](https://github.com/emoacht/Monitorian/files/7248229/operation.log)

**Comment by emoacht** [comment]
Thanks for the logs.
In those logs, both monitors look quite normal and healthy. So you mean the external one (Dell) as second monitor? If so, there would be the number of reasons for an external monitor to fail to respond.
The operations.log is cumulative in nature and the events will be appended as long as it is on. Could you try to capture the timing when the issue happens and provide a log which includes events befure and after the issue?

**Comment by schroef** [comment]
well i just tried the shortcut and now does seems to work. Ill need to check again after a restart i guess.
PS what you mean by timing?

**Comment by emoacht** [comment]
I mean when you notice the issue happens.

**Comment by schroef** [comment]
AH like that, ill test again tonight after work.

**Comment by schroef** [comment]
Just checked it and as reported initially second monitor does not respond when i use the shortcut. Only when ive clicked the app icon once in the traymenu does it seem to work on both monitors at the same time.

**Comment by emoacht** [comment]
Could you explain what you did step by step in detail?

**Comment by schroef** [comment]
i have monitorian as startup item. I was trying to figure out how i got both display to work with main keyboard shortcut working. I kinda remember i made shortcuts for them, but cant seem to find them anymore. That was on Windows 10 though, im on Windows 11 now.

How i use the app is using build shortcut for the main display to brighten/darken using fn+F2/F3. After a startup only the main build display responds to that code. When i open the Monitorian menu once, then both monitors will work.

**Comment by emoacht** [comment]
Thanks for the explanation.
So, could you turn on `Restore set brightness` temporarily and try to hit hot keys for the second monitor and upload the operations..log which includes the events after the startup?

**Comment by schroef** [comment]
I run again after the startup. I noticed in that save state that in the beginning it only shows "Generic PnP Monitor (Internal)".
Only when i click the icon and show this menu, just once, then they start to work. I can also see that in that log. After that they both show in that log file.
![monitorian-popup](https://user-images.githubusercontent.com/6923008/135540824-7f962afb-0f2d-4095-88ec-e33f9ebebca6.png)

But ill check again. Currently a win11 update i going. So once thats done ill do this test again. Though im not sure at what point, at startup im not sure if the app is loaded already

this is the log before the startup. It does show only internal display reacts in the beginning. Then when you see both, i have activated that menu
[operation.log](https://github.com/emoacht/Monitorian/files/7262948/operation.log)

**Comment by schroef** [comment]
i can 100% confirm the second monitor only works when i active the popup menu. Ive now tried the shortcut right after startup. I also noticed monitorian is not running right away. So i waited until it got loaded then start using the shortcut nothing. Untile i activate the menu at 19:30 after that i also see both monitors in the log.

heres that log file again
[operation.log](https://github.com/emoacht/Monitorian/files/7263051/operation.log)

**Comment by emoacht** [comment]
Thanks for the log.
Howver, I could not find any clue in it.
How long does this state (the external monitor does not respond) contine if you don't touch the icon in the notification area? Forever?
What hot koy you use to change the external monitor?

**Comment by schroef** [comment]
Yes it will not respond until i click the tray icon or execute the app once more, then the popup shows and only then does it react to the shortcut.

The shortcut is the build shortcut for the main monitor, its fn + f2/f3
Though i short remember it vagilue i made app shortcuts, but cant seem to find those anymore.

**Comment by emoacht** [comment]
I am really puzzled.
I am asking what kind of hot key (i.e. Brighten, Brighten all, or equivalent key for indivisual monitor) and its key combination (i.e. Alt + K) for the external monitor.
I cannot understand what you mean by "build" shortcut.
I am not asking information on hot key for your "main" monitor. I thought you are talking about your "second" monitor "DELL U2419H". Is it right?
"fn" is not valid key for hot keys. It merely changes on/off state of function keys.

**Comment by schroef** [comment]
Im using the build hotkeys for the main display, these are fn + f2 to brighten & fn + f3 to darken. When the Monitorian popup has shown once, then both display react to that same hotkey. If i dont show the popup, only the main monitor responds to that hotkey.

By build in hotket, i mean the trigger for 3rd action the F-keys have. Most laptops have a third action set to those F-keys. Users then need to use the FN key to trigger those
see image below
![Omen 15 keyboard](https://h30434.www3.hp.com/t5/image/serverpage/image-id/275342i32B744BB35601A6D)

**Comment by emoacht** [comment]
Finally I understand what you are talking about. So you use built-in hardware hot keys (not this app's hot keys) to change the brightness of laptop display and expect the brightness of external monitor to follow it by unison function.
Yes, it does not work before the main window of this app is shown for the first time. It is because unison function depends on the sliders in main window and they are instantiated when the main window is shown for the first time. It is a limitation came from the mechanism of unison function and cannot be easily changed.

**Comment by schroef** [comment]
is there no method for making this able to run from bootup. Since the app has all the settings and it also sees the second monitor. It would be nice if the dual triggering would just work straight away

**Comment by emoacht** [comment]
Fixed by ed6d9f1612de76cd2cd29228da72821dbc2681a2

**Comment by schroef** [comment]
I'll check it out tonight

**Comment by schroef** [comment]
Sorry i meant 3.6.40 and 3.6.5.0

What i meant with the checkbox, in the above screengrab you see "enable moving in unison". What got me confused is "enable" as this normally means you already enable it. But this enable the sliders to be visible. So i thought, perhaps name it differently, so something like "Show unison sliders".

**Comment by emoacht** [comment]
I don't agree. I will lock this thread.
