### ISSUE TITLE
Unison for contrast as well & option for buttons instead of slider

### ISSUE THREAD

**Issue by JustWhelmed** [emoacht/Monitorian#233]
I think there should be a unison option for contrast as well. Both an option to link multiple contrasts and an option to link contrast and brightness.

Another option I'd love to see is having buttons instead of sliders (maybe in increments of 10).

Thank you for your work on this incredible app!

**Comment by emoacht** [comment]
Thank for the suggestion.
Unison is in fact a quite complex feature and I have no plan to apply it to contrast at this moment.
The feature of brightness button to incremet brightness is reproduced in the brightness number. You can increment the brightness by tapping the number.
