### ISSUE TITLE
Old Belinea display not recognized/useable in version 3.4.0 and newer

### ISSUE THREAD

**Issue by kima-machn** [emoacht/Monitorian#236]
I have an old Belinea display (Belinea101735) which I used to control with Monitorian 3.3.0. After an update, it stopped recognizing (not shown in popup) this second screen. This issue occurs on both my private and my work laptop. I tested every version from 3.4.0 to 3.6.0 with the same result.

Maybe the display doesn't properly report its capabilities and therefore stopped working in newer versions.

I attached some (hopefully helpful) debug logs. In version 6.0.0 I used the rescan monitors functions without success. The log contains '"IsReachable": false', maybe that is a hint for the cause of the problem.

[probe_v330.log](https://github.com/emoacht/Monitorian/files/7265234/probe_v330.log)
[probe_v600.log](https://github.com/emoacht/Monitorian/files/7265235/probe_v600.log)
[operation_v600.log](https://github.com/emoacht/Monitorian/files/7265236/operation_v600.log)

**Comment by emoacht** [comment]
Thanks for the report and logs.
It is clear that the gabage data at the end of "CapabilitiesString" is the reason why this string is regarded as invalid in newer version. Your monitor seems not good at responding to the inquiry for capabilities.
Having said that, it is not difficult to dealt with it.

**Comment by emoacht** [comment]
Fixed by 386b88183dbe660c6f5d045ee62759494fb47c86

**Comment by kima-machn** [comment]
Sorry for the late response. Version 3.6.3.0 (and therefore 386b881) did in deed fix the problem. Thank you very much!
