### ISSUE TITLE
Exceptions at startup, sometimes

### ISSUE THREAD

**Issue by cdanis** [emoacht/Monitorian#24]
I've been happily using Monitorian for some time.  However occasionally I get repeated exceptions at startup time, which go away some time later.  Not sure what causes it!  If I can consistently reproduce I will update the bug.  
[exception.log](https://github.com/emoacht/Monitorian/files/2589612/exception.log)

**Comment by emoacht** [comment]
Hi cdanis,
Thank you for reporting.
It seems to be the same issue as #12 and it is recently discussed in #23.

**Comment by cdanis** [comment]
I will watch windows store for the new version. Thank you!

**Comment by emoacht** [comment]
Ver. 1.7.4 is now available in Microsoft Store.
