### ISSUE TITLE
After update subscription information cannot be restored

### ISSUE THREAD

**Issue by lebucur** [emoacht/Monitorian#240]
I do not know what version I had previously, but now, after updating to 3.6.6.0 the program does not recognize my purchase.
I tried clicking "Reload subscription information" - with no effect, and trying to buy the pro features but it won't let be because MS Store recognizes my subscription.

**Comment by lebucur** [comment]
I also tried reinstalling the program (and a reboot) but with no success.

**Comment by lebucur** [comment]
I should mention that I'm using my work laptop, and I bought the subscription on my personal account (which is linked to MS Store) because I do not want to save the credit card information on the work account.

**Comment by emoacht** [comment]
@Dragonsky8 Could you try `Reload subscription information`?
As I wrote just before, the code of this app remain almost unchaged. I wonder if Micrsoft changed the reponse to Store API.

**Comment by emoacht** [comment]
Thanks. I will upload a version which can record the responses from Store API shortly.

**Comment by lebucur** [comment]
How does one access the hidden menu?

**Comment by emoacht** [comment]
Please read [Probe](https://github.com/emoacht/Monitorian#probe).

**Comment by lebucur** [comment]
I don't know, it simply works now (after the update).

**Comment by emoacht** [comment]
Okay, so I understand that in your case, the issue is sovled.

**Comment by Dragonsky8** [comment]
Indeed. Now the renew subscription works. For me, issue has been solved.

**Comment by lebucur** [comment]
Thanks for the quick reply.I’ve just tried it on my personal laptop (where the subscription account is the only one linked to the MS Store) and Monitorian behaves the same.When I try to buy it, I get this message: “Looks like you already own this”.On the personal laptop I have “Windows 10 Enterprise 21H1 19043.1237”.On the work laptop I also have W10 Enterprise. Sent from Mail for Windows From: emoachtSent: Monday, October 11, 2021 03:05To: emoacht/MonitorianCc: Loredan E. Bucur; AuthorSubject: Re: [emoacht/Monitorian] After update subscription information cannot be restored (#240) Thanks for the report.What is your OS version?The subscription is tied with a particular account and sometimes, the accounts on a system could be very complicated...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
