### ISSUE TITLE
Lost ability to control external monitor after upgrading to windows 11

### ISSUE THREAD

**Issue by latonita** [emoacht/Monitorian#242]
Hi. Recently moved to windows 11.
Can't control my external AOC 2460 (hdmi) monitor anymore. 

[probe.log](https://github.com/emoacht/Monitorian/files/7341386/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/7341388/operation.log)
.

**Comment by emoacht** [comment]
Thanks for the report and logs.
Unfortunately, I can tell from the logs, the external monitor does not respond to DDC/CI command.
