### ISSUE TITLE
Startup error : System.InvalidCastException

### ISSUE THREAD

**Issue by HyperNovax** [emoacht/Monitorian#243]
Hello,

I update Windows 10 to 11. I installed Windows 11 from scratch.
The application worked fine in Windows 10 with my screens.
But now I have an error : 
```
[Date: 14/10/2021 23:06:25 Ver: 3.6.5.0]
System.InvalidCastException: Le cast spécifié n'est pas valide. HResult: -2147467262
   à System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
   à System.Management.SecuredIWbemServicesHandler.ExecQuery_(String strQueryLanguage, String strQuery, Int32 lFlags, IWbemContext pCtx, IEnumWbemClassObject& ppEnum)
   à System.Management.ManagementObjectSearcher.Get()
   à ScreenFrame.Helper.OsVersion.GetOsVersion()
   à ScreenFrame.Helper.OsVersion.IsEqualToOrGreaterThan(Int32 major, Int32 minor, Int32 build, String propertyName)
   à ScreenFrame.VisualTreeHelperAddition.GetDpi(Visual visual)
   à ScreenFrame.Movers.StickWindowMover.TryGetAdjacentLocationToTaskbar(Double windowWidth, Double windowHeight, Rect& location)
   à ScreenFrame.Movers.StickWindowMover.TryGetAdjacentLocation(Double windowWidth, Double windowHeight, Rect& location)
   à ScreenFrame.Movers.BasicWindowMover.HandleWindowPosChanging(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à ScreenFrame.Movers.WindowMover.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I have the last version of NET Framework.

You have an idea ?

**Comment by emoacht** [comment]
If you can, could you test the following code on your environment and check if there is difference between GetOsVersion1 (current version) and GetOsVersion2 (slightly changed version)?
https://gist.github.com/emoacht/b04be66acc9c4f43a667e8e8599dcd9a

**Comment by emoacht** [comment]
I am still wondering wht it happens on your environment. Could you upload your test project somewhere in GitHub?

**Comment by emoacht** [comment]
I am still wondering why it happens on your environment. If calling in another thread helps to avoid it, it may have something to do with thead apartment. Could you upload your test project in somewhere in GitHub?

**Comment by emoacht** [comment]
This WMI classs internally calls COM and COM has thread apartment thing that is hard to delve into.
So, to save time, I am inclined to change to other method.

**Comment by HyperNovax** [comment]
You still wish I upload my test project ?

I feel embarased you take time for my problem of which I am the only one to have.

**Comment by emoacht** [comment]
Yes, I do. There might be something interesting to me.
