### ISSUE TITLE
Feature Request - Hotkey determine which monitor to brighten by cursor location

### ISSUE THREAD

**Issue by va-jones** [emoacht/Monitorian#244]
Hi, I would like to suggest a feature enhancement to the hot key ability. Instead of manually picking the monitor using a separate hotkey, the current darken/brightness hotkeys will determine the monitor by which monitor the cursor is on.

It would work similarly to how [ExternalBrightnessDisplay ](https://www.nesveda.com/projects/ExternalDisplayBrightness/) works on  Mac.

**Comment by emoacht** [comment]
Have you tried Quick access (Show at cursor position) #238?
You can show the slider at the cursor position and move it both by hot keys.
