### ISSUE TITLE
Unique ID of each monitor

### ISSUE THREAD

**Issue by iFieryGod** [emoacht/Monitorian#251]
Does this application allow you to store information on the Monitor, for instance what if you wanted each monitor to have a unique name and ID property. 

Keeping track of monitors is a huge task and although not a major concern, it would be a great feature.

**Comment by emoacht** [comment]
Each monitor is given an unique ID by the OS, which is named "device instance ID". It has been used by this app to identify each monitor and store persistent settings for each monitor. You can get this ID by `/get` [command-line options](https://github.com/emoacht/Monitorian#command-line-options).
