### ISSUE TITLE
Missing string for translation

### ISSUE THREAD

**Issue by TheVoodoo** [emoacht/Monitorian#255]
Can't find the string for "Restore set brightness" in the .resx file. Is this one hardcoded?
Using the Microsoft Store version. (language = german)

![image](https://user-images.githubusercontent.com/16653359/141746549-8c2b14c4-7469-4580-8cbb-04158af31a1a.png)

**Comment by emoacht** [comment]
The description of this feature is relocated to public repository by d2505f2c5094c1843ea90f5debdad78b3a6e5652
