### ISSUE TITLE
[Question] GetMonitorHandles return different rect sizes

### ISSUE THREAD

**Issue by steam3d** [emoacht/Monitorian#256]
Hi. I try understanding how to get monitor handles.

https://github.com/emoacht/Monitorian/blob/c64b66595f655e5b7410ae3d32c17d83caccda2a/Source/Monitorian.Core/Models/Monitor/DeviceContext.cs#L315

I looked at your code, but when I try to repeat it, I get completely different rect sizes. 

Values from my test WPF app:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/30986874/142725211-bfa081db-b2fe-4e54-a13a-ea2786fc0f4a.png">

Values from Monitorian:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/30986874/142725239-935cf698-7f25-4ec2-9b2a-dbe9cb2a04bf.png">

Maybe I'm missing something, project settings or something else?

**Comment by emoacht** [comment]
Probably you forgot to add Per-Monitor DPI settings in application manifest.
See https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process#setting-default-awareness-with-the-application-manifest

This app uses the following settings:
https://github.com/emoacht/Monitorian/blob/4c8927cf7d9967e0bd3d6d94f120a58104fa5ff9/Source/Monitorian/Properties/app.manifest#L53-L58

**Comment by steam3d** [comment]
I found issue with app.manifest `true/PM` and `PerMonitor`.  The app will always get the wrong DPI after connecting second monitor and set it as primary. You always get the DPI of first monitor.

But if instead of using app.manifest use the program way and call `SetPerMonitorDPIAware` before any window was created you will get always correct DPI values for each display even if you change DPI from windows settings.
https://docs.microsoft.com/en-us/windows/win32/hidpi/declaring-managed-apps-dpi-aware

**Comment by emoacht** [comment]
This issue reminds me of the inability to track the correct DPI of the monitor where the notification area currently locates especially in the case where the PRIMARY taskbar locates inside the monitor OTHER THAN PRIMARY monitor.

I have some ideas for this purpose but not sure which is the best approach at this moment.

**Comment by steam3d** [comment]
The notification area can be only on primary display is not?

**Comment by emoacht** [comment]
The primary taskbar which contains the notification area can be moved to and located in any monitor. It makes things complicated.

**Comment by emoacht** [comment]
This should be relieved by bf47b486fe9682c62bf2c4a28579f9f4e7ce06e4
When the notification area icon is clicked, it will trigger checking the current DPI of notification area and apply it to the icon.

**Comment by emoacht** [comment]
Released.
