### ISSUE TITLE
Popout obscured by taskbar (incorrect height)

### ISSUE THREAD

**Issue by jesstech** [emoacht/Monitorian#257]
The following happens semi-regularly, typically after waking from sleep, disconnecting an external display, etc. 

![image](https://user-images.githubusercontent.com/607359/142737803-edd3d0d0-b97c-4bc4-b22f-47295c2183d1.png)

No amount of fiddling with the settings in the right-click context menu will reset the popout.  The incorrect size persists after closing and re-opening Monitorian.  The popout maintains its incorrect height even after moving the taskbar to the right side of the screen:

![image](https://user-images.githubusercontent.com/607359/142737896-3fd64449-0cf2-4a71-be46-61ac25c7ea98.png)

Just hazarding a guess that this may be due to height or offset calculations related to DPI scaling, particularly if multiple displays use different DPI scaling settings, as I've had similar issues with apps in the past.

Windows 10 21H1 (19043.1348)
Monitorian 3.6.10.0

**Comment by emoacht** [comment]
Thanks for the report.
This window state indicates that no monitor is found after rescanning monitors. I have no idea about the root cause at this moment and need the logs.
I don't think it is related to DPI scaling because I designed the UI of this app independent from Per-Monitor DPI of monitors.
