### ISSUE TITLE
Incredible stutter when using 2 external displays

### ISSUE THREAD

**Issue by omegamalkior** [emoacht/Monitorian#259]
Full specs:
Laptop- HP Spectre x360 14, i7-1165G7, 16GB ram
External GPU- Razer Core X with a Gigabyte Aorus RTX 3070 Master
Display 1: LG 27GN850-B, 1440p 144Hz Nano-IPS
Display 2: Philips 241E1, 1080p 75Hz 

If I turn on Monitorian for some reason there is an incredible stutter consistently each time I move the mouse cursor or move a Window anywhere. I have tried changing Nvidia GPU drivers and they all cause the same (version 496.98). Already tried turning off G-sync and a bunch of other settings tweaks and nothing fixes this except exiting out of Monitorian which is the only fix. Closing out other active apps solves nothing.

Version of the app installed: 3.6.8.0
Any help or advice would be appreciated.

**Comment by emoacht** [comment]
Thanks for the report.
Your device seems quite cool but something unusual. I have never heard such case of sound so far and have no idea about it.

1. I would like to ask when the sound exactly starts? It starts when the window of this app is first shown?
2. If it related to the visual effects of this app, you can disable transparency effects by `/texture none` command-line option. You can store that option in the hidden menu. Please refer [Probe](https://github.com/emoacht/Monitorian#probe) on how to open the hidden menu.

**Comment by omegamalkior** [comment]
> Thanks for the report. Your device seems quite cool but something unusual. I have never heard such case of sound so far and have no idea about it.
> 
> 1. I would like to ask when the sound exactly starts? It starts when the window of this app is first shown?
> 2. If it related to the visual effects of this app, you can disable transparency effects by `/texture none` command-line option. You can store that option in the hidden menu. Please refer [Probe](https://github.com/emoacht/Monitorian#probe) on how to open the hidden menu.

It's not a sound the issue, it's the fluidity of the desktop as a whole. You know when a desktop is at 144Hz but something makes it lag to 90Hz or 60Hz and you feel the smoothness go away? Well imagine that but up an downs, seeming a desktop wide stutter. That's my issue right now. 

1. The stutter starts as soon as I open the app with the 2 monitors present. Doesn't happen when I use one monitor but with 2. 
2. Tried disabling those textures but the stutter still happens. How do I revert that texture change btw? Since it didn't fix it.

**Comment by emoacht** [comment]
I see. Then I have no idea at all.
You can revert the option just by deleting it.
