### ISSUE TITLE
No adjustmet of external monitor via hotkeys

### ISSUE THREAD

**Issue by elektrinis** [emoacht/Monitorian#260]
I have a 4K monitor connected to DELL XPS13 9310 laptop via Thunderbolt3 dock WD19TB.
The monitor is detected fine, and brightness can be adjusted when dragging the sliders (locked together).
However the brightness of external monitor does not change when adjusted with inbuilt hotkeys "bridghtness up" and "brightness down" on the keyboard (only internal screen is adjusted), even though both sliders are moving.

**Comment by emoacht** [comment]
Thanks for the report.
It sounds strange. Could you trun on `Restore set brightness` and recond [operation.log](https://github.com/emoacht/Monitorian#operations) and post it?

**Comment by elektrinis** [comment]
Log quoted below.
Pleane note that I had "Defer change until stopped" checked and "Restore set brightness" unchecked.
After playing with these settings I have found that in my case the only working configuration is for Defer.. to be not checked ans Restore... checked.

`[Date: 2021-12-01 17:45:23 Ver: 3.6.10.0]
Enabled

[Date: 2021-12-01 17:45:30 Ver: 3.6.10.0]
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 50 <- 60
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 60 <- 70
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 70 <- 80
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 80 <- 90
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 90 <- 80
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 80 <- 70
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 70 <- 60
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 60 <- 50
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 50 <- 40
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 40 <- 50

[Date: 2021-12-01 17:45:36 Ver: 3.6.10.0]
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 50 <- 40
HandleBrightnessChange "PHL 328E1"
 [Save] 5 <- 0
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 40 <- 50
HandleBrightnessChange "PHL 328E1"
 [Save] 0 <- 5
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 50 <- 60
HandleBrightnessChange "PHL 328E1"
 [Save] 5 <- 15
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 60 <- 50
HandleBrightnessChange "PHL 328E1"
 [Save] 15 <- 5

[Date: 2021-12-01 17:45:38 Ver: 3.6.10.0]
HandleBrightnessChange "DELL SHP14F7 Display"
 [Save] 50 <- 50
HandleBrightnessChange "PHL 328E1"
 [Save] 5 <- 5

`

**Comment by emoacht** [comment]
Thanks. I could reproduce it in combination with `Defer change until stopped`.

**Comment by emoacht** [comment]
This should be fixed by 469c394f477ada667237f19637bf23424727f5cb

**Comment by elektrinis** [comment]
Thank you!
Will be waiting for installer :)

**Comment by emoacht** [comment]
Released.
