### ISSUE TITLE
One from 5 Displays won't be detected

### ISSUE THREAD

**Issue by LarsBoosNationalexpress** [emoacht/Monitorian#262]
I have a problem that i can control only 4 Displays. The fifth display won't be detected.
In Windows 10, nVidia Control Panel and Quadro Display Manager i can see fine my 5 Displays.
What could be the solution?

My Setup:
1x Xeon E3-1280 v6
2x nVidia Quadro P2200
16x GB DDR4 RAM
5x LG BK750Y Displays

**Comment by emoacht** [comment]
Are you subscribed to add-on features?
If not, the monitors shown at a time is up to 4. See [remarks](https://github.com/emoacht/Monitorian#remarks).

**Comment by LarsBoosNationalexpress** [comment]
Ok. How can i subscribe with the microsoft store version? I can't find a "buy" button.
And if i use the pc with several peoples do everyone need the license to use monitorian?

**Comment by emoacht** [comment]
You can purchase a subscription in Microsoft Store version. Open menu window and click `Add-on Feastures`. Then you will find `Proceed to purchase subscription`.
The subscription is on per Microsoft account basis.
