### ISSUE TITLE
Contrast control keeps disapearing

### ISSUE THREAD

**Issue by kuorka** [emoacht/Monitorian#263]
With "Enable changing contrast" ON, the Contrast control for an external monitor is not shown. If the situation occurs, it can't be brought back by unchecking and checking the "Enable changing contrast" menu option. Only the restart of the application helps.
Issue is regularly seen on a Windows 10 with one external monitor connected by DP. 
This happens usually after the laptop returns from overnight sleep.

**Comment by emoacht** [comment]
Thanks for the report.
Probably it happens because the monitor fails to report its capabilities after resume.
Could you post [Probe.log](https://github.com/emoacht/Monitorian#probe) at the following situations?
- When the contrast slider is shown normally.
- When the contrast slider disappeared after resume.
- When this app is restarted after the contrast slider disappeared.

**Comment by kuorka** [comment]
Posting probe.log for the following situations:1. Both internal and external monitors active (extended desktop)   a) contrast control missing   b) contrast shown after restart of the app2. Only external monitor active   a) contrast control missing   b) contrast shown after restart of the app
Just one more remark, I don't know if it is of importance here, I have two laptops connected to the same external monitor, alternating their use. These logs come from my new Dell which connects to the ext. monitor like this:   laptop ->(usb-c)-> docking station ->(usb-c)-> monitor
Before I got the Dell laptop, I had macbook pro connected the very same way and its Lunar app worked like a charm.

**Comment by emoacht** [comment]
In addition to probe.log, I am particulaly interested in operation.log which covers the whole sequence afther the resume and contrast slider disappears and then after the restart of this app, when contrast slider comes back.

Regarding the connection through the docking station, no one knows what might happen in such case. Any connection between devices might cause a trouble time to time.

**Comment by emoacht** [comment]
If no further development, I will close this issue.

**Comment by kuorka** [comment]
The laptop where it's happening is connected directly to monitor via DP cable. No dock in between.
Attaching the operation.log. It captured following situation:
- wake up system after a full night in sleep (contrast control missing)
- enabled operation.log
- quit and restart monitorian (contrast control available)
- saved operation.log
[operation.log](https://github.com/emoacht/Monitorian/files/7948662/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/7948663/probe.log)

**Comment by emoacht** [comment]
Thanks for the log.
But I need to check the log exactly when contrast bar disappeared.
Keep `Make operation log` checked and after you noticed this issue, save the log.

**Comment by kuorka** [comment]
sending the operation.log right after contrast bar disappeared
[operation.log](https://github.com/emoacht/Monitorian/files/7963187/operation.log)
.

**Comment by emoacht** [comment]
Thanks for the log.
Is is now clear that your monitor (Lenovo) fails to respond to a query for capabilities after resume.
Thus the contrast bar is disabled.
If you wish to circumvent this situation, you can utilize `/preclear` option for the time being. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584
