### ISSUE TITLE
Time-based and program based

### ISSUE THREAD

**Issue by Jack74r** [emoacht/Monitorian#273]
Hey
I just discovered your software, I also use f.flux, clickmonitorddc ,DimScreen . 
I was wondering if the functionality based on time exists or is planned in the development?
And maybe depending on some program (like fflux or clickmonitordds)

Thanks

**Comment by emoacht** [comment]
What do you mean by "the functionality based on time"?
Generally I believe that scheduling things will be better handled by Task Scheduler or other existing tools.
