### ISSUE TITLE
Brightness unison fails with multiple user accounts

### ISSUE THREAD

**Issue by tysonmatanich** [emoacht/Monitorian#280]
Repro steps:
1. Login into **account A**
2. Set brightness on display 1 and display 2 to 100%
3. Enable changing in unison for display 1 and display 2
4. Switch user to **account B** (don't completely sign out)
6. Enable changing in unison for display 1 and display 2
7. Set brightness to 50%
8. Switch user to **account A** (don't completely sign out)
9. Set display 1 brightness to 100%

Expected result:
Both display 1 and display 2 change to 100% in step 9

Actual:
Only display 1 brightness changes to 100%

From this point on the unison feature is broken for both user accounts. Disabling the reenabling unison on each monitor or the unison feature won't even fix it. If you restart the Monitorian app it resolves the issue for that user.

Other than this issue the app is awesome. Great work!

**Comment by emoacht** [comment]
Thanks for the report.
I found that it is caused by switching users and it appears only when switching is done without logoff. It is not related to running this app in both accounts.
I can fix it but in the first place, I don't recommend to run multiple instances at the same time.

**Comment by tysonmatanich** [comment]
Out of curiosity, what is the reason for issues with multiple instances?

**Comment by emoacht** [comment]
In short, I don't expect multiple instances running at the same time and consider whether this app's functions work properly in such situation. Running multiple instances on the same account is already prohibited for this reason. I have not seen any issue by multiple instances on the different accounts but it is just a unintended result.

**Comment by tysonmatanich** [comment]
Thanks! Seems like its working with the latest update. It did seem like it had a slight delay where it had to sync the new values after switching accounts.
