### ISSUE TITLE
Feature Request - Dim display(s) after period of inactivity

### ISSUE THREAD

**Issue by CreeT6** [emoacht/Monitorian#282]
This feature was always present on laptops to save battery life. I don't know if this is 1, possible on desktop, and 2, useful enough for people to spend hours writing the code for this feature. Anyways, if you think this is useful to you, reply below.

**Comment by JC-LGMS** [comment]
This feature is no more available on Windows 10 (laptop or desktop). I mean to set a timer for normal brightness then a timer for dim brightness then a timer for screen to turn off.
I will be happy to have it back please

**Comment by emoacht** [comment]
Thanks for the suggetion.
But I have no clue for this.

**Comment by emoacht** [comment]
In fact, you can use existing Task Scheduler for this purpose.
Set a trigger by idle time and make its action to call [command-line options](https://github.com/emoacht/Monitorian#command-line-options) of this app.

**Comment by emoacht** [comment]
I have thought about how this feature can be implemented.
Although it is possible to detect the inactivity of a user for a certain period of time, there is no practical way to detect when the user returns back except global hook which I generally avoid to use.
Therefore, I concluded this feature can not be implemented.
