### ISSUE TITLE
Fujitsu B24-8 TE Pro changing black level instead brightness

### ISSUE THREAD

**Issue by Sundro00** [emoacht/Monitorian#284]
Hello there, I love this app it works perfectly well with my Dell screen.

On my Fujitsu B24-8 TE it's actually changing the black level instead the screen brightness. I can see that if I move the slider on monitorian and look at the monitor settings, it shows that only the black level got changed.

Is there a way to fix this?

**Comment by emoacht** [comment]
Honestry I have no idea. I have never used Fujitsu monitor.
Although you can check DDC/CI compatibilities by proble.log, it might not be useful to identify the root cause.
