### ISSUE TITLE
Feature request: Support for brightness control keypresses

### ISSUE THREAD

**Issue by dennis97519** [emoacht/Monitorian#287]
On a desktop computer when using brightness control keys (programmed on a custom keyboard like [so]( https://community.keyboard.io/t/what-are-the-codes-for-the-brightness-control-keys/4094)), a slider for brightness adjustment (from windows) actually pops up, but doesn't do anything except changing the slider. Is it possible to attach the app to whatever mechanism is behind that?
<img width="60" alt="image" src="https://user-images.githubusercontent.com/4066022/151760553-1055be70-9112-4652-8ae2-a6082c956755.png">

**Comment by emoacht** [comment]
The answer is impossible.

**Comment by Artoria2e5** [comment]
It's not *technically* impossible, but the solution would involve pretending to be a display driver providing a brightness control interface. It will have to implement one of the DXGK_BRIGHTNESS_INTERFACE features [see this article about internals](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/supporting-brightness-controls-on-integrated-display-panels) and set a registry value to [enable brightness control for an external monitor](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/supporting-brightness-controls-for-external-display-connectors) at install.
