### ISSUE TITLE
Feature request - "animated" brightness control

### ISSUE THREAD

**Issue by Sighi-04** [emoacht/Monitorian#288]
Hi, I initially wanted to do this myself and submit a PR, and while I was able to "sneak it into the code" and see that it works, I'm still learning a lot and don't know my way around such a big codebase and couldn't find the right place to put it. Whenever I change my brightness, instead of it happening in a "big jump" I would like a progressive increase or decrease until it reaches the selected value.
I'm sure you already know this, but some quick if statements and for loops would do the trick.

**Comment by emoacht** [comment]
Thanks for the question.
I would like to clarify your intension. Do you mean that, let's say, when the user moves the brightness slider 10 to 50, change the actual brightness of monitor progressively to 10, 20, 30, 40, 50? If so, "animated" in the issue title could be misleading.

**Comment by Sighi-04** [comment]
Yes, progressively is what I meant. Sorry for my english, I'm from Italy.

**Comment by emoacht** [comment]
Okay, no problem.
Then, let me point out that, especially in the case of external monitor, there is a slight time lag after a command to set brightness is sent to a monitor. Also, in fact, the brightness level, the luminance level of backlight, changes continuously to the set level in short interval. In addition, most users want a monitor to follow the set brightness ASAP.
So I don't see much value to deliberately insert steps when changing the brightness.

**Comment by Sighi-04** [comment]
I get it, it's a really niche feature, no worries. Whenever I'll have some free time I'll try doing it, (and if I get it working as an optional thing maybe I'll submit a pr), but yeah it's not something I _need_ at the moment. Closing the issue, thanks for your reply and the great app.

**Comment by emoacht** [comment]
The point is how that feature can improve UX of the majority of users. You need to explain it.
