### ISSUE TITLE
Unison problem on Second Screen only 

### ISSUE THREAD

**Issue by abolog** [emoacht/Monitorian#289]
I have a laptop and an external monitor and two keyboards which have brightness keys on them.
Unison works perfectly adjust both screens. But most of the time I disable the laptop display, selecting "Show only on monitor 2", which breaks the brightness keys to update the external monitor in unison.
![image](https://user-images.githubusercontent.com/34079978/152864004-0c92dfd0-a4ae-494f-afc1-2c2829ace9c3.png)

**Comment by emoacht** [comment]
I understand that your keyboards have brightness keys which can change the brightness of internal monitor (display 1) but if the internal monitor is disabled, they will do nothing, this Unison function will do nothing.
It's quite normal.

**Comment by ejain** [comment]
On macOS, Lunar and MonitorControl let you adjust the brightness of an external monitor via the keyboard's brightness keys, even when the internal monitor is disabled. But this may not be possible on Windows?

**Comment by emoacht** [comment]
No. There are no generic brightness keys in Windows. Most notebook and some keyboard have brightness keys but thier function is hardware specific and as far as I know, their key input cannot be captured by a application.

**Comment by emoacht** [comment]
No. There are no generic brightness keys in Windows. Most notebooks and some keyboards have brightness keys but thier function is hardware specific and as far as I know, their key input cannot be captured by an application.
