### ISSUE TITLE
Monitorian disables display's eco mode

### ISSUE THREAD

**Issue by Johnnyt12** [emoacht/Monitorian#292]
I noticed that every change of brightness made by Monitorian results in display's eco mode being diabled. I use an LG IPS235 connected via HDMI. It has a so-called "super energy saving" mode that needs to be activated manually over and over again in the display's settings after using Monitorian brightness slider.

I would appreciate a fix for the brightness slider leaving this setting untouched, as it is probably impossible to access energy saving mode (or any other advanced display's feature) via Monitorian directly.

Let me know if further information is needed.

**Comment by emoacht** [comment]
Thanks for the report.
This app just sends comamnds to set the brightness via DDC/CI. If your monitor reacts each command as you dercribed, it cannot be helped.
