### ISSUE TITLE
Current Simplified Chinese Translation is really really bad!

### ISSUE THREAD

**Issue by FISHandCHEAP** [emoacht/Monitorian#297]
As a Chinese, I have to point it out because this small and powerful tool is so great, and I wish everyone who is suffering from silly Win10 design can have this tool!

Some of the translations are confusing and one option is translated to M? I don't know why but I don't think it's a bug.

Because I tried the newest version (v3.9) twice by downloading from Github and MS Store separately, and I meet the same problem.

Now I delete the Simplified Chinese Translation file so that I can understand the meaning of each option.

I can help to make a correct translation, and just let me know what can I do.

BTW, can we have an option to customize the logo? The original one is not my taste and I'd like to replace it with my own design (I don't mind to share it)

Best wishes to the developers and this tool!

**Comment by FISHandCHEAP** [comment]
BTW again, why not just give an option to allow users to change language?

**Comment by emoacht** [comment]
A PR to improve translation will be welcomed. See the past PR such as #294

You already know how to return to default. But there is `/lang` command-line option for testing purposes. In the case of English, you can specify `/lang en`

Then logo? thereis no such option.

**Comment by emoacht** [comment]
A PR to improve translation will be welcomed. See the past PR such as #294

You already know how to return to default. But there is `/lang` command-line option for testing purposes. In the case of English, you can specify `/lang en`

Then logo? there is no such option. Probably I will maintain it.

**Comment by FISHandCHEAP** [comment]
I just fixed translation errors with a PR, but it's my first time to use PR so not sure if I did it right.

Just to make sure, what does "Order by monitors arrangement" mean? I only have one monitor so I can't know.

Show current number means to show the number of the current monitor, right?

**Comment by emoacht** [comment]
>Just to make sure, what does "Order by monitors arrangement" mean? I only have one monitor so I can't know.

It reorders the monitors in this app depending on the placement of each monitor inside the entire desktop. A monitor at the left-top corner will be higher and a monitor at the right-bottom corner will be lower. Let's say, you have a tablet connected with two external monitors and three monitors are arranged as follows:

 - Monitor A (Tablet) : Lower
 - Monitor B (External monitor 1): Upper left
 - Monitor C (External monitor 2): Upper right

In this case, the order will be Monitor B -> Monitor C -> Monitor A.

> Show current number means to show the number of the current monitor, right?

It means whether to show the number representing the brightness of a monitor shown right next to each slider. You can easily check the result by turning on/off the setting.

**Comment by FISHandCHEAP** [comment]
For the first one, it sounds wired to me because I never had multiple monitors. So does that mean monitors know their physical arrangement? Or does it refer to the order that the system gives to monitors?

For the second one, I am 100% sure that the option did not work last time when I tested it, but it works now, so maybe there's a bug.

BTW, the PR that I pulled yesterday disappeared, and it is not updated to code. What's happened?

**Comment by emoacht** [comment]
> For the first one, it sounds wired to me because I never had multiple monitors. So does that mean monitors know their physical arrangement? Or does it refer to the order that the system gives to monitors?

No, it is not about physical arangement of monitors. As I wrote "the entire desktop", it is about how you place the screen of each monitor on the desktop. It can be managed in Display settings of the OS. Maybe this article [How to Rearrange Multiple Monitors on Windows 10](https://www.howtogeek.com/666239/how-to-rearrange-multiple-monitors-on-windows-10/) helps.

> For the second one, I am 100% sure that the option did not work last time when I tested it, but it works now, so maybe there's a bug.

It works perfectly on my environment. If you find how to reproduce it, please report it in another issue.

> he PR that I pulled yesterday disappeared, and it is not updated to code. What's happened?

I have not received a notification on the PR. Probably it has not been successfully sent yet.

**Comment by FISHandCHEAP** [comment]
OK, that explains clearly, then I think I have to PR again with some corrections

I found that some strings are not translated, such as Site and License, as well as Restore set brightness and Add-on feature in the MS Store version

**Comment by emoacht** [comment]
> I found that some strings are not translated, such as Site and License, as well as Restore set brightness and Add-on feature in the MS Store version

I usually don't answer to the point which I have explained in previous issues or comments. See 
https://github.com/emoacht/Monitorian/issues/255#issuecomment-968938806 and https://github.com/emoacht/Monitorian/pull/121#issuecomment-761982528
