### ISSUE TITLE
"Enable changing contrast" setting is not saved

### ISSUE THREAD

**Issue by lebucur** [emoacht/Monitorian#298]
Every time I disconnect/connect my monitors I have to click on each monitor's contrast button in order to be able to scroll over the contrast adjustment bar: it's really annoying.

**Comment by emoacht** [comment]
On/off state is not to be saved. It is so designed.

**Comment by lebucur** [comment]
Thanks for taking my feedback into consideration. /s
At least make a single button to toggle the contrast bar for all monitors, if I pay to control multiple monitors through this app.
