### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by LukeDMG** [emoacht/Monitorian#30]
Hello!

I've noticed that **dragging windows** became **much slower** since I've installed Monitorian on my Tablet. Checked out CPU usage in Process Explorer and it looks like the Desktop Window Manager eats more CPU when Monitorian is running.

I've measured **average CPU usage** of dwm.exe while moving a window (in this case the Windows 10 Calculator) around the desktop. Checked it both on my Tablet and PC - here are the results:

Device | Monitorian off | Monitorian on
-- | -- | --
Tablet | 24% | 30% (lagging a lot!)
PC | 17% | 20%

_Note: not all windows eat as much CPU while dragging, but even with simplier ones there is a very noticeable lag when running Monitorian on my Tablet. The PC runs smooth, but there is a CPU usage incerase._ 

Also, you should consider adding command line options or configurable keyboard shortcuts for brightness control on main/all monitors. Other thant that - great and very useful piece of software. Good job, sir!

**Comment by emoacht** [comment]
Thank you for reporting.
I have no idea on CPU usage while this app is not activated. Could you try Wifinian? It uses common component for handling the app's window.
Regarding command line options, could you describe the scenario of its usage in your mind? How to interact with this app from command line while it is continuously running?

**Comment by LukeDMG** [comment]
> Could you try Wifinian and see whether the same thing happens?

Yep, it's the same.

> Regarding command line options, could you describe the scenario of the usage in your mind? What is your idea on how to interact with this app through command line when it is running?

To be able to control the brightness via keyboard. Currently I'm using AutoHotkey script that does that by calling ScreenBright executable with certain arguments (it just sets brightness level and quits). And when the brightness goes to zero, I'm lowering screen gamma to dim it even more (because my monitor is too bright to look at without any ambient light, even at lowest brightnest setting).

But for a casual user the hotkey configuration should be sufficient enough : )

**Comment by emoacht** [comment]
I have no clue for this case. Without any additional information, I will close this issue.

**Comment by LukeDMG** [comment]
Sorry for the delay, didn't have time to check it out earlier.

Here are the results:

cpu usage* | Monitorian 
-|-
60 | off
88 | on
84 | minimized

cpu usage* | WpfPseudoAcrylic
-|-
60 | off
60 | on
60 | minimized
73 | on + blur
69 | minimized + blur

Looks like that blur effect is slowing things down, even while the app is minimized/in systray. 

It's not noticeable until the thread in dwm.exe (that is responsible for drawing things, I assume) reaches 100% core usage (yep, looks like there's only one thread for that), wich happens when CPU is in low power mode or on some low-end machines (like tablets/NUC's).

---
_*It's average of '% Processor Time' value logged by ms perfmon.exe for dwm.exe process. It's baseline is one core, not the whole cpu (so for 4 core cpu: 100% Processor Time means 25% overall usage)._

**Comment by emoacht** [comment]
Thank you very much!
This information is quite valuable. I am looking into it.
Searching around, I found some machines have high CPU usage by dwm.exe and I guess this issue is related to such dwm.exe's issue.
I have a couple of questions.

- Do you set transparency effects in personalization settings on?
- What is your hardware (especially graphic chips)?

**Comment by LukeDMG** [comment]
On my tablet, I've checked many different variations of Windows settings. Found out, that both transparency effects and mouse snap functions have reduced responsiveness a bit, but it was barely noticeable. With Monitorian running in background, and transparency + snap disabled, the lag (while moving windows around) was much worse. Even more so with those two options enabled.

On PC everything works great.. until I force the lowest multiplier on the CPU (it then runs at just under 1GHz), so CPU is the bottleneck here. Also on both systems GPU usage looks fine (on tablet it's around 50% with transparency enabled).

Tablet: 4x1.7GHz Atom + integrated Intel 8th gen GPU (WDDM 2.0)
PC: 3x3GHz Phenom II + GeForce 9600 GT (WDDM 1.2)

**Comment by LukeDMG** [comment]
Hello, quick update. I think I've found out why dwm.exe on some machines uses more CPU than on the others. I'm pretty sure (at least In my case) **it's because of the mouse**.

I had noticed that, while using touchpad (I don't use it too often) on my tablet's keyboard dock, I had almost no lag (with Monitorian running in background + transparency & snap enabled). Same thing with touch screen. Currently I'm using "gaming" mouse with high polling rate (500/1000Hz). I'm guessing that this causes dwm.exe to draw more frames of moving window in given period of time. I'll have to find my backup mouse and check it on my desktop as well.

I'll report back with the results, cheers!

**Comment by emoacht** [comment]
Thank you for additional information!
It's quite valuable and sounds interesting.
I am currently preparing an update to switch transparency & blur effects depending on the transparency effects settings of OS. It might not have a direct impact on high CPU usage case but could reduce CPU usage to some extent.

**Comment by LukeDMG** [comment]
That's a good idea. You could also use the user's accent color to paint the slider's handle. (And round up it's edges, add a window border, and align it to the right screen edge, to have more "native feeling". But I'm being picky now - UI/UX nerd here : )

About that performance issue, maybe the code captures image frame to perform that blurring effect even when the app is minimized? I've noticed that the blur is different than the acrylic stuff Windows uses. Is there a way to use the "native" one? If I'll find some spare time, maybe I'll learn C#/.net and check it out myself. I'd love to contribute (especially to the UI stuff).

**Comment by LukeDMG** [comment]
Just checked out new version. With transparency disabled, there is no performance drop.

Great job and keep up the good work!

**Comment by emoacht** [comment]
Thank you for checking the newer version.
I am not so enthusiastic about copying completely UI design of the current version of Windows because it has been changed abruptly time to time.
Regarding the blurring effects, it is somehow different from those of Windows itself because the same effects could not be achieved when this hack (it uses an undocumented API) became known to public and on the older version of Windows 10. On the current version of Windows 10, it can using updated hack. I am not sure it worth to follow it. You can see the example of updated hack in the following repository.
[sourcechord/FluentWPF](https://github.com/sourcechord/FluentWPF)
