### ISSUE TITLE
Control interface needs more text prompts

### ISSUE THREAD

**Issue by KargathEx** [emoacht/Monitorian#300]
![image](https://user-images.githubusercontent.com/40135358/159413945-7799c115-da81-4791-bf7c-b719b219ca39.png)

Hello, I did not find the specific description of the two control bars in the picture in the readme. Which of them is the brightness control and which is the contrast control?

**Comment by emoacht** [comment]
The left blue one is brightness and the right purple one is contrast.
Since the right one will only appear when a user clicks the right-top contrast button, I think the user can easily guess it is for changing contrast and can be confirm the guess by moving the slider.

**Comment by emoacht** [comment]
The left blue one is for brightness and the right purple one is for contrast.
Since the right one will only appear when a user clicks the right-top contrast button as tooltip says, I think the user can easily guess it is for contrast and can confirm the guess by moving the slider.
