### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by lipoiq** [emoacht/Monitorian#303]
Can you add a hotkey press to change brightness for the Logitech MX Keys keyboard? Why hotkeys is not available in 3.9.0.0?

**Comment by emoacht** [comment]
Key inputs by hardware brightness keys cannot be handled.
Hotkeys are included in add-on features of Microsoft Store version.

**Comment by lipoiq** [comment]
> Key inputs by hardware brightness keys cannot be handled. Hotkeys are included in add-on features of Microsoft Store version.

I installed it from Microsoft Store...

**Comment by csgaee** [comment]
> > Key inputs by hardware brightness keys cannot be handled. Hotkeys are included in add-on features of Microsoft Store version.
> 
> I installed it from Microsoft Store...

same issue -- where add-on not even know how to sub

**Comment by emoacht** [comment]
You can open the window for subscription information by clicking `Add-on Features` at the top part of menu window.
See the screenshot in [Add-on Features](https://github.com/emoacht/Monitorian#add-on-features) section.
