### ISSUE TITLE
Weird location of the panel

### ISSUE THREAD

**Issue by FISHandCHEAP** [emoacht/Monitorian#306]
Why not make the Monitorian panel shows at the corner of the screen? That's where other panels shows (volume, network)
![Snipaste_2022-04-05_09-39-46](https://user-images.githubusercontent.com/58490693/161714771-173ddcd9-cbb8-410e-9da8-35ffb650f131.png)

**Comment by emoacht** [comment]
It is for the shortest mouse movement from the notification icon.
