### ISSUE TITLE
"Show adjusted brightness" is not working

### ISSUE THREAD

**Issue by FISHandCHEAP** [emoacht/Monitorian#307]
If the function controls the display of "88" in the picture, then it is not working on my laptop because I made the screenshot when it's turned off.
![Snipaste_2022-04-05_09-44-34](https://user-images.githubusercontent.com/58490693/161715336-a62f0049-27d6-4291-bd8c-f73aa8b6de04.png)

**Comment by emoacht** [comment]
Thanks for reporting.
Could you elaborate it further? Did you check "Defer change until stopped"?

**Comment by FISHandCHEAP** [comment]
Basically, I can't turn off its display. Maybe temporarily turn off the display of that feature in the next version?

**Comment by emoacht** [comment]
Added __preclude__ option by c9ed609cf1bfcb7db0d8eb9d93b7b9b7277e0336 
The usage is the same as __preclear__ option while the effect is opposite. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

**Comment by emoacht** [comment]
Added __preclude__ option by c9ed609cf1bfcb7db0d8eb9d93b7b9b7277e0336 
This option is to exclude a specified monitor from this app. The usage is the same as __preclear__ option while the effect is opposite. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

**Comment by FISHandCHEAP** [comment]
Thx for the reply. But I don't know what you are saying because I am not a pro-user of Github, so could you please explain what's happening?

**Comment by emoacht** [comment]
I thought you requested to "turn off" handling of that monitor by this app. If it is not the case, don't mind.

**Comment by FISHandCHEAP** [comment]
Yep, I requested that, but I just don't understand what does this mean:

> Added preclude option by https://github.com/emoacht/Monitorian/commit/c9ed609cf1bfcb7db0d8eb9d93b7b9b7277e0336
This option is to exclude a specified monitor from this app. The usage is the same as preclear option while the effect is opposite. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

But that's ok, cause it is going to be solved.

**Comment by emoacht** [comment]
Could you elaborate your request in the first place?
Why you cannot turn off the display? What do you mean by "temporarily turn off the display of that feature"?

**Comment by FISHandCHEAP** [comment]
What am I saying is that

1) "Show adjusted brightness" is not working, so I request to fix it

2) According to your first reply, it seemed that the problem can't be easily fixed, so I suggest you turn off the display of that option temporarily if you can't fix it when releasing the next version

3) You replied to me about what you are going to do with that problem, and I said that I don't understand because I am a new Github user. But that is not something I am complaining about because obviously you are not ignoring that problem

**Comment by emoacht** [comment]
I see. Now it is clear.
I rejust your suggestion. If you found that feature does not work for your monitor, just don't use it.
