### ISSUE TITLE
"Enable changing contrast" is not working

### ISSUE THREAD

**Issue by FISHandCHEAP** [emoacht/Monitorian#308]
![Snipaste_2022-04-05_09-58-06](https://user-images.githubusercontent.com/58490693/161718185-d24e3dfd-f590-4a8e-a476-89bf409d4b23.png)

As you can see in the screenshot, where the bottom for contrast adjustment is blank.

**Comment by emoacht** [comment]
It is because there is no generic way to adjust the contrast of internal monitor. The OS does not offer this functionality.
