### ISSUE TITLE
Apple Pro Display XDR

### ISSUE THREAD

**Issue by zolomatok** [emoacht/Monitorian#309]
Not really an issue, but a question. I'm sorry, I don't know where else to ask.

Does Monitorian work with the XDR on a windows PC? (with a 30 series GeForce card if that makes a difference) (Not a mac that's running bootcamp)

Thank you!

**Comment by emoacht** [comment]
It depends on the mac and the display support DDC/CI and I have no idea on it.
I have confirmed this app works on intel MacBook and Dell monitor but I have never tested on Apple Silicon mac with Apple display.
