### ISSUE TITLE
Built-in laptop screen not detected on Windows 11 Insider Preview

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [emoacht/Monitorian#316]
I use a laptop with an external monitor connected.

In Windows 10, Monitorian detected both the laptop screen and the external monitor, and I was able to control the brightness of both.

I've just upgraded to Windows 11, and now, Monitorian only detects the external monitor. The laptop screen control is missing. I can still control the laptop screen brightness using Windows built-in controls, but not from monitorian.

Monitorian version: 3.10.1.0

**Comment by ZimM-LostPolygon** [comment]
If I unplug the external monitor, I get this:
![изображение](https://user-images.githubusercontent.com/928550/163042626-cc7bc7c5-072d-45ae-9523-7677f0e80fea.png)

Which can't be true, it's perfectly controllable using the standard Windows controls.

**Comment by ZimM-LostPolygon** [comment]
Apologies. Here they are:

[probe.log](https://github.com/emoacht/Monitorian/files/8479772/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/8479773/operation.log)

**Comment by emoacht** [comment]
Thanks for the logs.
probe.log clearly indicates that this app could not get the response from the OS to a query by WMI (WMI is a part of interface between the OS and apps.) I think it is quite rare and guess there might be something wrong in the OS.
This is what I can say at this moment.

**Comment by ZimM-LostPolygon** [comment]
Could it be something about how Monitorian is calling the WMI? I can query and change the laptop screen brightness just fine using WMI from Powershell:
![изображение](https://user-images.githubusercontent.com/928550/163155595-77fbe7e8-af8f-4138-bcd5-e34a1189caaa.png)

**Comment by emoacht** [comment]
Okay, it seems to depend on the functions of WMI.
Could you reproduce the method below by PowerShell and check whant happnes? https://github.com/emoacht/Monitorian/blob/093ca58cf90c7207a34da083d9e00cb6eb05508a/Source/Monitorian.Core/Models/Monitor/MSMonitor.cs#L66-L97

**Comment by ZimM-LostPolygon** [comment]
OK so, I've just forked the `master` branch, launched it, and... both screens are present and controllable!
![изображение](https://user-images.githubusercontent.com/928550/163205499-ece1e11a-9e96-40a1-adbd-62a81947736b.png)
Not sure what to think of this. Of note is that I've installed Monitorian from Microsoft Store... Could Windows be applying some weird compatibility mode? I'll check if anything changes with a standalone install.

**Comment by ZimM-LostPolygon** [comment]
And indeed, when querying from Powershell without admin privileges, I get an access denied error.
![изображение](https://user-images.githubusercontent.com/928550/163209777-c73cd7a7-9a4a-4cc1-857c-1e1d6c6847ce.png)

**Comment by emoacht** [comment]
So there might be something related to security policy or security settings.

**Comment by ZimM-LostPolygon** [comment]
Nothing has changed, it was a regular upgrade from Windows 10 to Windows 11. If there is something, then shouldn't it be for all Windows 11 installations?

**Comment by emoacht** [comment]
I personally have never heard similar issue at least after public release of Windows 11.

**Comment by jjavierdguezas** [comment]
the same thing has been happening to me for a few days

```
OS Info:
==========
Edition	Windows 11 Pro
Version	22H2
OS build	22598.100
Experience	Windows Feature Experience Pack 1000.22598.100.0

Monitorian Info:
====================
Version 3.10.1.0
Instaled via Microsoft Store
```

It detects external monitor but not the internal one. I am sure it was working before, with windows 11

If I unplug the external monitor, I get this:

![image](https://user-images.githubusercontent.com/13673443/165478390-9ba2ea15-64fd-4885-8490-013f11703f5e.png)

[probe.log](https://github.com/emoacht/Monitorian/files/8570397/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/8570396/operation.log)

**Comment by emoacht** [comment]
@jjavierdguezas Thanks for the logs.
This is an issue of the OS. On Insider Preview, anything can happen.

**Comment by schroef** [comment]
I have the same issue since i update to Windows r22610 today. Must say havent used it in couple weeks. But today noticed only build in monitor responded. It used to trigger the app. When i quit Monitorian it only shows my second monitor, not showing the main display of the laptop.

Just noticed my version was still at 3.6.5. Ill update and see if it works. Weird thing was , when i checked microsoft store and searched. Ity showed install, while the app was already installed. I never seem to get a update notification

**Comment by ZimM-LostPolygon** [comment]
Windows 11 r22616.1 seems to fix it, I can control both monitors again.

**Comment by emoacht** [comment]
@ZimM-LostPolygon It's good to hear.

**Comment by jjavierdguezas** [comment]
yes, it is working now
