### ISSUE TITLE
Monitorian occasionally stops working after monitor goes to sleep

### ISSUE THREAD

**Issue by DasIstWalter** [emoacht/Monitorian#318]
Occasionally, after the monitor goes to sleep automatically, monitorian will stop working and display the message "DDC/CI not supported" after waking it up. Closing and restarting the app fixes the problem.
[exception.log](https://github.com/emoacht/Monitorian/files/8558369/exception.log)

**Comment by emoacht** [comment]
Thanks for reporting.
The exception.log seems to be recorded when you close this app. Is it right? If it is the case, it does not help much.
Could you post exception.log which includes the transition from the normal state to the problematic state?

**Comment by DasIstWalter** [comment]
That log popped up when I clicked on the monitorian tray icon after I came back to my pc. The monitor was asleep for several hours and that's usually what causes the "DDC/CI not supported" issue.

**Comment by emoacht** [comment]
I see. The exception.log indicates that your system was going shutdown during being suspended.
I could not quite get the situation.

**Comment by DasIstWalter** [comment]
Today the "DDC/CI not supported" message appeared after a reboot. Steps I took were:
1. create probe.log;
2. rescan monitors(which fixed the brightness control);
3. create operation.log;
[probe.log](https://github.com/emoacht/Monitorian/files/8574920/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/8574921/operation.log)

**Comment by emoacht** [comment]
@DasIstWalter Thanks for the logs.
It is clear that your monitor occasionally turns to be unresponsive. If you wish, you can use `/preclear` option. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

Still I could not get the relationship between this unresponsiveness and system shutdown.

**Comment by DasIstWalter** [comment]
Preclear option seems to work, no problems after several reboots. Thanks!
