### ISSUE TITLE
Ability to force change?

### ISSUE THREAD

**Issue by s-seidel** [emoacht/Monitorian#325]
Hi, I use an HP laptop with an HP Dock and two external monitors on the dock. Monitorian doesn't allow me to change the brightness of the monitors saying "Monitor is not controllable". However, when I click "Probe into monitors", the brightness is changed. I can see that it attempts to set the brightness and reports "failed", but the actual monitor brightness is changed.
So if you could add a "force" mode where the brightness can just be set but setting failures are ignored, that would be great.[](url)

**Comment by s-seidel** [comment]
[probe.log](https://github.com/emoacht/Monitorian/files/8706088/probe.log)

**Comment by emoacht** [comment]
Thanks for reporting.
The log says that getting and setting the brightness of your monitor were not successful. 

```
"GetBrightness": "Success: False",
"SetBrightness": "Success: True, Match: False (Expected: 9, Actual: 0)"
```

It is impossible to make this app work without knowing at least the current brightness.

**Comment by s-seidel** [comment]
Yes, it says it's not successful, but the monitor brightness was changed anyway. Hence I was wondering if Monitorian could be instructed to ignore the failure and still set the brightness.

**Comment by emoacht** [comment]
As I explained, the inability to get the brighness is critical rather than that to set the brightness.
