### ISSUE TITLE
add saturation, color adjustment 

### ISSUE THREAD

**Issue by ChrisAlex22** [emoacht/Monitorian#330]
Hi Emoacht,

Is it possible to add Saturation, color,construst, audio adjustment function in your code? Or which portion can I encode to make the function come ture？ Could you help give me suggestion?

Thanks in advance !

**Comment by emoacht** [comment]
Thanks for the suggestion.
But I have no intenstion to recklessly expand the elements to be managed by this app.
So your suggestion is declined.
