### ISSUE TITLE
Not all (identical) screens detected

### ISSUE THREAD

**Issue by seteq** [emoacht/Monitorian#334]
Hi,

I have a somehow strange issue on one computer. 
There are three identical displays (Asus PB277) connected via DisplayPort cables to a Quadro 4000 GPU (Driver v516.25) on Windows 11 (all updates installed).

Monitorian (using 3.11.3.0) sometimes detects one screen, sometimes two screens but almost never all three of them.
Is there any way to debug the detection of screens in Monitorian?

Thanks

**Comment by emoacht** [comment]
Could you read [reporting](https://github.com/emoacht/Monitorian#reporting)?

**Comment by seteq** [comment]
Sorry, I missed this section about reporting, I did the logs now:

[operation.log](https://github.com/emoacht/Monitorian/files/8900643/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/8900644/probe.log)

I also noticed when I try to rescan the monitors several times, somehow all three screens appear and can be controlled properly.

Thanks.

**Comment by emoacht** [comment]
Thanks for the logs.
probe.log shows that all three monitors are capable of DDC.CI. However, operation.log indicates that the responses from these monitors are unstable and change its capabilities time to time.
I have no idea but something related to hardware (including connector, cable) or driver could cause this issue.
