### ISSUE TITLE
4 Screens but only 2 screens detected by Monitorian

### ISSUE THREAD

**Issue by VanVan** [emoacht/Monitorian#336]
Hello,

I have 4 screens, connected in DVI and HDMI.
It detects one of the screens in DVI and one of the screens in HDMI. All these screens are connected to a single graphics card on Windows 11.

Here are the two log files attached.

Thanks to you
NB: It misses an option of unlimited purchase without subscription :)

[operation.log](https://github.com/emoacht/Monitorian/files/8912679/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/8912681/probe.log)

**Comment by emoacht** [comment]
Thanks for the logs.
Both logs indicate two DVI monitors are not capable for DDC/CI. This is why the two are not shown in this app.

**Comment by VanVan** [comment]
For your information, ignoring the 3rd one, two of the monitors connected to DVI are strictly identical, but only one of them is detected

**Comment by emoacht** [comment]
All three DVI monitors seem to have diffrent screen sizes..
Anyway, if two out of three monitors are identical model, the difference could come from connertors or cabels.

**Comment by VanVan** [comment]
The difference in size is related to the fact that they are not in the same resolution (1920*1080 vs 2560 x 1440), but it is indeed twice the same monitor.
The change of resolution does not have any impact on the support of the monitors by your program.
I'll try switching the cables soon to see if this is the cause of the problem.

**Comment by emoacht** [comment]
I just noticed the physical sizes of all DVI monitors are different (74, 21, 27). Not set resolutions.
Anyway, they don't matter.
