### ISSUE TITLE
Feature request: reduce brightness after timeout

### ISSUE THREAD

**Issue by Polyterative** [emoacht/Monitorian#337]
I would love to have a similar behavior as in phones.
Reduce brightness after a minute and reset it back up after I move the mouse or click or write on keyboard.
Would lower power consumption as well

**Comment by emoacht** [comment]
Thanks for your suggestion.
It is difficult to reset low brightness state by capturing mouse move or key stroke because it will require to hook all mouse moves and key strokes on the system but I decided to avoid it.

Alternatively, what I could think of is adding a hot key to manually turn on or off low brightness state.

**Comment by Polyterative** [comment]
> Thanks for your suggestion. It is difficult to reset low brightness state by capturing mouse move or key stroke because it will require to hook all mouse moves and key strokes on the system but I decided to avoid it.
> 
> Alternatively, what I could think of is adding a hot key to manually turn on or off low brightness state.

Maybe windows exposes some API for inactivity state? Kinda like Microsoft Teams. IDK just throwing ideas.
A keyboard shortcut would be better than nothing, though.

**Comment by emoacht** [comment]
As far as I know, no.

**Comment by emoacht** [comment]
I forgot to say but this app has a hot key to turn off display. It would be better for power saving rather than just making brightness lower.

**Comment by emoacht** [comment]
I decided not to implement this suggestion because the OS's built-in function to turn off display after time is better in terms of power saving and existing hot key of this app enables user to turn off display anytime. So, there would be no added value.
