### ISSUE TITLE
Doesn't allow controlling my monitor, but GetBrightness+SetBrightness works in log

### ISSUE THREAD

**Issue by Terrobility** [emoacht/Monitorian#338]
My monitor is a MSI G273QF connected over DisplayPort. I checked the probe log and this is what it says:

```json
"Description": "MSI Optix G273QF",
"MonitorIndex": 0,
"Capability": {
  "IsHighLevelBrightnessSupported": false,
  "IsLowLevelBrightnessSupported": false,
  "IsContrastSupported": false,
  "IsPrecleared": false,
  "CapabilitiesString": null,
  "CapabilitiesReport": null,
  "CapabilitiesData": null
},
  "GetBrightness": "Success: True, Valid: True (Minimum: 0, Current: 35, Maximum: 100)",
  "SetBrightness": "Success: True, Match: True (Expected: 40, Actual: 40)"
```

So clearly the GetBrightness and SetBrightness is working. But because the capability is reporting as False, the app isn't allowing brightness control. Or at least that's my guess. 

I tested with another DDC app and the brightness CAN be controlled (as well as contrast, color temp, etc.). So this is definitely a Monitorian issue.

Full logs:
[probe.log](https://github.com/emoacht/Monitorian/files/8993333/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/8993334/operation.log)

**Comment by emoacht** [comment]
Yes, it may or may not be surrounded by quotation marks when it is given by command-line.

**Comment by Terrobility** [comment]
I'm not sure about command line but in the Monitorian hidden menu, it doesn't work when surrounded by ""

**Comment by emoacht** [comment]
No, it does not.
