### ISSUE TITLE
[Windows 8.1] Crash on enabling accent colors

### ISSUE THREAD

**Issue by SigmaTel71** [emoacht/Monitorian#345]
Monitorian 3.12.0, Windows 8.1 x64.
[exception.log](https://github.com/emoacht/Monitorian/files/9203819/exception.log)

**Comment by emoacht** [comment]
Thanks for reporting.
This function only works on Windows 10. I forgot it.
I will disable it on Windows 8.1.

**Comment by SigmaTel71** [comment]
Is it impossible to get Metro UI color from Windows 8.1 settings to reuse it at desktop mode?
![image](https://user-images.githubusercontent.com/17989678/181491195-d0073fcf-742f-42bc-b15e-e5699b6c3641.png)

**Comment by emoacht** [comment]
On Windows 10, the accent color is actually a set of colors with different shades. So they can be utilized as Static color and MouseOver/Pressed color.
In contast, while we can get accent color, I don't know how to get shaded variants of that color or even whether such colors exist. It is the reason why Window 8.1's accent color cannot be used as it is.

**Comment by emoacht** [comment]
Finished by 24652b423a30b28cc0ea31f955f48b596ef21f6f 0d57f4f0b67b228c9cebc05b8f118eb787942bdc
