### ISSUE TITLE
Show Windows display number and/or set custom name for display

### ISSUE THREAD

**Issue by peskdale** [emoacht/Monitorian#351]
When using multiple monitors of the same model, they show up with identical names in Monitorian - with no way to discern between them except by moving each slider.

It would be great to have a better way of identifying them in the list.

I could see this being done in one of two ways...
- showing the Windows display number next to each name (and possibly sorting in this order too)
- having the ability to set a custom name for each display (which could then be stored alongside other persistent settings for future reconnections)

**Comment by emoacht** [comment]
Thanks for your suggestion.
You can customize the name for each monitor. See the first paragraph in [Remarks](https://github.com/emoacht/Monitorian#remarks).

**Comment by peskdale** [comment]
Apologies - I somehow missed that. Thanks.
