### ISSUE TITLE
having range in contrast and on hotkeys / CLI setter

### ISSUE THREAD

**Issue by fluoroom** [emoacht/Monitorian#354]
seems like my monitor understands wrong ddc/ci messages and contrast actually dimms the image, this would be cool

**Comment by emoacht** [comment]
I don't quite understand what you mean by title and explanation. Could you elaborate it?

**Comment by fluoroom** [comment]
The actual contrast control has not a "range" option to set max and min, only brightness has. It also isn't capable to assing hotkeys to contrast control or to set contrast by CLI as actual syntax is "/set [Brightness]", no contrast available.

**Comment by emoacht** [comment]
Thanks for the explanation.
The contrast bar is added purely for supplement the control of brightness. I have no plan to bolster the control of contrast itself.
