### ISSUE TITLE
Bug - Dual Monitor Setup But Only 1 Adjuster

### ISSUE THREAD

**Issue by kutaycinar** [emoacht/Monitorian#356]
Switched to using dual GM27-FQ ARGB monitors but only one is detected and the adjuster works.

![image](https://user-images.githubusercontent.com/76612427/192881138-3fc1aedd-2929-4ca0-9676-8793baa6b590.png)

They are both connected via DisplayPort directly to an RTX 2080.

![image](https://user-images.githubusercontent.com/76612427/192881337-2d3d32e0-616a-4383-ac90-bf012eaac332.png)

[probe.log](https://github.com/emoacht/Monitorian/files/9669094/probe.log)

**Comment by kutaycinar** [comment]
Restarting the app seems to sometimes switch which monitor's brightness is affected where the slider starts to control the other monitor's brightness.

Other times the app fails to detect both monitors as controllable.

![image](https://user-images.githubusercontent.com/76612427/192880717-b02d284c-3dbc-4e30-bb6a-6262012daf62.png)

This error persists even though both monitors have DDC/CI are enabled.

However, resetting the NVDIA graphics driver with CTRL+WIN+SHIFT+B seems to resolve this error message but then still only one monitor is controllable at a time and the original bug persists.

**Comment by kutaycinar** [comment]
Power cycling the monitors seem to have fixed my issue.

![image](https://user-images.githubusercontent.com/76612427/192897085-68b095de-4df4-4f57-b6da-511ed0b47cc3.png)

**Comment by emoacht** [comment]
Thanks for reporting.
According to the log, these monitors fail to report their capabilities via DDC/CI.
In such case, you can use `/preclear` option. See https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584
