### ISSUE TITLE
Samsung Smart TV

### ISSUE THREAD

**Issue by timikesmarky** [emoacht/Monitorian#36]
Doesn't work on Smart TV. I'm looking for an app that controls Samsung TV brightness. Do you know of any?

**Comment by emoacht** [comment]
Is the Samsung monitor is compatible with DDC/CI? If not, probably no app can do it. If you provide prob.log described in readme, I can tell what is happening.

**Comment by timikesmarky** [comment]
Here is the log:
[probe.log](https://github.com/emoacht/Monitorian/files/2870584/probe.log)

**Comment by emoacht** [comment]
Thank you for posting the log.
It indicates the monitor is not capable of DDC/CI or it is not enabled. Just out of curiosity, what model is it?

**Comment by timikesmarky** [comment]
It is UA40D6600 3D LED TV.

**Comment by emoacht** [comment]
I see. I could not find any information on DDC/CI functionality in its specification. Probably it does not support DDC/CI.

**Comment by timikesmarky** [comment]
Yes, only apps that use gamma ramp API work with this. There are only two apps I know that use the API.
