### ISSUE TITLE
Monitorian close itself automatically every time I unplug an external monitor from my laptop

### ISSUE THREAD

**Issue by oeloo** [emoacht/Monitorian#361]
Hi, I am using Monitorian (latest version) on Windows 11. It works great, but when I unplug my dell laptop on Windows 11 (with latest update) from my Dell station (fully uptodate), Monitorian is closing automatically.
Regards

**Comment by emoacht** [comment]
Thanks for reporting.
But there is nothing I can do from limited information. If this app suddenly stops, there should be a chance to leave an exception.log.
