### ISSUE TITLE
Eizo FS2434 is not adjustable with with Monitorian in Windows 10

### ISSUE THREAD

**Issue by pohuing** [emoacht/Monitorian#362]
I've always assumed the monitor was just incapable of this, ControlMyMonitor also shows that the screen does not work.

However [MonitorControl](https://github.com/MonitorControl/MonitorControl) on the same hardware booting MacOS as a hackintosh system is able to control the monitor perfectly fine.
![grafik](https://user-images.githubusercontent.com/24683548/196291298-afbe2948-84e8-4009-a53f-8ca0cd867c1e.png)

I have tried preclude and preclear flags with the instance id both with escaped backslashes as well and quotation combinations but that did not change anything unfortunately: `/preclude "DISPLAY\ENC2634\7&18E99910&2&UID256"`

Could driver issues maybe prevent the control? 

[probe.log](https://github.com/emoacht/Monitorian/files/9804733/probe.log)

**Comment by emoacht** [comment]
Thanks for reporting.
The proble.log shows that the Eizo monitor does not respond to DDC/CI at all. In such case, `/preclear` will not help. FYI, `/preclude` is to exclude a monitor from this app's control and so pointless for this case.

I have checked FS2434"s manual but found no indication on DDC/CI. So usually this monitor is regardes as incompatible with DDC/CI. I have no idea on what happens on MonitorControl. Chaninging the driver of graphic card may or may not change it.

**Comment by pohuing** [comment]
Oh pretty absurd that MonitorControl achieves what shouldn't even work according to spec. Are there perhaps alternative APIs for controlling the screen?

**Comment by emoacht** [comment]
As far as I know, there is no other industry standard for communicating with externak monitors.

**Comment by pohuing** [comment]
Hmm I'll have to dig into how MonitorControl does it and see if I can port that to windows. Thanks for answering the questions

**Comment by pohuing** [comment]
Just as a resolution, it took a while to get back to this but i've figured out how MonitorControl does it. [They're using software dimming by creating a darkened overlay for the entire screen.](https://github.com/MonitorControl/MonitorControl/blob/b39e30726cc5082d58e027d55f8823329729c309/MonitorControl/Support/DisplayManager.swift#L66)
I don't have a clue if such a solution would be portable to Windows, it might be but that's probably beyond the scope of this project.

**Comment by emoacht** [comment]
Thanks for the information.
And no, such trick is not what this app is intended for.
