### ISSUE TITLE
Won't start on login after 22h2 update

### ISSUE THREAD

**Issue by SnowDrifterr** [emoacht/Monitorian#363]
Ticking the 'start on login' setting doesn't seem to save the setting. Clicking off the window, then reopening it still shows as un-ticked

**Comment by emoacht** [comment]
Thanks for reporting.
Could you specify which version of this app?

**Comment by SnowDrifterr** [comment]
3.13.0.0

**Comment by emoacht** [comment]
Thanks. But I mean ordinary or Microsoft Store version.

**Comment by SnowDrifterr** [comment]
Apologies

Microsoft store version

**Comment by emoacht** [comment]
Thanks. On my Windowd 11 22H2 (22623.870), it does not reproduce. `Start on sign in` works fine.
