### ISSUE TITLE
Monitorian has unexpected problem occurred after reboot pc.

### ISSUE THREAD

**Issue by Ivanoks** [emoacht/Monitorian#366]
So. I use Monitorian 1 day, and after reboot, i get this. 

![image](https://user-images.githubusercontent.com/88715280/198813807-5fd18be0-4c2f-4602-b448-22d37418bf99.png)

They show up twice. So idk. I checked the windows store and msi too, same issuse.
There log:
[exception.log](https://github.com/emoacht/Monitorian/files/9892998/exception.log)

**Comment by emoacht** [comment]
Thanks for reporting.
What is the OS version?

**Comment by Ivanoks** [comment]
> Thanks for reporting. What is the OS version?
 
Windows 10 pro. 22H2.
![image](https://user-images.githubusercontent.com/88715280/198814051-ec4f1f54-981e-4f6f-8e9d-bb289bd6f849.png)

**Comment by emoacht** [comment]
Is this app Microsoft Store version or ordinary one?

**Comment by Ivanoks** [comment]
> Is this app Microsoft Store version or ordinary one?

That's from MSI. But, on Microsoft too.

**Comment by Ivanoks** [comment]
Maybe, that's problem on my side? Maybe i can to do something on my pc?

**Comment by Ivanoks** [comment]
AYO, i fix it by `sfc /scannow`. Lmao.

![image](https://user-images.githubusercontent.com/88715280/198831671-5d99a232-8489-4248-b7cf-b03aca75ec7a.png)


![image](https://user-images.githubusercontent.com/88715280/198831662-ee54c852-5107-48a5-9978-cb0c8e4c4913.png)

Sorry for this, but, i guess, maybe, it will come in handy someday.

**Comment by emoacht** [comment]
Thanks for the information.
It's an issue of the platform and so should be left to the platform.
