### ISSUE TITLE
Inzone M9 cannot be controlled

### ISSUE THREAD

**Issue by kanongil** [emoacht/Monitorian#367]
Monitorian claims that "DDC/CI is not supported or enabled".

However, I have enabled DDC/CI in the monitor menu, and I can confirm that the bundled software can be used to change the brightness. It is connected directly from an NVIDIA GPU using DP.

[probe.log](https://github.com/emoacht/Monitorian/files/9895771/probe.log)

**Comment by emoacht** [comment]
Thanks for reporting.
The monitor seems not return capabilities information. In such case, use `/preclear` option.

**Comment by kanongil** [comment]
Thanks, it works now. I think part of the problem is that the monitor cannot change brightness when in HDR mode.
