### ISSUE TITLE
Action Center

### ISSUE THREAD

**Issue by alaurene** [emoacht/Monitorian#37]
Just installed this app on an Intel NUC8i7HNK with an ASUS MX25AQ monitor.  This NUC is identified as a "desktop" computer by Windows as it uses a desktop chipset and processor.  Windows does not install its brightness slider (Settings > System > Display) nor its Action Center brightness control on "desktop" computers - these are only installed, by design, on laptop computers.  Thus, the monitor control buttons or the graphics control panel are the only methods for changing screen brightness.  Neither are as simple to access as the Windows brightness controls - nor as easy to access as Monitorian.  Brightness is now easily accessible and works perfectly - Thank you for a very useful app!

I would like to request that an option be added to provide an Action Center button rather than the taskbar location - similar to the native Windows brightness button.  This configuration option would provide for desktop computers essentially what is available for laptops.

Thanks again!

**Comment by emoacht** [comment]
Thank you for your feedback.
As far as I know, there is no hack available to a third party app which enables the app to add its UI parts inside Action Center, except toast notification.

**Comment by alaurene** [comment]
Thank you for replying.  Your program is very useful and well appreciated.


________________________________
