### ISSUE TITLE
Showing percentage number of brightness instead of tray icon.

### ISSUE THREAD

**Issue by emoacht** [emoacht/Monitorian#370]
### Discussed in https://github.com/emoacht/Monitorian/discussions/365

<div type='discussions-op-text'>

<sup>Originally posted by **Oppa-YA** October 23, 2022</sup>
Hello. Please add possibility to show the brightness percentage number instead of the tray icon. This is the most important feature that should be in this software. People could just look at the icon and see the brightness level. Thank you.

Here is the example picture of how it's done in the software Click Monitor DDC, just showing the number for brightness:
![1](https://user-images.githubusercontent.com/11776599/197381488-87086653-5a12-4d76-bffb-fc05fa468dd6.jpg)
</div>

**Comment by emoacht** [comment]
Thanks for the suggestion.
In my view, such feature is not useful in the case of this app. If the information to be shown in taskbar were the kind of information which cannot be easily accessible, it could be useful. In contrast, you can see the brightness of each monitor with your eye balls directly and super quickely.
Thus this suggestion is rejected.

**Comment by Oppa-YA** [comment]
LOL. Well, ok, it's up to you.
