### ISSUE TITLE
Implementing controls for other aspects for eg DYAC+ and Black EQ settings.

### ISSUE THREAD

**Issue by atharva1051** [emoacht/Monitorian#373]

**Comment by atharva1051** [comment]
Really love this project and would love to contribute unfortunately I'm not at all experienced>
I use this monitor XL2546K for 2 years and every time I had to change all these settings physically, this addition would be game changing!

**Comment by emoacht** [comment]
Thanks for the suggestion.
But DyAc+ and Black eQualizer seem to be special and proprietary features of BenQ. This app communicates with a monitor by DDC/CI and so special features other than those of standard DDC/CI are out of scope in the first place.

**Comment by atharva1051** [comment]
Oh Alright makes sense! Thanks for making me understand!
Keep up the good work 💯

**Comment by FelixKainz** [comment]
Let me propose a workaround.
Does your screen support profiles? Can you create a profile that has backlight strobing enabled and one that does not?
Then you can use another similar tool to Monitorian called [ddccontrol](https://github.com/ddccontrol/ddccontrol) to switch between these profiles. This way you can enable or disable strobing through the OS.

**Comment by atharva1051** [comment]
Oh I’ll definitely give that a try!
There is a thing called S Switch but its annoying to keep that plugged in. I’ll give it a try and get back.

**Comment by emoacht** [comment]
Out of curiosity, could you post probe.log of that monitor? I am interested in whether BenQ extended DDC/CI standard for its propriatory features.

**Comment by atharva1051** [comment]
How do you do that?

**Comment by emoacht** [comment]
You can get probe.log from this app. Read [Probe](https://github.com/emoacht/Monitorian#probe).

**Comment by emoacht** [comment]
I posted related issue in #399
