### ISSUE TITLE
Monitorian causing windows lags

### ISSUE THREAD

**Issue by samuelAN-GH** [emoacht/Monitorian#374]
Hi,

Monitorian 3.14 seems to cause periodic windows lags (mainly seen on the mouse behaviour lagging).

These lags appears systematically at windows logon, and after they appear randomly, during ~10 secs.

No lag when Monitorian is closed.

**Comment by emoacht** [comment]
In general, if each scan causes suc lag, there is not much I can do. This depends on your PC and perhaps the monitor.
