### ISSUE TITLE
A part of number is hidden

### ISSUE THREAD

**Issue by u-Sir** [emoacht/Monitorian#375]
`100` incomplete 😁
![图片](https://user-images.githubusercontent.com/93647031/204149612-7430b7f1-8a4d-4952-b9ea-6fed627b0a26.png)

**Comment by emoacht** [comment]
Thanks for reporting.
What percentage is your monitor's DPI?

**Comment by u-Sir** [comment]
> Thanks for reporting. What percentage is your monitor's DPI?

250%, 3840*2160

**Comment by emoacht** [comment]
Thanks.
 but it does not reproduce on Surface Pro 8, Windows 11 22623.875 with 4K monitor and 250% in DPI.
Strange ...
![250%-4k](https://user-images.githubusercontent.com/7205690/204395174-781f1595-2a21-40b7-9f2b-27c9ee72741f.png)

**Comment by emoacht** [comment]
The font size on your PC (upper) is bigger than mine (lower). Have you set any settings on your desktop which may affect the font size?
![font-comparison](https://user-images.githubusercontent.com/7205690/204699233-dd1e48fb-6454-4b5f-a2e1-49405dbe9ea0.png)

**Comment by u-Sir** [comment]
> The font size on your PC (upper) is bigger than mine (lower). Have you set any settings on your desktop which may affect the font size? ![font-comparison](https://user-images.githubusercontent.com/7205690/204699233-dd1e48fb-6454-4b5f-a2e1-49405dbe9ea0.png)

no. my sysinfo
![图片](https://user-images.githubusercontent.com/93647031/205424994-f8e7453c-d38b-4238-97d9-d67b3ed1a3f8.png)

**Comment by emoacht** [comment]
How about `Accessibility` > `Text size`?
And what is your language settings?

**Comment by u-Sir** [comment]
> How about `Accessibility` > `Text size`? And what is your language settings?
Chinese Simplified, zh-cn
text size:
![图片](https://user-images.githubusercontent.com/93647031/205430313-572f5585-af9a-42a5-b7f7-55eea817f15f.png)

**Comment by emoacht** [comment]
Thanks. I got it.
It is because Chinese default font size is bigger than others. I will fix the font family for the text.

**Comment by emoacht** [comment]
Fixed 0cadd566a2b576ef9ecd0542d2d1e30792831d16
