### ISSUE TITLE
After the app update the taskbar icon visibility is always reset

### ISSUE THREAD

**Issue by vbrozik** [emoacht/Monitorian#379]
I want to have the taskbar icon of Monitorian always visible for quick check and setting of brightness and contrast.

Unfortunately after Monitorian is updated by MS Store:
* the icon is reset to hide
* the app is not restarted (I have to start it manually again)

**Comment by emoacht** [comment]
Thanks for the suggestion.
But unfortunately, it is not controllable from an app.
