### ISSUE TITLE
Hot keys to control contrast

### ISSUE THREAD

**Issue by GuruOz** [emoacht/Monitorian#381]
Currently we can use hot keys to control the brightness. Could we get another key binding to control the contrast?

Or better yet, can we get a key binding that controls both brightness and contrast at the same time?

**Comment by GuruOz** [comment]
More than happy to contribute to this project. this program is one of the most important tool that i use day to day.

**Comment by emoacht** [comment]
Thanks for the suggestion.
Could you elaborate what kind of behavior by hot keys for contrast?
Regarding the combination of brigtness and contrast at the same time, I have no idea about whether such behavior could be useful in practice. In my view, they are somehow interlinked but need to be carefuly adjusted independently.
