### ISSUE TITLE
SUGGESTION : ADJUSTMENT BY MOUSE WHEEL ON TRAYICON

### ISSUE THREAD

**Issue by havewisdom** [emoacht/Monitorian#382]
There's a function I want to request
I don't know where to leave it, so leave it here.

First of all, thank you for allowing me to use a good app.

In Windows 11, you can adjust the volume only with the mouse wheel without clicking the cursor on the system tray volume icon
I think it would be good to adjust the MONITORIAN system icon in this way!

**Comment by emoacht** [comment]
This issues has been discussed in #174
The technique currenly avaibale for third-party apps for this purpose is apprently overkill.
