### ISSUE TITLE
Remember unison difference

### ISSUE THREAD

**Issue by jjonescz** [emoacht/Monitorian#384]
Hi, thanks for this great project. I was wondering if it's possible to handle my common scenario:

1. Work on laptop, adjust brightness arbitrarily (single monitor). No problem here.
2. Connect to external monitor, adjust its brightness, enable moving in unison (let's say I set it 1:1). *This preference should be persisted.*
3. Disconnect from external monitor, or connect to another one (in other workplace), etc. Again adjust brightness arbitrarily.
4. Reconnect back to monitor from step 2. Now whatever brightness my laptop has, I would like the external monitor to match that automatically (since I set it to move in unison 1:1 in step 2). Without this, I have to always manually adjust it using the slider[^1].

[^1]: This is especially frustrating as my "OCD" forces me to exactly match the numerical value, i.e., I just cannot have `40` on one monitor and `41` on the other one. But it's sometimes difficult to move the slider right to achieve this 😉

I even implemented this by persisting "delta" (difference) in monitor brightness values of monitors configured to move in unison. See [my fork](https://github.com/emoacht/Monitorian/compare/master...jjonescz:Monitorian:persist-unison-delta). It's probably a hacky implementation, but I will gladly improve it under your guidance. I have been using that fork for some time successfully. Or maybe you have some other ideas how to achieve this?

**Comment by emoacht** [comment]
Thanks for the suggestion.
I checked your fork. The fundamental question is that monitors[0] is not necessarily the internal monitor. We cannot assume so. I assume that monitors in unison are equal and thus it is difficult to specify the base monitor.

**Comment by jjonescz** [comment]
I think it doesn't really matter which monitor is `monitor[0]`. When some monitor gets connected and it's set to be unison with some existing monitor, the new monitor's brightness should be adjusted according to the already-connected monitor brightness.

**Comment by emoacht** [comment]
If so, I don't think this idea useful so much.
So monitors[0] (monitor A) will be the base monitor to store the difference when a monitor (monitor B) disconnected. Then when the monitor (monitor B) reconnected, monitors[0] could be different monitor (monitor C). If it happens, there is no decent reason to change monitor B based on monitor C using the dirrence with monitor A. We need a persuasive reason to change monitor B.

**Comment by emoacht** [comment]
I remember the combination of unison and restore functions would be similar effect.

**Comment by jjonescz** [comment]
In your example, my implementation first assigns some unison delta to both monitor A and monitor B and saves it to settings (it doesn't matter what their index is, in the settings, they are uniquely identified it seems). Then when monitor C connects, its brightness would be only changed if it has been previously configured to be unison and has the delta in the settings.

For example, let's have brightness A=50, B=60; then unison delta of A will be persisted as 0, unison delta of B as 10. In another scenario, let's say there was brightness A=50, C=40; then unison delta of C will be persisted as -10. That's how it works.

> I remember the combination of unison and restore functions would have similar effect.

That's the problem, these settings go against each other. If I have monitor A and B in unison, let's say brightness 50. Then I disconnect B, adjust brightness of A to 100, reconnect B, its brightness gets restored to 50 and I'm left with 100-50, very unpleasing to my eyes. Plus I have to turn off unison temporarily to be actually able to correct the values.

**Comment by jjonescz** [comment]
> When the monitor is disconnected, the stored brightness is modified if the monitor is in unison and the brightness of other monitor in unison is changed.

Oh, really? That's actually cool, but didn't seem to work for me.

**Comment by jjonescz** [comment]
But that "restore brightness" function is not open-source, right? Although it's available in the free version available in Microsoft Store?

**Comment by emoacht** [comment]
I had modifed restore function because of the exactly same reason. Could you post operation.log? long one.

**Comment by emoacht** [comment]
The restore function is not open. It is because it uses the component of closed one.

**Comment by jjonescz** [comment]
Just tried it and it seems to work perfectly. Maybe I was using an older version (and haven't updated since I was using my fork). Anyway, thank you very much.
