### ISSUE TITLE
Menus disappear when they are in the overflow area

### ISSUE THREAD

**Issue by DennisGaida** [emoacht/Monitorian#385]
When the icon is moved into the taskbar / tray overflow area, the menus (right click and left click) can't be reached because they always disappear before I can ever click them.

This behavior does not happen when I have the icon pinned in the tray. See the following video for the observed behavior:

https://user-images.githubusercontent.com/2392217/207309668-0f8b2bf3-dda7-4c38-a4b8-c29061f34b2c.mp4

Runing latest Monitorian version (w/o subscription, though would love cmdline support) on Windows 11 22H2 Build 22623.891

**Comment by emoacht** [comment]
Thanks for reporting.
But I cannot reproduce it on Windows 11 22H2 22623.1028. We need the clear conditions to reproduce it.
