### ISSUE TITLE
Contrast adjustment

### ISSUE THREAD

**Issue by emoacht** [emoacht/Monitorian#390]
### Discussed in https://github.com/emoacht/Monitorian/discussions/389

<div type='discussions-op-text'>

<sup>Originally posted by **UnrealChrisB** December 16, 2022</sup>
Monitorian is fantastic, I use use it every day all the time.

Please consider adding more support for adjusting Contrast, much like already for Brightness.

Over the course of the day I'm constantly adjusting the contrast as well as brightness.

For example, I have dual monitors and so I have to adjust each monitor on contrast because there's no "Enable changing contrast in unison"
And command line, there's no support for contrast e.g. "/set contrast all 50" like "/set all 50" works for brightness. I use a bat file to switch on my favorite setting, but it doesn't include contrast.

Thanks.
</div>

**Comment by emoacht** [comment]
This request is related to #381 and #354

**Comment by emoacht** [comment]
As of Ver 3.15.6 of Microsoft Store version, contrast is supported for command-line options and hot keys.

### Command-line option

Inserting `contrast` after `/get` or `/set` will switch to contrast (e.g. `monitorian /get contrast all`). In addition, you can execute multiple options sequentially (e.g. `monitorian /get 20 /get contrast 20`).

### Hot keys

A hot key to switch to contrast and that to switch back to brightness are added. When switched to contrast, a hot key for brightness will work as that for contrast. This way, all hot keys for brightness can be used for contrast. I think this is the most versatile way to incorporate contrast hot keys.

**Comment by UnrealChrisB** [comment]
@emoacht Brilliant thanks!

**Comment by GuruOz** [comment]
thank you for your effort. i have resumed my subscription.
