### ISSUE TITLE
Command line on hotkey

### ISSUE THREAD

**Issue by UnrealChrisB** [emoacht/Monitorian#397]
Hi!

It would be good to be able to use command line scripts outside of making a .bat file.

How about we have in the "Set Keys" area, a box for a hotkey and associated command line arguments?

This would be useful because I often do this by double clicking bat files on my desktop.

Thanks for your consideration. This app is great!

**Comment by emoacht** [comment]
Thanks for the suggestion.
But it sounds excessively complicated.
I made this app can take combined commands. I will leave sending commands to other tools specialized for hot keys in general.
