### ISSUE TITLE
Turn off individual monitor?

### ISSUE THREAD

**Issue by UnrealChrisB** [emoacht/Monitorian#398]
Hi!

Is it possible to target an individual monitor to switch off?

With dual monitors, this is good when you're settling in to watch a film.

Could this be supported by command line?

And can it be added next to the individual monitor options like this image attached? 

![image](https://user-images.githubusercontent.com/90207881/210093663-f7ddb39e-d65c-4527-a653-a9daf4ee6976.png)

**Comment by emoacht** [comment]
Thanks for the suggestion.
First, turning off display and powering off indivisual monitor are different things. They are not substitutable.

Second, I have a doubt about the necessity to power off by hot key. After you power off a monitor either programatically or physically, you have to hit the physical power button of the monitor to power on it. You have to have access to the power button in any case. In addition, in contrast to brightness or contrast that you have to traverse OSD menu, you can hit the power button easily and quickly. I don't think there is a big difference between hitting keyboard and hitting the power button.
In sum, I cannot imagine there is strong demand for such hot key.
