### ISSUE TITLE
BenQ XL2730Z monitor not detected

### ISSUE THREAD

**Issue by halbrd** [emoacht/Monitorian#4]
My setup is as follows:

2 x Dell U2151h monitors (identified in app - called 'Generic PnP Monitor')
1 x BenQ XL2730Z monitor (missing from app)

DDC/CI is enabled on the BenQ. 

GPU is GTX 980, driver version 397.64.

OS is Windows 7 Professional.

Using Monitorian 1.5.1 standalone executable.

Can happily provide more information if needed. Thanks!

**Comment by emoacht** [comment]
Hi halbrd,
Could you try to connect the BenQ monitor alone? It may help to determine whether it is caused in conjunction with other monitors or not.

**Comment by halbrd** [comment]
I disabled the Dell monitors in Windows (did not unplug) and the BenQ now seems to show up with the name Generic PnP Monitor (like the Dells), but it states that it isn't configurable:

![image](https://user-images.githubusercontent.com/4065127/40164641-783b9f84-59fd-11e8-9529-56fd0b51ab7e.png)

I also renamed both of the Dells in Monitorian, so I'm pretty confident that the one referenced in the screenshot above is indeed the BenQ.

Not having delved too deep into the source code, I assume that Monitorian doesn't show monitors that can't be controlled, unless they're the only one(s) available? 

I'll see if I can get the BenQ to respond to DDC/CI signals with any other software - it might just be defective.

**Comment by emoacht** [comment]
Thanks for your information.

>Not having delved too deep into the source code, I assume that Monitorian doesn't show monitors that can't be controlled, unless they're the only one(s) available?

Yes, it is an expected behavior for the current version.
Monitorian uses a set of functions to get information on a specific monitor and if any of those functions fails, that monitor will be regarded as not controllable.  Let me have some time to prepare test code in order to identify which function fails.

**Comment by emoacht** [comment]
@halbrd Try [Ver 1.5.2](https://github.com/emoacht/Monitorian/releases/tag/1.5.2-Executables).
Open menu window and click Probe under Monitorian title. It will create Probe.log on the desktop which includes the results of the set of functions to get initial information on a monitor.

**Comment by emoacht** [comment]
Okay, this result clearly shows that, according to GetMonitorCapabilities function, the BenQ monitor (DisplayIndex: 0) does not support GetMonitorBrightness and SetMonitorBrightness functions through DDC/CI. I have no idea to remady this point at this moment.

**Comment by halbrd** [comment]
Sad to hear that. I'll leave it to you to close this issue or not.

**Comment by emoacht** [comment]
As another trial, I added low-level functions which use VCP features.
[Ver 1.5.3](https://github.com/emoacht/Monitorian/releases/tag/1.5.3-Executables)
It might make a change. This time, click Monitorian title three times to access "Probe monitors" button in menu window.

**Comment by halbrd** [comment]
Holy crap! It's working now!

![image](https://user-images.githubusercontent.com/4065127/40425983-3c67999c-5edd-11e8-863c-90df6dee65af.png)

I'm looking through the new commits but I don't have enough experience with the Windows APIs to understand what I'm reading. Anyhow, I don't know what you changed but as of 1.5.3 it's picking up the BenQ and controlling it correctly.

Thanks for the great support!

P.S. Any chance of allowing the user to reorder the monitors in the list? :wink:

**Comment by emoacht** [comment]
Thanks for your confirmation. I am glad to hear it works as expected.

>P.S. Any chance of allowing the user to reorder the monitors in the list?

No. The order is the same as that which the OS returns. It is intentional and so I can figure out what entry in main window represents what monitor easily regardless of its name.

**Comment by halbrd** [comment]
Alright, fair enough.

Do you intend to make a new full release with the changes from 1.5.3?

**Comment by emoacht** [comment]
Yes. Very soon. Then this issue will be closed.
