### ISSUE TITLE
Subscription not working. Not showing the extra features after the subscription.

### ISSUE THREAD

**Issue by kalilmd** [emoacht/Monitorian#407]
I already did the Microsoft store subscription through the app. I closed the app and reopened it several times. I reloaded the subscription information several times. And I still don't get the extra add-on features.

How long does it take for my subscription to be activated and for me to have access to the add-on features?

Thanks

**Comment by kalilmd** [comment]
On the Windows 11 Settings > Apps > Installed apps > Monitorian > Advanced Options

I repaired then reset the app and restarted the PC and now it's working fine.

**Comment by emoacht** [comment]
Thanks for sharing information.
I have no idea what was the problem. If any file in installation package is missed or corrupted, most probably this app will not start at all.
I move this issue to the discussion for the reference for other users.
