### ISSUE TITLE
Screen Temperature

### ISSUE THREAD

**Issue by UnrealChrisB** [emoacht/Monitorian#410]
Would it be possible to adjust the monitors colour temperature?

You know, like a monitor is typically 6500 k but have a slider to change it down 3000 k for a warmer.

Yes, windows has a night light slider for this, but to have it in monitorian would be super convenient and also hotkeyable.

**Comment by emoacht** [comment]
Thanks for the suggestion.
First of all, I think most users rarely change color temperature of a monitor once they unpack and connect it to the system. So I don't see strong needs on this.

In addition, I studied how to get/set color temperature by DDC/CI checking the capabilities string to date and found that most monitors only offer limited settings of color temperatures such as just warm or cold.

Thus I concluded that adding a hot key for color temperature would be enough.

**Comment by UnrealChrisB** [comment]
Thanks for adding this enhancement!

It does however, only work on my second monitor, the first does not respond at all. They are both the same model, both hdmi connected. I reset the monitors on it's built in menu. They are GIGABYTE G32QC.

Here's some log below, I notice it says in Unison is false, but the UI option is ticked "enable changing brightness in unision"

[Date: 22/03/2023 19:27:17 Ver: 4.2.2.0]
OnMonitorsChangeInferred (DisplayWatcher 4)

[Date: 22/03/2023 19:27:23 Ver: 4.2.2.0]
ScanAsync [22/03/2023 19:27:17]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413952",
      "Description": "G32QC A",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,2560,1440,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "IsTemperatureSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    },
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413955",
      "Description": "G32QC A",
      "DisplayIndex": 2,
      "MonitorIndex": 0,
      "MonitorRect": 2560,0,2560,1440,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "IsTemperatureSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413952",
        "Description": "G32QC A",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,2560,1440,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "IsTemperatureSupported": true,
        "Brightness": 10,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "G32QC A",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    },
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413955",
        "Description": "G32QC A",
        "DisplayIndex": 2,
        "MonitorIndex": 0,
        "MonitorRect": 2560,0,2560,1440,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "IsTemperatureSupported": true,
        "Brightness": 10,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "G32QC A",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 23/03/2023 09:43:17 Ver: 4.2.2.0]
Initiated

[Date: 23/03/2023 09:43:22 Ver: 4.2.2.0]
Get updates: No update

[Date: 23/03/2023 09:43:23 Ver: 4.2.2.0]
ScanAsync [23/03/2023 09:43:18]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413952",
      "Description": "G32QC A",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,2560,1440,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "IsTemperatureSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    },
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413955",
      "Description": "G32QC A",
      "DisplayIndex": 2,
      "MonitorIndex": 0,
      "MonitorRect": 2560,0,2560,1440,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "IsTemperatureSupported": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413952",
        "Description": "G32QC A",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,2560,1440,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "IsTemperatureSupported": true,
        "Brightness": 10,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "G32QC A",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    },
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\GBT3206\5&21d9b601&0&UID413955",
        "Description": "G32QC A",
        "DisplayIndex": 2,
        "MonitorIndex": 0,
        "MonitorRect": 2560,0,2560,1440,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "IsTemperatureSupported": true,
        "Brightness": 10,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "G32QC A",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 23/03/2023 09:43:26 Ver: 4.2.2.0]
KeyPressed: {Action=Activate} (Brightness)

[Date: 23/03/2023 09:44:20 Ver: 4.2.2.0]
KeyPressed: {Action=Activate} (Brightness)

[Date: 23/03/2023 09:44:21 Ver: 4.2.2.0]
KeyPressed: {Action=Activate} (Brightness)

[Date: 23/03/2023 09:44:21 Ver: 4.2.2.0]
KeyPressed: {Action=Activate} (Brightness)

[Date: 23/03/2023 09:44:29 Ver: 4.2.2.0]
KeyPressed: {Action=Activate} (Brightness)

[Date: 23/03/2023 09:44:46 Ver: 4.2.2.0]
KeyPressed: {Action=Quick} (Brightness)

[Date: 23/03/2023 09:44:47 Ver: 4.2.2.0]
KeyPressed: {Action=Quick} (Brightness)

[Date: 23/03/2023 09:44:48 Ver: 4.2.2.0]
KeyPressed: {Action=Quick} (Brightness)

[Date: 23/03/2023 09:44:52 Ver: 4.2.2.0]
KeyPressed: {Action=Quick} (Brightness)

[Date: 23/03/2023 09:45:47 Ver: 4.2.2.0]
KeyPressed: {Action=None, ActionName=ChangeTemperature} (Brightness)

[Date: 23/03/2023 09:45:48 Ver: 4.2.2.0]
KeyPressed: {Action=None, ActionName=ChangeTemperature} (Brightness)

[Date: 23/03/2023 09:45:48 Ver: 4.2.2.0]
KeyPressed: {Action=None, ActionName=ChangeTemperature} (Brightness)

[Date: 23/03/2023 09:45:48 Ver: 4.2.2.0]
KeyPressed: {Action=None, ActionName=ChangeTemperature} (Brightness)

[Date: 23/03/2023 09:45:48 Ver: 4.2.2.0]
KeyPressed: {Action=None, ActionName=ChangeTemperature} (Brightness)

[Date: 23/03/2023 09:45:51 Ver: 4.2.2.0]
KeyPressed: {Action=None, ActionName=ChangeTemperature} (Brightness)

**Comment by emoacht** [comment]
It is up to the current capability of each of your monitors. Could you post probe.log?

**Comment by emoacht** [comment]
Did you select the first monitor before hitting the hot key? It works for one monitor at a time.

**Comment by UnrealChrisB** [comment]
Attached the probe.log

Not sure how to "select" a monitor before hitting the hotkey?
[probe.log](https://github.com/emoacht/Monitorian/files/11049652/probe.log)

![image](https://user-images.githubusercontent.com/90207881/227175052-d85d3a5f-e2de-4c56-826f-a862428ccc77.png)

**Comment by emoacht** [comment]
Thanks for probe.log.
Selecting a monitor means to click the slider of the monitor, to change brightness or contrast of the monitor, use arrow key or hot key to select the monitor, or any action related to the monitor.
