### ISSUE TITLE
No sliders on Win11 with a Samsung Ultrawide 49 inch

### ISSUE THREAD

**Issue by khammo01** [emoacht/Monitorian#415]
Same with Windows store and Github downloaded versions. When left click on the taskbar icon, instead of sliders, can only see the word "Monitorian" in a box, next to the task tray. Right click shows the settings. 
Same behavior in both HDR and non HDR modes.

LC49RG92SSNXZA monitor in case that matters.

**Comment by emoacht** [comment]
Please read [Detection of external monitors](https://github.com/emoacht/Monitorian#detection-of-external-monitors)
I could not find a refenece to DDC/CI in its [manual](https://downloadcenter.samsung.com/content/UM/202108/20210824162657906/BN46-00901B-Eng.pdf).
