### ISSUE TITLE
Second monitor randomly losing signal since 4.0.1.0

### ISSUE THREAD

**Issue by UnrealChrisB** [emoacht/Monitorian#419]
Hi,

My second monitor keeps losing signal and reconnecting, it happens every now and then, maybe 10 times an hour and any other time every 4 hours or whatever, no pattern. I don't change any Monitorian settings for this to happen.

This only happens I've noticed (or it seems because it's so intermittent problem) after I've opened when Monitorian is running, even after closing Monitorian, at some point this will still happen.

I've swapped power cables and hdmi cables around, in all four combinations, and over the day, it will still happen only on the second monitor.

It seems to of be happening since the update to 4.0.1.0. It's been a while trying to find a solution but it could be something to do with Monitorian.

Can I send you a log for you to inspect? Like when this problem happens do I go to Copy operation log or Probe into monitors?

**Comment by emoacht** [comment]
I guess it is a hardware issue. I don't think that the DDC/CI commands sent by this app could disconnect a monitor from the system. If it happens, it must be an hardware issue.
Although the way to access a monitor by this app has not changed recently, you can try the older version and watch if it makes any difference.

**Comment by UnrealChrisB** [comment]
Hi emoacht,
I've still got this issue.
Can you help diagnose please?
How can I do a hard reset on all monatorian or dcc related activities etc, a flush out?

**Comment by emoacht** [comment]
If you want to reset all settings of monitor, a monitor should have factory reset fruntion in OSD menu.

**Comment by UnrealChrisB** [comment]
Thanks for your reply. Please watch this video and try to help me diagnose what's happening.
https://github.com/emoacht/Monitorian/assets/90207881/a4ff35b3-573a-4a42-88d6-b78b5c28fa6b

**Comment by emoacht** [comment]
Unfortunately, I have no idea at all.

**Comment by UnrealChrisB** [comment]
I guess it's one of 3 things.
1.SDR / HDR conflict, enabling windows HDR seems to stop it. Could be the way monitorian handles HDR with DCC.
2.When watching amazon prime video, if both monitors are on, then HD is available when you click the top right gear icon, but when I turn off one monitor HD is unavailable.
3.HDCP status (graphics card and display supports it, but might be this)
