### ISSUE TITLE
External monitor is not detected

### ISSUE THREAD

**Issue by xduseko** [emoacht/Monitorian#42]
Monitorian does not detect external monitor when it is connected using external USB-C hub, for example [this one](https://www.dx.com/cs/p/cwxuan-4-in-1-usb-3-1-type-c-to-hdmi-4k-usb-3-0-micro-usb-charge-hub-adapter-usb-c-hd-video-converter-2089658).

**Comment by emoacht** [comment]
Hi,
It depends on whether the device in question is compatible with DDC/CI. If not, there would be no chance.

**Comment by xduseko** [comment]
Hi. Monitor definitely is compatible. Tested before the hub arrived. Does the hub has to be also compatible in any way?

**Comment by emoacht** [comment]
Yes. In such case, the hub would be the real problem.

**Comment by xduseko** [comment]
Ok, thanks for the explanation. I will try another DDC/CI tool to verify that tomorrow in the office.

**Comment by xduseko** [comment]
Other tools are not working as well. Closing the issue. Thanks.
