### ISSUE TITLE
Simultanesouly change brightness and video color too?

### ISSUE THREAD

**Issue by alexeik** [emoacht/Monitorian#420]
Hi
Simultanesouly change brightness and video color too?
While u can change BR on display , BR on video (youtube and others video players) stays on default.

**Comment by emoacht** [comment]
I have no idea how to make video stays in dark. Could you elaborate it?

**Comment by alexeik** [comment]
video stays on default BR.
video BR doesn follow monitor BR.

**Comment by emoacht** [comment]
I have no idea on video BR.

**Comment by alexeik** [comment]
![image](https://user-images.githubusercontent.com/318732/224783806-4b7ee045-5218-4724-af85-865aa539d9d8.png)

Here)

**Comment by emoacht** [comment]
I see. It seems to be NVIDIA's proprietry settings.
I am not familier with NVIDIA's API. I found old [NVIDIA Control Panel API](https://download.nvidia.com/developer/SDK/Individual_Samples/screenshots/samples/NvCpl.html) but it is quite old.
Could you povide up-to-date information on NVIDIA's API?

**Comment by alexeik** [comment]
https://github.com/falahati/NvAPIWrapper
here
.net wrapper
but video support not available:)
maybe you can request by issue ?
