### ISSUE TITLE
4.2 still display 4.1 version

### ISSUE THREAD

**Issue by Riki7745** [emoacht/Monitorian#429]
...but had Unison option...
![capture](https://user-images.githubusercontent.com/377289/226167033-e0f05dce-40cb-4540-ba9f-a64b1fdd1048.jpg)

**Comment by emoacht** [comment]
Thanks! I will correct it.
BTW, the unison function hase been there and its behavior is changed in this version.

**Comment by Riki7745** [comment]
Thanx ! Another thing, how can I translate Monitorian ?

**Comment by emoacht** [comment]
Published [ver 4.2.1](https://github.com/emoacht/Monitorian/releases/tag/4.2.1-Installer)
I answered to your quesiton in Discussions.

**Comment by Riki7745** [comment]
You're The Flash !
