### ISSUE TITLE
Context menu style

### ISSUE THREAD

**Issue by MaxVonMustermann** [emoacht/Monitorian#43]
Hey, nice app, I really like using it. Only thing to improve in my opinon: Giving the user the ability to select a right click context menu design and adding one that fits the grey Windows 10 vanilla style. I know that this won't improve functionality, but I hope it will be added one day in order to improve consistency. :)

**Comment by emoacht** [comment]
Hi, Thank you for your suggestion.
When thinking about UI, usability with touch interface has been one of my concerns since the start of this project. Personally, I don't think context menu by right clicking is not the ideal way for day-to-day operation with touch interface. This is why I have tried to avoid using context menu as much as possible and I am reluctant to add it.

**Comment by MaxVonMustermann** [comment]
I'm talking about the popup menu that openes when the user performs a right click on the Monitorian icon in the taskbar's system tray. 
Your app has this transparency effect, while other system icons in the tray don't; they're mainly just grey.

For example the right click context menu of the volume icon: https://scr.wfcdn.de/19512/Windows-10-Build-18272-19H1-1541376539-0-12.jpg

**Comment by FurkanKambay** [comment]
The current context menu just has primitive controls anyway. The links wouldn't work but for that there could be an About item that shows a simple pop-up with the version info and the links.

I like the main window where you adjust the brightness just fine. I'm just talking about the current right-click menu like OP.

**Comment by emoacht** [comment]
@MaxVonMustermann So, your suggestion is to make the background of menu window non-transparent dark gray?
@FurkanKambay Could you clarify what you are really suggesting about menu window?

**Comment by FurkanKambay** [comment]
@emoacht I mean a Windows native context menu. Not a custom one.

**Comment by emoacht** [comment]
@FurkanKambay  I see. So are there any practical reason to use old context menu?

**Comment by FurkanKambay** [comment]
@emoacht I would say consistency.

BTW I'm not sure if the default context menu style for a UWP app is the UWP-style menu like Max wants or the older Win7-style white ones.  But if the UWP style context menu (like the context menu for the Network icon or Windows Security icon) is the default then that's what I think it should be. [This app](https://github.com/File-New-Project/EarTrumpet) also uses the UWP-style context menu.

**Comment by MaxVonMustermann** [comment]
> @MaxVonMustermann So, your suggestion is to make the background of menu window non-transparent dark gray?
> @FurkanKambay Could you clarify what you are really suggesting about menu window?

Well, my suggestion is to at least give the user the ability to turn off the transparancy effect for the context menu, yes.

**Comment by emoacht** [comment]
@MaxVonMustermann Thank you for clarification. It is not my priority but allowing user to customize the colors would be possible. Regarding the reveal effect, I reject it. It is not only useless but also really irritating when a user is in hurry. Such visual effect is not the purpose of this app.
@FurkanKambay Thank you for your explanation. As I wrote in other issue, I am not enthusiastic to completely reproduce UI designs of the current version of Windows. There are a number of variations of context menu and Microsoft has a history to change UI designs abruptly time to time.

**Comment by emoacht** [comment]
I implemented some command options to change window border and background by 2b195cbe2be9e386643530f2c2c702b25334e434

For example, to make the background of menu window non-transparent gray, the options will be `/menu_border #A0A0A0 /menu_background #2B2B2B`
