### ISSUE TITLE
Monitorian crashes whenever PC goes to sleep

### ISSUE THREAD

**Issue by infinitepower18** [emoacht/Monitorian#432]
Whenever I'm away from my PC (to the point where my PC decides to go to sleep) and return to use it again the Monitorian icon disappears from my taskbar. I have to manually open Monitorian again from the start menu to get it back.

This started happening recently as I don't recall this being a problem before.

**Comment by emoacht** [comment]
Please read [Operations](https://github.com/emoacht/Monitorian#operations) and post a operation.log after you notice it. The log may or may not give a clue.

**Comment by emoacht** [comment]
I would like to make clear that an app is expected to exit when an unexpected thing happens. The important thing is not keeping an app running but finding out how it happens.
Thus, a report without a meaningful clue is not helpful.

**Comment by infinitepower18** [comment]
@emoacht how can I do it when it keeps on saying this? How long do I have to keep it recording for?

<img width="295" alt="image" src="https://user-images.githubusercontent.com/44692189/227719189-853ca305-3b9a-43ab-91d1-2fdc726590d4.png">
