### ISSUE TITLE
Add function to turn off the montitor

### ISSUE THREAD

**Issue by thebishalniroula** [emoacht/Monitorian#436]
Add a button that when clicked turns off the monitor.

**Comment by emoacht** [comment]
Could you explain why you need it whereas you can hit the hardware switch any time?

**Comment by Jbravo70** [comment]
Just chiming in, on my monitors, the off switches are on the back side along with the OSD controls, not very convenient as I have 3, but I couldn't pass up the deal when I bought them.  (Monoprice 27S2G)   I love this app!!

**Comment by emoacht** [comment]
I guess the designer of the monitor did not expected a user to turn on/off each time. When the system turns off or suspends, the connected monitor will automatically suspend. That will be enough in most cases.

**Comment by Jbravo70** [comment]
I agree completely, not the best design for an on/off button, that might contribute to why they discontinued this specific model.  I turn them all off and on via a surge protector.   Thank you again for  making this app, it makes changing the brightness and contrast on all 3 at once very simple.

**Comment by emoacht** [comment]
@thebishalniroula Please undestand a person who made a proposal is expected to explain its necessity.
