### ISSUE TITLE
Command line options appear to not work when program installed from GitHub (instead of Microsoft store)

### ISSUE THREAD

**Issue by kalekje** [emoacht/Monitorian#437]
My corporate PC does not have the Microsoft Store, I therefore downloaded this app from GitHub instead. It installed to `C:\Program Files (x86)\Monitorian`. When I run `monitorian /set all +20` thru the command line, the brightness slider pops up, but no adjustment is made. I can still make adjustments by clicking and sliding the slider though.

I did not have this issue on my home PC where I installed thru the MS store and it downloaded the path specified in this documentation.

**Comment by emoacht** [comment]
As the command-line options are described in Add-on Features section, they are available only in Microsoft Store version.
