### ISSUE TITLE
When HDR is enabled on external display, Monitorian does not control its brightness. Only works when HDR is Off

### ISSUE THREAD

**Issue by oeloo** [emoacht/Monitorian#440]
Hi, I have a laptop (Dell) with an external monitor :
![image](https://user-images.githubusercontent.com/98819304/229461150-0422c7d2-cf55-4a08-a7ad-b241bdb86686.png)

Monitorian is working great when HDR on my external display is Off.
But when I have HDR turned On on my external monitor:
![image](https://user-images.githubusercontent.com/98819304/229462109-ce7b449c-a424-45e8-8740-78e839689092.png)
![image](https://user-images.githubusercontent.com/98819304/229462184-d426fa8a-a380-4f0f-84eb-76639f0de096.png)

In Monitorian, moving the slide for this external monitor is not changing anything.

For information, the built-in screen of my laptop always had HDR turned On, and this never caused any issue in Monitorian:
![image](https://user-images.githubusercontent.com/98819304/229462808-e8f9fb4b-0dff-4ce6-a01b-4c8188dd5277.png)

**Comment by emoacht** [comment]
Hi, have you read #411?

**Comment by oeloo** [comment]
No, though I had search for "HDR" in the Issues and the Discussions BEFORE making this issue 🤔

**Comment by emoacht** [comment]
Perhaps you searched it with the conditions of `is:issue is:open`. To search all issues, it should be `is:issue`.
The reason why closed is that there is no clue at all to look into it. No hope. At least at this moment.
