### ISSUE TITLE
Ability to adjust Brightsness without direct screen control

### ISSUE THREAD

**Issue by Shine753** [emoacht/Monitorian#445]
When you have a screen (main or second, doesn't matter) that cannot be controlled by Monitorian (I don't know the exact terms that leads to this), it could be great to keep having the ability to adjust their luminosity as other softwares like "Eye Saver" or "Free Monitor Manager", and the older "Desktop Lighter" do.

**Comment by emoacht** [comment]
I don't quite catch what you try to say. In fact, you puzzuled me.
Could you elaborate it?

**Comment by emoacht** [comment]
If an external monitor is not controllable vis DDC/CI, by definition, there is nothing this app can do.

**Comment by emoacht** [comment]
If an external monitor is not controllable via DDC/CI, there is nothing by definition this app can do.

**Comment by Shine753** [comment]
Seriously... ? Well, call this as you want but this obviously can be done. What a lack of curiosity...
I have a monitor that is not recognized by Monitorian and by many other softwares when connected through a KVM, that seems to break the DDC/CI feature. Even Windows have a hard time to recognize it at 100%. And these softwares succeed in adjusting its brightness anyway without any difficulties.
So what, are you telling that people who made these are magicians and you are not ?
In any case, you obviously lack imagination. Your answer reminds me a know citation "They didn't know that was impossible, so they did it..."

**Comment by emoacht** [comment]
To be clear, the technique to make the desktop look darker or lighter to some extent by manupulating color gammas has been there for long time. It is neither new nor magical. It considerablly affect colors themeselves.
I am just saying this app is intended to actual brightness settings but not the gammas.

**Comment by Shine753** [comment]
Oui, je suppose que c'est effectivement en jouant sur le gamma que ces applications arrivent à faire cela. Et effectivement, cela influe sur les couleurs. Mais, de mon point de vue, c'est un non-problème.

Parce que si vous êtes de l'équipe des personnes qui font du graphisme sur un écran parfaitement calibré, vous ne voudrez certainement pas modifier la luminosité de votre écran, puisque cela influe beaucoup sur la calibration de votre écran.

Si vous êtes de l'équipe des personnes qui aiment avoir des couleurs justes sur leur écran mais pas forcément parfaitement calibrées, avoir une légère perte de colorimétrie sur l'écran pour pouvoir ponctuellement ajuster la luminosité de votre écran reste acceptable (sinon vous modifiez la luminosité de l'écran de façon permanente). Et vous êtes a priori suffisamment au courant du sujet pour comprendre ce que vous faites.

Enfin si vous êtes de l'équipe qui se moque de la justesse des couleurs, vous ne vous posiez pas la question avant, et vous ne vous la poserez pas non plus après.

Par ailleurs, une même personne peut faire partie de plusieurs de ces équipes en même temps.

C'est là qu'un logiciel qui permet de modifier la luminosité via le gamma a, en plus de la méthode que vous utilisez, un avantage certain : il permet de modifier ponctuellement la luminosité de l'écran pour un besoin précis (ex : longue lecture sur fond clair), tout en conservant le réglage de la luminosité qui a été définie de manière hardware, et donc la calibration quand on revient au réglage de gamma initial.
C'est d'autant plus intéressant si l'écran est par exemple partagé entre deux ordinateurs, un par exemple pour de la visualisation de photos, et l'autre pour de la bureautique. Si on baisse la luminosité en bureautique, on ne souhaite pas forcément qu'elle soit répercutée sur les réglages de l'écran quand on basculera sur l'autre ordinateur.

Dans le même esprit, on peut avoir envie de régler la luminosité d'un moniteur via commande hardware, et d'un second écran via gamma.

Intégrer cette possibilité de réglage "via gamma" à votre logiciel serait ainsi un plus certain. Rien n'empêchant par ailleurs un petit mot d'avertissement  sur la gestion des couleurs, par exemple dans la documentation ou lors de l'activation de l'option.

-------------------------------------

Yes, I suppose that it is indeed by playing on the gamma that these applications manage to do this. And i agree, it affects the colors. But, from my perspective, that's a non-issue.

Because if you're on the team of people who do graphics on a perfectly calibrated screen, you'll certainly don't want to change the brightness of your screen, since this influence the calibration of your screen.

If you belong to the team of people who like to have good colors, but not necessarily perfectly calibrated, on their screen, having a slight loss of colorimetry on the screen to be able to adjust the brightness of your screen from time to time remains acceptable (otherwise you will think about modifying the screen brightness permanently). And you are in that case sufficiently aware of the subject to understand what you are doing.

Finally, if you're part of the team that doesn't care about the correctness of colors, you didn't ask yourself the question before, and you won't ask yourself it afterwards either.

Moreover, the same person can be part of several of these teams at the same time.

This is where software that allows you to modify the brightness via the gamma has, in addition to the method you use, a definite advantage: it allows you to occasionally modify the brightness of the screen for a specific need (eg: long reading on a bright background), while retaining the brightness setting that has been hardware defined, and therefore maintaining the calibration when returning to the initial gamma setting.
This is all the more interesting if the screen is for example shared between two computers, one for example for viewing photos, and the other for office tasks. If you lower the brightness in office tasks, you do not necessarily want it to be reflected in the screen settings when switching to the other computer.

In the same spirit, you may want to adjust the brightness of a monitor via hardware control, and of a second screen only via gamma.

Integrating this adjustment possibility using "gamma" for one or many managed screens into your software would thus be a definite plus. And a simple warning about color management can be shown, for example, in the documentation or when activating the option.

**Comment by Shine753** [comment]
Yes, I suppose that it is indeed by playing on the gamma that these applications manage to do this. And i agree, it affects the colors. But, from my perspective, that's a non-issue.

Because if you're on the team of people who do graphics on a perfectly calibrated screen, you'll certainly don't want to change the brightness of your screen, since this influence the calibration of your screen.

If you belong to the team of people who like to have good colors, but not necessarily perfectly calibrated, on their screen, having a slight loss of colorimetry on the screen to be able to adjust the brightness of your screen from time to time remains acceptable (otherwise you will think about modifying the screen brightness permanently). And you are in that case sufficiently aware of the subject to understand what you are doing.

Finally, if you're part of the team that doesn't care about the correctness of colors, you didn't ask yourself the question before, and you won't ask yourself it afterwards either.

Moreover, the same person can be part of several of these teams at the same time.

This is where software that allows you to modify the brightness via the gamma has, in addition to the method you use, a definite advantage: it allows you to occasionally modify the brightness of the screen for a specific need (eg: long reading on a bright background), while retaining the brightness setting that has been hardware defined, and therefore maintaining the calibration when returning to the initial gamma setting.
This is all the more interesting if the screen is for example shared between two computers, one for example for viewing photos, and the other for office tasks. If you lower the brightness in office tasks, you do not necessarily want it to be reflected in the screen settings when switching to the other computer.

In the same spirit, you may want to adjust the brightness of a monitor via hardware control, and of a second screen only via gamma.

Integrating this adjustment possibility using "gamma" for one or many managed screens into your software would thus be a definite plus. And a simple warning about color management can be shown, for example, in the documentation or when activating the option.

**Comment by emoacht** [comment]
Thanks for long explanation.
I reiterte this app is created for adjusting actural brightness. Nothing else.
I lock this issue.
