### ISSUE TITLE
A portable version ?

### ISSUE THREAD

**Issue by Shine753** [emoacht/Monitorian#446]
Would you mind providing a portable version of Monitorian ?
I suppose this can be done as there is a similar but less advanded software (https://github.com/blackholeearth/Win10_BrightnessSlider) that propose this.

**Comment by emoacht** [comment]
No, I don't see any necessity for it.
If you want to place executables on your own, read [Install/Uninstall](https://github.com/emoacht/Monitorian#installuninstall).
