### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [emoacht/Monitorian#45]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by emoacht** [comment]
@KovalevArtem Thank you for your feedback. I added explanation on Globalization under Development section of readme.
The following descriptions in menu window would be translated.
- Probe into monitors
- Start on sign in
- Use large buttons
- Show adjusted brightness
- Enable moving in unison
- Close
You can create a Resource file and send PR. Or if you provide Russian description, I will add the file.
