### ISSUE TITLE
Asus ProArt Display PA348CGV - not detected (but work with other software)

### ISSUE THREAD

**Issue by olegolegoleg** [emoacht/Monitorian#457]
Hi! The Asus ProArt Display PA348CGV monitor is not detected:
![image](https://user-images.githubusercontent.com/7686755/235522237-583f9fff-84cc-4272-9acc-8dafebdaed6c.png)

But I am able to change brigtness via ScreenBright app (it is also using DDC/CI):
![image](https://user-images.githubusercontent.com/7686755/235523222-b7069d82-225e-49e4-b4e1-c3d0eb936ac1.png)

Also DDC/CI is enabled for sure:
![photo_2023-05-01_22-10-52](https://user-images.githubusercontent.com/7686755/235523011-89659f24-6dd0-4672-9f5e-9a19c6bd5745.jpg)

Interesting, that after reinstall or update of the nVidia dirver (my GPU is GT 1030) Monitorian detects monitor correctly 1 time and allow to change brigtness.

I've genereted and added _probe.log_:
[probe.log](https://github.com/emoacht/Monitorian/files/11367834/probe.log)

**Comment by emoacht** [comment]
Thanka for the log.
The probe.log indicates that your monitor did not report its capabulities at all but getting/setting brightness was successful.
For such weird monitor, preclear option can be used. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

**Comment by olegolegoleg** [comment]
Hi @emoacht, thanks you very much! Now all works with "_/preclear + DeviceInstanceId_" argument. The _probe.log_ contains _DeviceInstanceId_ in 2 formats (lower and upper case and only upper case letters):
- `DISPLAY\\AUS342E\\5&27a40ad2&0&UID184576`
- `DISPLAY\\AUS342E\\5&27A40AD2&0&UID184576`

In my case only first (lower+upper) works – `DISPLAY\\AUS342E\\5&27a40ad2&0&UID184576`

The compleate target in the shortcut:
`"C:\Program Files (x86)\Monitorian\Monitorian.exe" /preclear "DISPLAY\\AUS342E\\5&27a40ad2&0&UID184576"`

![image](https://user-images.githubusercontent.com/7686755/235889419-05b1811d-fecb-4b64-992f-43aeeb65a1e4.png)

Thanks again, really nice app! Feel free to close the ticket

**Comment by emoacht** [comment]
Yes, the ID is case-sensitive.
It is because the device instance ID obtained by Device Context method is used internally to compare IDs and case-insensitive comparison requires a bit more cost than case-sensitive one. But perhaps the difference is neglisible. I will consider it.

**Comment by ryankhart** [comment]
I seem to have the same issue with my Asus monitor. It's an Asus PB278.
[probe.log](https://github.com/emoacht/Monitorian/files/11416320/probe.log)
[operation.log](https://github.com/emoacht/Monitorian/files/11416321/operation.log)

However, I was able to work around the issue and get it resolved, at least temporarily, by using the instructions found [here](https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584).

**Comment by emoacht** [comment]
Fix 97766cca7a10f3493a8b38937b28aa111654ca89
