### ISSUE TITLE
Slider bug and a request.

### ISSUE THREAD

**Issue by DeaD3R** [emoacht/Monitorian#462]
When using the slider, if you click outside of the thumb, hold the mouse1 down and then try to move the thumb, it starts moving from the previous position.

https://github.com/emoacht/Monitorian/assets/16120515/b2437c37-77a8-4e96-9fcc-7075ca1ac609

Now the request, which ties in with this bug, is to use the native windows sliders, other tools like twinkle tray and eartrumpet use them and don't have this problem, and are also more convenient. For example topmost windows will cover Monitorian slider, but won't cover twinkle tray's.

**Comment by emoacht** [comment]
Thank your for reporting.
First, it is not an issue of Slider. A Slider of this app is designed to faithfully reflect the brightness returned by the monitor. If you noticed a jump to particular level, it means that the actual brightness of the monitor is at that level. I am not sure what exactly happened in your monitor but [operation.log](https://github.com/emoacht/Monitorian#operations) might give a clue on it.

Second, there is no such "native windows slider" out of box.

Third, I coud not undertand you last sentence. Could you elaborate it?

**Comment by DeaD3R** [comment]
> First, it is not an issue of Slider

I disagree. Please try what I did in this video. click somewhere in the slider, and without releasing the mouse1 button, move the cursor left or right. It's an older monitor, but I don't see how it could be monitor's fault.

> Second, there is no such "native windows slider" out of box.

ah, that sucks.

> Third, I coud not undertand your last sentence. Could you elaborate it?

when a window that has topmost flag is located where the slider is located, the slider is not visible. Here's a video. Since I don't have twinkle tray anymore, I'll compare Monitorian's behavior with EarTrumpets.

https://github.com/emoacht/Monitorian/assets/16120515/b3475e23-232d-4161-b6b3-d03172758912

**Comment by emoacht** [comment]
As for the first point, I identified the root cause, I will fix it.

As for the third point, if the other app wants to stay topmost even after it shows up, I don't think it is nice hehavior though, I would prefer not to fight against such app.

**Comment by DeaD3R** [comment]
>As for the first point, I identified the root cause, I will fix it.

That's great news. Thanks for the quick response.

> As for the third point, if the other app wants to stay topmost even after it shows up, I don't think it is nice hehavior though, I would prefer not to fight against such app.

I respect your opinion. I personally think that such temporary corner popups like volume, brightness, quick actions should always be above other windows, because you specifically call them for a few seconds to adjust an important setting, and they don't take a significant amount of screen space. Sort of like If you click volume up/down key in windows or phone, it always shows on top of any other open window. This could also be an optional setting.

Hope I'm not being annoying, but since this issue is about slider, I'll add my one other request about it, I think it should always pop up in the right bottom corner, where everything else pops up, and shouldn't be dependent on the icon's location. Such a setting would also be great.

**Comment by emoacht** [comment]
As for the third point, the fight over the topmost is in fact, quite complicated when the other app does not gracefully go to background.

As for the fourth point. I reject it. As I explained in another issue, it is to make the movement of cursor from the notification icon the shortest. Search old issues.

**Comment by DeaD3R** [comment]
> As for the fourth point. I reject it. As I explained in another issue, it is to make the movement of cursor from the notification icon the shortest. Search old issues.

That's not the case when the icon is not pinned and is in the "hidden icons" group. Also even when pinned, the distance is only shorter to 100% brightness point, but farther than normal from 0%.

Anyway, it's your app, you know best. I moved to Monitorian because of its light weight compared to twinkle tray, but I think I'll go back for now since I like their slider's behavior more.

Monitorian is great, and thank you for putting in time to create and maintain it. All the best.

**Comment by emoacht** [comment]
The location of a notification icon in notification area and that of a notification icon in overflow area depend on the width of notification area and the width depends on the number of elements in notification area. I think in most cases, it is the case. But as you pointed out, if the distance from a notification icon to the sliders, assuming the center of, in this app matters and if the notification area is short, it is not. The best way to shorten the distance would be to place the horizontal center of this app at the horizontal center of the notification icon in the case where the notification icon is in notification area. But next question is how to make this behavior consistent thoughout a variety of cases of locations of the notification icon.

**Comment by emoacht** [comment]
Fixed c8c94b18033d5702f79a3f35e1c1b5bdecdf8c4f
