### ISSUE TITLE
Help detecting monitors

### ISSUE THREAD

**Issue by Scarl5** [emoacht/Monitorian#466]
Hey, I don't know much about the protocol, but I wanted to ask if you could shine some light about what is going on in my setup.
I have a double monitor setup and the program sometimes detects one of them, sometimes none, sometimes the other one but its not consistent. Restarting the monitor does not help either but restarting the app sometimes changes what monitor is working.
I have tried the preclear command but maybe I'm doing it wrong, maybe it doesn't work like that, but maybe there is a command that could help me so that's why Im asking. Here is both logs that you request:
[operation.txt](https://github.com/emoacht/Monitorian/files/11470940/operation.txt)
[probe.txt](https://github.com/emoacht/Monitorian/files/11470941/probe.txt)

I have changed the extension because it wasn't letting me upload them

**Comment by emoacht** [comment]
Thank you for the logs.
Your monitors don't respond to inquiries for capabilities but preclear option should work. However, it cannot fix hardware instability.

**Comment by Scarl5** [comment]
K, the preclear seems to work well for one monitor, but the other one is having some trouble, maybe I'm using the preclear wrong, is this okay?
![image](https://github.com/emoacht/Monitorian/assets/33733480/9d5ba76d-75aa-44f8-8a53-094b9ede77df)

**Comment by emoacht** [comment]
You don't need to repeat `/preclear`. It should be like
```
/preclear [First Device Instance ID] [Second Device Instance ID]
```

**Comment by Scarl5** [comment]
That was it, Thank you very much
