### ISSUE TITLE
Command-line does not work with Monitorian 4.3.0 installed via MSI

### ISSUE THREAD

**Issue by wigust** [emoacht/Monitorian#467]
Hi.

Environment:
I've installed Monitorian on Windows Server 2022 Standard Evaluation 10.0.20348.587 with MSI from https://github.com/emoacht/Monitorian/releases/download/4.3.0-Installer/MonitorianInstaller430.zip with a default configuration (installed by mouse double click on the MSI file).

Issue:
Cannot control a monitor brightness with via command-line interface provided by the Monitorian.exe program.

Steps to reproduce:
1. Install Monitorian 4.3.0 MSI.
2. Start Monitorian with `Monitorian.exe`.
3. Invoke `Monitorian.exe` with `/get all` or `/set all 30` in CMD.exe.

Getting:
No output to the console. Brightness does not change. The Monitorian pop-ups a window from start-menu showing current brightness, where I could change brightness manually by a mouse slide.

Expecting:
Brightness changes according to the value (30 in the Steps to reproduce).

Extra information:
Also, I have a Windows 10 machine with Monitorian. MSI installation does have the same issue with controlling brightness via command-line. Windows Store installation does not have the issue and works with command-line as expecting according to the Monitorian/README.md documentation.

**Comment by emoacht** [comment]
You are not the first person who missed that command-line options is under Add-on Features section.
