### ISSUE TITLE
monitors not detected after docking/undocking

### ISSUE THREAD

**Issue by Snuupy** [emoacht/Monitorian#468]
Hi,

I have a laptop connected to a usb-c dock. If I plug in the dock and start Monitorian afterwards, the monitors are detected.

However, if I start Monitorian, and then plug in the dock, the monitors are not detected.

If I unplug the laptop from the dock and plug it back in, the monitors are not detected.

Both monitors are DCC compatible and work with Monitorian as long as I plug in the dock first, and restart the app every time.

Can this be fixed?

**Comment by emoacht** [comment]
Please read through [Detection of external monitors](https://github.com/emoacht/Monitorian#detection-of-external-monitors)

**Comment by Snuupy** [comment]
Which bullet point are you referencing specifically? The dock supports DCC/CI. It's when the state of the system changes (i.e. unplugging/replugging) that Monitorian does not handle the new system state, no?

**Comment by emoacht** [comment]
It depends on how rapidly your monitor responds to the query from this app after being replugged. You can check it by operation.log. Please read [Reporting](https://github.com/emoacht/Monitorian#reporting).
