### ISSUE TITLE
Feature Request: switch Monitor input source

### ISSUE THREAD

**Issue by ccchiou** [emoacht/Monitorian#469]
I would like a feature to switch monitor input
Because I have an Xbox and PS4 connecting to the monitors
To switch the input source in my monitor, it required me to push some buttons 5 times
I'm just too lazy about it.

I know that DDC/CI  supported monitor can do it

A quick idea is some small buttons next to the monitor name to switch between HDMI1&2 DP1&2
![image](https://github.com/emoacht/Monitorian/assets/5751738/643e448f-4033-4ac6-9c65-8bb63ee4e81a)

**Comment by emoacht** [comment]
See #464
