### ISSUE TITLE
UWP project

### ISSUE THREAD

**Issue by ashikns** [emoacht/Monitorian#47]
There is a windows store version of Monitorian, but the repo does not contain any uwp projects. Can you please provide info how the uwp package was created?

PS: Monitorian is the only tool I use everyday yet is not widely popular. It really should be. I could not find any other tool that controlled both WMI and DDC monitors with a really simple UI as well. Thanks for your awesome work!

**Comment by emoacht** [comment]
@ashikns I have used DesktopAppConverter to create the package for Microsoft Store and so there is no such project.
Anyway, the content of manifest file is specific to a particular developer and not usable by other people.
