### ISSUE TITLE
Feature request: Scheduling / automatic brightness based on time

### ISSUE THREAD

**Issue by 1000goalgaming** [emoacht/Monitorian#471]
As someone with smart lights that change throughout the day, I feel like this feature would be useful for not just me, but anyone else with an environment whose lighting adapts to the day/night cycle. It would be amazing if Monitorian could adjust the brightness based on time automatically instead of one having to make manual changes.

**Comment by emoacht** [comment]
I answered to the same suggestion repeatedly. Search old issues.
In short, I recommend to use Task Scheduler other scheduling utility. You can make a detailed and complex schedule as you wish with Task Scheduler. See readme.
