### ISSUE TITLE
Suggestion: `Tab` Key: should also select the contrast slider

### ISSUE THREAD

**Issue by schittli** [emoacht/Monitorian#472]
Hello

**thank you very much for sharing your great work!**

I have a small suggestion: If the contrast slider is visible:
![image](https://github.com/emoacht/Monitorian/assets/8282673/b8e573b1-6e94-4fa1-b8b6-e8796f42991b)

Then it looks like there is no keyboard shortcut to navigate to the contrast slider. The `Tab` key just jumps between the two monitors.

#### I think it would be very useful if the `Tab` key would navigate between all sliders, 
from left to right and from top to bottom:

1. Focus on top Monitor, left slider: brightness
2. Focus on top Monitor, right slider: contrast
3. Focus on the bottom Monitor, left (middle) slider: brightness

Thanks a lot, kind regards,
Thomas

**Comment by emoacht** [comment]
Thanks for the suggestion.
I have not paid much attention to tab navigation but it certainly isn't good. So I improved.

**Comment by emoacht** [comment]
Fixed 4b4a444717f00f12f3cfee587e1ca11775a04211
