### ISSUE TITLE
Monitors over a converter plug not supported?

### ISSUE THREAD

**Issue by homit-dalia** [emoacht/Monitorian#477]
I have a monitor plugged in via USB-C to VGA adapter. It is not detected by Monitorian. However, the same monitor works when directedly connected to VGA cable. Monitor-2 missing from the list.

![image](https://github.com/emoacht/Monitorian/assets/103167599/42c0e1f1-ac7e-449b-a160-a3c5dbe8e981)

**Comment by emoacht** [comment]
Please read [Detection of external monitors](https://github.com/emoacht/Monitorian#detection-of-external-monitors) and if you wish to make clear what is happning, post the logs.

**Comment by homit-dalia** [comment]
Thanks. You can close the issue. The adapter probably does not support it.
