### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by dzid26** [emoacht/Monitorian#479]
Usually, after waking up from modern standby. 

I have a laptop screen + two monitors via USB-C -> HDMI

Log
[exception.log](https://github.com/emoacht/Monitorian/files/11923799/exception.log)

**Comment by emoacht** [comment]
Thank you for reporting.
Could you post [probe.log](https://github.com/emoacht/Monitorian#probe) of your monitor?

**Comment by dzid26** [comment]
[probe.log](https://github.com/emoacht/Monitorian/files/11928367/probe.log)

**Comment by emoacht** [comment]
Thank you for the log.
I guess your VX2370 returns erroneous capabilities string and it cause the exceprion.
I can avoid it.

**Comment by emoacht** [comment]
Fixed by 32ba21b6876af10f2e1cfd698cdd166420108428

**Comment by dzid26** [comment]
Btw, probing seems to be a little unreliable. I noticed that now I am getting `CapabilitiesString` responses from all three monitors. 
[probe.log](https://github.com/emoacht/Monitorian/files/11929527/probe.log)

Anyway, regardless, I will report back if it is still crashing at all.
