### ISSUE TITLE
App doesn't notify for updates

### ISSUE THREAD

**Issue by schroef** [emoacht/Monitorian#483]
Im currently running 3.6.5.0 and noticed just noow the app is already at 4.4. Is it correct the app doesnt notify the user when a new update is ready?

**Comment by schroef** [comment]
Looking at this screenshot, its weird the store doesnt show "update" you can clearly see the installed version is lower
![monitorian-v3560](https://github.com/emoacht/Monitorian/assets/6923008/e94e4f6e-e4e0-44f5-9376-19375aeee6b2)

**Comment by schroef** [comment]
I had this same behavior before in this issue; https://github.com/emoacht/Monitorian/issues/204

**Comment by schroef** [comment]
Could it be because i see 2 installed, when i search for the app. 2 show up under apps
![monitorian-2-installed](https://github.com/emoacht/Monitorian/assets/6923008/ba1b3841-4e7a-426f-bfc7-67fcd1a42cf1)

On shows as 4.4.1.0 when i click advanced, the other i cant check in advanced options. Ill try to delete that second one
![monitoria-2-advanced](https://github.com/emoacht/Monitorian/assets/6923008/70c83ee0-f0b1-4dcf-a171-20ac4596c400)

**Comment by emoacht** [comment]
The update function is only available in Microsoft Store version. It is because the function utilizes Store API.

**Comment by emoacht** [comment]
You installed Microsoft version (4.4.1.0) and standard version (3.6.5.0).
As far as I know, Microsoft's "Microsoft Store" app only cares about an app installed from Microsoft Store.

**Comment by schroef** [comment]
Yeah somehow 2 version were installed. But only the older one was running
 Removed that now
