### ISSUE TITLE
Feature request: monitor brightness and contrast schedule

### ISSUE THREAD

**Issue by yakhl** [emoacht/Monitorian#488]
Please add the function of creating a schedule for automatically changing the brightness and contrast of the monitor. It is very convenient to change the brightness and contrast in the evening to the minimum value.

**Comment by emoacht** [comment]
You can use command-line options od add-on feature combined with Task Scheduler. Task Scheduler is quite versatile and proven scheduler.

**Comment by emoacht** [comment]
I have answered to the same reguest several times. Please read contributing guidelines.
