### ISSUE TITLE
Is it possible to add a Button to rotate the monitor?

### ISSUE THREAD

**Issue by mayeths** [emoacht/Monitorian#49]
I have a Dell U-Series monitor and sometime I need to rotate it to assist me in programming or watch video. Use Windows Setting is somewhat annoying.

Is it possible to add a Button to rotate the monitor?

I love this app. It's toooooo convenient to set brightness.

**Comment by emoacht** [comment]
Hi, Mayeths
Although the rotation would be technically possible, it is out of the scope of this app.
While I found that the hot keys for rotation which Intel and other chip vendors had provided with their driver utilities no longer available for Windows 10, I am not sure it worth to implement this functionality at this moment.
