### ISSUE TITLE
Monitarian slider window appears behind taskbar

### ISSUE THREAD

**Issue by smbell1979** [emoacht/Monitorian#494]
I'm having an issue where the window appears behind my taskbar. I thought it might have been because I was using start11, but It does the same thing with the native win11 taskbar.

![image](https://github.com/emoacht/Monitorian/assets/76536166/6817120c-f0ba-41c5-9bc4-e5a9e9f1cf04)

**Comment by emoacht** [comment]
Thank you for reporting.
Probably it manipulates the standard taskbar. What a nuisance behavior.
Could you try Ver [4.4.7](https://github.com/emoacht/Monitorian/tree/4.4.7-Installer)?

**Comment by emoacht** [comment]
Thank you for reporting.
Probably it manipulates the standard taskbar. What a nuisance behavior.
It could be fixed by 8a0a70267c4bcc540fe4f06f01a9c6018cd5936d
