### ISSUE TITLE
Monitor not detected

### ISSUE THREAD

**Issue by uttarayan21** [emoacht/Monitorian#495]
Hi, Thank you for the application it's super useful. 

Monitorian doesn't seem to detect my monitor for some reason.

here is the [probe.log](https://github.com/emoacht/Monitorian/files/12333199/probe.log)

On linux IIRC I can control it with ddcutil.

When probing It does seems to change the monitor's brightness for a second but even with rescan it doesn't show up in the menu.

The monitor also has a usb interface for Gigabyte's software
which also has a python script to control it here.
https://gist.github.com/wadimw/4ac972d07ed1f3b6f22a101375ecac41

**Comment by emoacht** [comment]
Your Gigabyte monitor did not respond to the query for capabilities.
In such case, use `preclear` option https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

**Comment by uttarayan21** [comment]
Thank you. That works perfectly.
