### ISSUE TITLE
It is hard to choose a precise value using the slider

### ISSUE THREAD

**Issue by ibrahimGit123** [emoacht/Monitorian#499]
It is hard to choose a precise value using the slider. For example, if i want a value of 18, it is hard to get that exact number without clicking with the mouse multiple times.

Suggested solution: Allow us to use keyboard left and right arrow keys when we click on the slider to increment+1  and -1 values. Another option is to add clickable arrows on the left and right of the slider that increment +1  and -1

**Comment by emoacht** [comment]
Moving a slider with larrow keys is already there. Once you click on the slider, you can move it with left or right arrow key.

**Comment by ibrahimGit123** [comment]
O, I see. I did not notice because it does not move one point per arrow click. It just moves when you keep pressing the arrow down. That can work, but i think it would be much more intuitive if it moved 1 point for each arrow click

**Comment by emoacht** [comment]
I found that the combination of a setting of Slider and custom dunction causes this behavior.
Fixed by bb8824ebe4707b96f636d25682c62192ad43ee29
