### ISSUE TITLE
Laptop crashing when launching app

### ISSUE THREAD

**Issue by CashflowCommander** [emoacht/Monitorian#500]
Hi all,

I'm trying to setup a way to adjust the brightness of my 3 external monitors from my laptop. I haven't seen this issue reported anywhere and I'm hoping someone can help troubleshoot.

The laptop has its screen disabled via windows, two monitors are connected via a USB c hub and HDMI, and the main monitor is connected VIA hdmi directly to the laptop's output. When I launch Monatorian the entire laptop crashes. I actually don't think I've ever gotten a "Your pc encountered an error" message prior to this in my years of using this setup. This also happens when launching the Twinkle Tray app, which I imagine works in a similar way. I haven't seen this talked about as a common error so I'm hoping someone can help.

Edit: this is on windows 10, the error is a "Kernal security check failure". It only triggers when the second set of monitors is plugged in via the USB c dock. Just to be clear, this only occurs when the app is running.

**Comment by emoacht** [comment]
So fatal error happens. Perhaps you system has something unusal but I cannot tell.
