### ISSUE TITLE
Why can't the screen above the keyboard on the Asus UX4100E model dual-screen laptop be detected?

### ISSUE THREAD

**Issue by ShisanXing** [emoacht/Monitorian#501]
华硕UX4100E型号双屏笔记本电脑键盘上方的屏幕为什么识别不到呢？
Why can't the screen above the keyboard on the Asus UX4100E model dual-screen laptop be detected?

我原计划向用这款软件替换掉华硕官方那款难用到让人想呕吐的ScreenPad Plus，但发现只有它们的软件可以控制副屏亮度，尝试了各种办法都无法绕过控制

**Comment by emoacht** [comment]
Please rewrite in English.

**Comment by emoacht** [comment]
And could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.
