### ISSUE TITLE
Make tray icon customizable

### ISSUE THREAD

**Issue by gfgjs** [emoacht/Monitorian#503]
Can the system tray icon be modified or customizable, as shown in this image:
<img width="36" alt="1" src="https://github.com/emoacht/Monitorian/assets/29412548/efa3a6fc-3429-427a-ae60-2b2f7a4c870d">
Just like the icon on the right side of this picture.
![light](https://github.com/emoacht/Monitorian/assets/29412548/1b7285b1-2d2e-4972-a58e-9958454cb4f2)
(white, invisible)
And this icon comes from iconfont.cn.

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md)?
Please add rationale. I do not have any incentive to make it changeable.
