### ISSUE TITLE
Availability to tune brightness by hotkey

### ISSUE THREAD

**Issue by prounlocks** [emoacht/Monitorian#508]
Hello!
Pleaese can you add shortcuts feature for keyboard and direct input (xinput) devices like joysticks etc.
I have displaylink USB display and DP display -both contolling via Monitorian. i have MFD airplane display which have direct input keys to regulate brightness.

Windows brightness embedded slider not working for desktop PC  as well.

**Comment by emoacht** [comment]
The shortcut keys from kerboard are already there.
Could you elaborate input by joystick and "MFD airplane display"? I don't have them.

**Comment by emoacht** [comment]
Regarding joystick, I don't think capturing the input by joystick is practically useful. Rather, use arrow keys.
Regarding MFD device, I doubt the inputs from such device can be captured by ordinary apps.

**Comment by prounlocks** [comment]
Arrow keys? You have working hotkeys already?
Tell me please also can we hook to standard brightness windows hotkeys?
Now brightness indicator appears but not working on windows for desktop PC.

Whould be greate if we can stick together monitorian and windows regulator
 (Fn + F1  F2)


Пт, 8 сент. 2023 г. в 12:56, emoacht ***@***.***>:

**Comment by emoacht** [comment]
Please do not post by email. It is expained in Contributing Guideline.
