### ISSUE TITLE
Not recognizing all monitors

### ISSUE THREAD

**Issue by berollin** [emoacht/Monitorian#509]
Monitorian is not recognizing all 4 monitors.  See image.

Recognized. 2 Acer monitors.  Connected through my Logidock via usbc port.
Recognized. Dell laptop monitor.
Not recognized. Asus Monitor (portrait).  Connected through directly through 2nd usbc port.

![IMG_2206](https://github.com/emoacht/Monitorian/assets/144267875/0ab82e9a-2e7c-4181-a36d-81ece442b7cb)

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__ and __operation.log__? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.
