### ISSUE TITLE
Feature request: Equal brightness setting when laptop is charging or not

### ISSUE THREAD

**Issue by bladE667** [emoacht/Monitorian#511]
Windows remembers the screen brightness settings separately if the computer is charging or running on battery power alone. An additional setting would be useful to override this directly from the Monitorian software.

**Comment by emoacht** [comment]
Thank you for the suggestion but could you elabolate more?
I could understand what you mean but cannot explain why and when it is useful.

**Comment by bladE667** [comment]
No problem. Less need for adjusting the brightness when unplugging or plugging the charger.  This can be set from the OS as well, but that can be tedious. I found this feature useful, when laptop is suffering some minor and random charging problems.

**Comment by emoacht** [comment]
Thanks. But I think we need to have more easily understandable, straightforward explanation about this function for users who are not familiar with power management stuff.

I tentatively added an option by 6b11dd4ea74021d167410ac6f3d1757da8e7cc16
This function will be enabled by `/powerbind` command-line option.
