### ISSUE TITLE
FEATURE REQUEST Allow Naming Devices

### ISSUE THREAD

**Issue by FlyinPancake** [emoacht/Monitorian#516]
I know this may seem silly, but I have identical monitors and sure they appear according to arrangement, it would be nice to rename them i.e.: `left`, `mid`, `right`.

I hope you have the capacity for this, if not I might be able to look into the code and submit a PR

**Comment by emoacht** [comment]
Please read Remarks in readme.

The monitor name shown in main window can be changed to distinguish monitors easily. To change the name, press and hold it until it turns to be editable.
