### ISSUE TITLE
Support for KVM - probably reconnecting issue

### ISSUE THREAD

**Issue by TomaszGawlikPL** [emoacht/Monitorian#517]
I am using 3 PC's with KVM (monitor, mouse and keyboard are switched between 3 connected PCs). On two of them I use Monitorian. Unfortunately when switched to different PC with Monitorian instance running and back to previous one it does not work. Restarting app does the trick. I did not checked sources yet but it is probably a matter of checking if connection is alive. For example if brightness is changed but "connection" is broken (other instance was initialized later) than changing brightness does not change its value. It is read correctly but changes are not applied - read value is unchanged. This could be used to detect the strange state. There might be easier more direct ways to check this.

**Comment by emoacht** [comment]
Thank you for reporting.
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post  __operation.log__? Don't forget to post the exact time when each change happened that I can find the corresponding event or action in the log. How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.

**Comment by emoacht** [comment]
Is it possible to provide operation.log within a few days? If not, this issue will be closed.
I have seen so many people just opened an issue but did not respond to the request for additional information.

**Comment by TomaszGawlikPL** [comment]
I will do this in the morning.

Wysyłane z aplikacji Outlook dla systemu iOS<https://aka.ms/o0ukef>

www.sportradar.com

​
​You hereby acknowledge the information contained in and accompanying this communication is confidential and is intended only for the named recipient(s). If you are not a named recipient, please notify the sender immediately and delete any and all copies of this message. Any unauthorized copying, disclosure, distribution of, and/or taking any action with respect to the contents, attachments, and/or other materials in this e-mail is strictly forbidden without Sportradar’s express, written permission. Additionally, the integrity and security of this email cannot be guaranteed over the internet and Sportradar disclaims any and all liability for damage arising from transmission of this email to the fullest extent permitted by applicable law. Further, the views and expressions included in this email are the views and expressions of the sender and may not reflect the views of Sportradar. Sportradar disclaims any and all liability for damage arising from these views and expressions and/or your actions taken upon reliance of these views and expressions to the fullest extent permitted by law.
________________________________
Od: emoacht ***@***.***>
Wysłane: Wednesday, September 27, 2023 1:00:35 AM
Do: emoacht/Monitorian ***@***.***>
DW: Tomasz Gawlik ***@***.***>; Author ***@***.***>
Temat: Re: [emoacht/Monitorian] Support for KVM - probably reconnecting issue (Issue #517)

Is it possible to provide operation. log within a few days? If not, this issue will be closed. I have seen so many people just opened an issue but did not respond to the request for additional information. — Reply to this email directly,


Is it possible to provide operation.log within a few days? If not, this issue will be closed.
I have seen so many people just opened an issue but did not respond to the request for additional information.

**Comment by Gawson** [comment]
![Zrzut ekranu 2023-09-27 143422](https://github.com/emoacht/Monitorian/assets/6636946/fdfaedd2-a2c0-4e42-bd3b-46ff0a8ee8a6)

[operation.log](https://github.com/emoacht/Monitorian/files/12738615/operation.log)

This is operation log from one of the PC's. Second does not want to generate log. It claims "wait for more log to be registered".

**Comment by Gawson** [comment]
Desktop PC is sometimes able to recover (Nvidia graphics P2200). On a Dell Laptop (integrated Intel card) I did not see this behaviour. I need to restart app nearly each time I switch computers with KVM.

**Comment by Gawson** [comment]
Ok. Got log from Dell laptop.
[operation.log](https://github.com/emoacht/Monitorian/files/12738693/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/12738695/probe.log)

**Comment by emoacht** [comment]
Thank you for the logs.
The first operation.log shows that the control over the monitor was restored.
The second operation.log shows that this app was restarted and after that the monitor is regarded as not compatible with DDC/CI completely untill the app was restarted again.
It is hard to distinguish between a monitor that can be compatible but not accessible at that time and a monitor that is not compatible completely.

**Comment by emoacht** [comment]
As a workround, you can use `preclear` option. Please see https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584
