### ISSUE TITLE
Moving in unison breaks easily

### ISSUE THREAD

**Issue by p1ho** [emoacht/Monitorian#52]
Hello, first of all, I'd like to say thank you for your hard work and open sourcing this.

I'm not sure if this was designed or a bug, but I have 2 monitors that I'd like to have synced brightness. Now sometimes the percent value may be off by a little bit (like 60% and 70%), but I'd still want them to move together.
<img src="https://user-images.githubusercontent.com/22629067/64928443-88423100-d7e6-11e9-8d47-baa061ae5b84.png" height="100">

I found that when two percent values are off, even by a little bit, when brightness for one monitor reaches an extreme (100% or 0%), it becomes very easy to break *moving in unison*, and you have to manually add to it again.
<img src="https://user-images.githubusercontent.com/22629067/64928455-a314a580-d7e6-11e9-95f2-6f2290d7cce3.png" height="100"><br>(Fig. 2 one monitor reaches an extreme, moving in unison still enabled)

<img src="https://user-images.githubusercontent.com/22629067/64928497-0b638700-d7e7-11e9-9519-ef3e05d9c24c.png" height="100"><br>(Fig. 3 if you try to make the other 100%, it breaks moving in unison)

I was wondering if this was expected behavior, and if so what was the reasoning. Thanks in advance!

**Comment by emoacht** [comment]
Hi Paul,
It is completely expected behavior.
The idea behind is that the movement of the master (the monitor which the user is currently changing) should not be hindered by the slaves (the other monitors in unison).
From the coding point of view, the master does not know about the statuses of slaves and the slaves do not have the ways to share their values with the master. The relationship between the master and slaves are already somehow complicated and I did not want to introduce the additional complexity to it.

**Comment by p1ho** [comment]
Thank you for the response! I was unaware of the master/slave relationships.

I was hoping there would be a way to lock master monitor brightness at 100% while moving the slave monitor's brightness up without breaking the relationship or vice versa.
I was wondering if we disregard the technical constraints, would this be a bad idea?


This is slightly unrelated, so if you'd like I can open this in a separate thread.
I have another question about clicking the button. I understand that a single click is supposed to increment by 10%, but when I have the 2 monitors synced, the other one increments by 20%, is this also caused by the master/slave relationship?

<img src="https://user-images.githubusercontent.com/22629067/64998388-f4d63200-d8b1-11e9-9197-bcc6ed00e787.png" height="100"><br>before click

<img src="https://user-images.githubusercontent.com/22629067/64998411-0ddee300-d8b2-11e9-83ee-15fa927f3a91.png" height="100"><br>after click

**Comment by emoacht** [comment]
I am a little bit confused. Do you mean "I was hoping there would be a way to lock _slave_ monitor brightness at 100% while moving the _master_ monitor's brightness up without breaking the relationship or vice versa." ?

And thanks for reporting the odd behavior. I found it is a bug. It happens complex interaction between the movements of monitors.

**Comment by p1ho** [comment]
For the bug, no problem! Do you need me to open a separate issue for it?
(Or I can change the title so the bug is easier to track)

I'll use a series of pictures to demonstrate my idea:
<img src="https://user-images.githubusercontent.com/22629067/65156297-d6c91880-d9fc-11e9-8fb0-4ff08c20f1ab.png" height="100"><br>2 monitors with different brightness are synced

<img src="https://user-images.githubusercontent.com/22629067/65156321-e183ad80-d9fc-11e9-9102-de8603db3407.png" height="100"><br>You move either one, their percent difference doesn't change

<img src="https://user-images.githubusercontent.com/22629067/65156342-eba5ac00-d9fc-11e9-9912-f22f32945a12.png" height="100"><br>but once 1 reaches 100%, and if you move the slave brightness up, the sync doesn't break

<img src="https://user-images.githubusercontent.com/22629067/65156372-fceeb880-d9fc-11e9-8137-bfce7f35d00d.png" height="100"><br>and proceeds to shorten the percent difference between the 2 monitors while still in sync

<img src="https://user-images.githubusercontent.com/22629067/65156389-07a94d80-d9fd-11e9-9887-4ae95a738b60.png" height="100"><br>this means if I move the brightness for either monitor back down, they will still move in unison, even if the percent difference is smaller.

**Comment by p1ho** [comment]
It took a bit of digging, but I found the [part of the code](https://github.com/p1ho/Monitorian/commit/87a566302d64e635538db68422724e458b335d4f) that disables the unison.
If you'd like, please checkout [my fork](https://github.com/p1ho/Monitorian/tree/feature/force-unison)
It is essentially an working version of what I described above.
Thanks!

**Comment by emoacht** [comment]
Changed by d21332c9c7593eaf2f13759a711e73cdc93f2c06
I think the difference between the monitors would be better to be kept when move back.

**Comment by p1ho** [comment]
Yeah, I think that's better too. Does your change work both ways (moving both to max brightness / min brightness).

**Comment by emoacht** [comment]
Yes. it works both ways.
