### ISSUE TITLE
Request for extra low brightness 🙏 

### ISSUE THREAD

**Issue by vasileioskorompilias** [emoacht/Monitorian#523]
If possible, please add the option to go almost completely black. 

Old LCDs get this annoying ghosting gray when they show blacks, and even in the lowest brightness setting on Monitorian it makes light in the room. It is better if I also lower the contrast, but then when I return I have to adjust 2 options which I will be lazy doing all the time.

If not, it's ok.
Thx 😊

**Comment by emoacht** [comment]
The actual brightness at 0 depends on each model and won't be pitch dark. It is what they supposed to be.
