### ISSUE TITLE
Brightness value return to default after launching a game

### ISSUE THREAD

**Issue by Jordan-4** [emoacht/Monitorian#524]
Example: monitor brightness on startup is 10, I increment it to 50, i launch a game and when it goes fullscreen it just return to 10. Tried with multiple games.

**Comment by emoacht** [comment]
Interestring. So, have you identified what changes the brightness when a game starts?

**Comment by Jordan-4** [comment]
> Interestring. So, have you identified what changes the brightness when a game starts?

Sorry for the late reply but no, I didn't identify the cause. You got any idea?

**Comment by emoacht** [comment]
I guess the culprit could be a display driver utility, if any.
