### ISSUE TITLE
Unreliable Monitor Detection

### ISSUE THREAD

**Issue by JandCandO** [emoacht/Monitorian#526]
![image](https://github.com/emoacht/Monitorian/assets/4197142/941dcacb-7819-4dd7-bc6d-52df9b35a6d2)

I'm getting these error messages on my 2 monitors even though they work sometimes. It's like it's a roll of the dice every time I boot. Sometimes, they both work just fine and other times either one or both fail to work. I don't know if it's a matter of how quickly the monitors can start up themselves or what, but since it does work perfectly sometimes I don't think it's my setup.

System Specs:
Ryzen 9 5800X
Nvidia 3070 Ti
Cables are not adapters they are both DP to DP

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.
The monitor detection depends on how your monitors respond to the inquiries. Your monitors sometimes repond but sometimes don't. All up to your monitors.

**Comment by JandCandO** [comment]
Here's the probe.log: 
[probe.log](https://github.com/emoacht/Monitorian/files/12908394/probe.log)

In that hidden menu I did hit probe into monitors and rescan monitors and saw a subtle brightness change but they are still listed as uncontrollable in the menu.

**Comment by emoacht** [comment]
Thank you for the log.
Your monitors didn't respond to the inquiries of capabilities but they responded set and/or get command. So you can use `preclear` option. https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

**Comment by JandCandO** [comment]
Thank you very much, I'll follow those steps!
