### ISSUE TITLE
TypeLoadException on Windows 10 LTSC 2021 21H2

### ISSUE THREAD

**Issue by KusanagiKW** [emoacht/Monitorian#527]
Here is the error log
[exception.log](https://github.com/emoacht/Monitorian/files/13064852/exception.log)

BTW, I'm using simplified windows like Atlas OS but chinese version, Is it because of this？
![QQ截图20231023074530](https://github.com/emoacht/Monitorian/assets/93427638/1070e197-4805-4a6d-9ee8-910fe50a5552)
![QQ截图20231023074518](https://github.com/emoacht/Monitorian/assets/93427638/18c67c8a-054e-4a53-9656-cce861752569)

**Comment by KusanagiKW** [comment]
![QQ截图20231023074530](https://github.com/emoacht/Monitorian/assets/93427638/1070e197-4805-4a6d-9ee8-910fe50a5552)
![QQ截图20231023074518](https://github.com/emoacht/Monitorian/assets/93427638/18c67c8a-054e-4a53-9656-cce861752569)

**Comment by emoacht** [comment]
Thank you gor reporting.
What is your OS version?

**Comment by KusanagiKW** [comment]
> Thank you for reporting. What is your OS version?

Windows 10 LTSC 2021 21H2 (19044.2311)

**Comment by KusanagiKW** [comment]
Now I'm using Ver 4.4.6 and everything is fine but since Ver 4.4.9 it crashes（◑▽◐）

**Comment by emoacht** [comment]
Fixed by 416f66a50525aa6ba676882f66fbeb2d7ecdbf67

**Comment by KusanagiKW** [comment]
Thx a lot !!!!!!!!!!!!
