### ISSUE TITLE
Brightness settings drop when switch monitor with hdmi hub

### ISSUE THREAD

**Issue by Alex-tolch** [emoacht/Monitorian#528]
I use hdmi hub to switch between laptop and pc. When i do it - brightness settings drop on each device and i had to do set up them every time i switch. Monitorian version 4.5.0.0, windows 10.

**Comment by emoacht** [comment]
Have you checked if it only happens when this app is running? And how you set the settings of this app?

**Comment by Alex-tolch** [comment]
> Have you checked if it only happens when this app is running? And how you set the settings of this app?

I didn't check with any other app, because use only this one (i use it by default). And about setting (checked):  

- start on sign in
- use large sliders
- show adjusted brightness
- order by monitor arrangement
- enable changing adjustable range

**Comment by emoacht** [comment]
So does it happen when this app is not running?

**Comment by Alex-tolch** [comment]
> So does it happen when this app is not running?

No, if app isn't running monitor brightness settings use (this settings static and may be changed only over monitor buttons)

**Comment by emoacht** [comment]
I see. Could you run this app with making operation .log for around one hour and record the time when the issue happens and post it along with operation.log? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.

Please note that if it is caused by a mystical reason in combination with your HDMI hub, there won't be a solution.

**Comment by Alex-tolch** [comment]
[operation.log](https://github.com/Alex-tolch/operationlog/blob/main/operation.log). There you mau find two monitors: AOC2269 and XMI3444. First one connected permanently to pc with vga and and don't support your tool. Second (XMI3444) - connected to hub and uses with pc and laptop. I try change brightness on it. Logs wrote on pc. There i switched 2-3 times between pc and laptop and brightness drop to it's max value

**Comment by emoacht** [comment]
Thank you for the log.
I found when XMI3444 appeared as a controllable monitor, it's brightness was 80 or 61.  This app did nothing to change the brightness.
And I might misunderstand what you described. what do you mean by "drop to its max value"?

**Comment by Alex-tolch** [comment]
> Thank you for the log. I found when XMI3444 appeared as a controllable monitor, it's brightness was 80 or 61. This app did nothing to change the brightness. And I might misunderstood what you described. What do you mean by "drop to its max value"?

I mean next: In the settings, you can set the maximum brightness with a separate slider. For example, if I set it to 80, and remove the brightness to 50, next time I reconnect the screen, I get a brightness of 80

**Comment by emoacht** [comment]
Thank you for explanation.
But i could not find any clue about the change of brightness. Anyway it is unlikely that this app changed it.
