### ISSUE TITLE
New feature: Option to adjust according to Windows Night Light

### ISSUE THREAD

**Issue by Lars-O-Knudsen** [emoacht/Monitorian#531]
I would like adjustments to take into account the "Night Light" function in Windows.
So in day time I set one level, and for night light I have a different setting.
The change of state for night light should be observed automatically.

Thanks for a nice utility!

**Comment by emoacht** [comment]
You know your preference of time window for the night mode. So, please use task scheduler and send [command-line options](https://github.com/emoacht/Monitorian#command-line-options).
I don't know how to obtain it.
