### ISSUE TITLE
Changing brightness in unison but with different value

### ISSUE THREAD

**Issue by alexandr-vladimirov** [emoacht/Monitorian#533]
Hello!

Thank you for such a great app, really love it!
My little problem is my laptop has a very dark screen comparing to my external monitors and so usually I keep laptop screen brighter, for example, for external monitors the brightness is 0, for laptop is 25. And when I want to make all screens are little brighter in unison, I change for laptop monitor to 27 and expect other monitors will be 2, but they become also 27.
![image](https://github.com/emoacht/Monitorian/assets/5782954/fd3c47fa-ed7e-4816-9741-6bfa780f2bca)
![image](https://github.com/emoacht/Monitorian/assets/5782954/925f89be-0def-4c46-bc72-b1fb38a99015)

I think in previous versions it worked as I expected, or maybe there is some configuration I accidentally changed, but I couldn't found. 

Thank you in advance and have a nice day!

**Comment by emoacht** [comment]
The unison should be used in combination with range "Change adjustable range". Please read #427
If your internal monitor's lowest brightness which is practically usable is 25, set the lowest limit of the adjustable range to 25. Set the lowest range of external monitors as well. Then the unison will change the brightness of all monitors in the same rate.

**Comment by alexandr-vladimirov** [comment]
Ohh, it wasn't so intuitive, thanks :)
Not sure that it works as before, I have to test more for different lighting in the room. But in general seems it works well, thank you!
