### ISSUE TITLE
Change brightness in unison of notebook brightness sensor.

### ISSUE THREAD

**Issue by emoacht** [emoacht/Monitorian#537]
### Discussed in https://github.com/emoacht/Monitorian/discussions/536

<div type='discussions-op-text'>

<sup>Originally posted by **foxxxr** November 11, 2023</sup>
It could be perfect if Desktop monitor brightness will follow with notebook current brightness with sensor. It looks like you have all for that: App shows current notebook brightness position like on photo:
![image](https://github.com/emoacht/Monitorian/assets/46103829/d01b8585-2bba-4e89-aeeb-58dfcd13e602)
</div>

**Comment by emoacht** [comment]
@foxxxr Similar ideas had been discussed in previous issues. Please spare some time to search the issues.

If you use Windows 11 and auto-brightness is on, the behavior of unison which includes internal monitor could be similar with what you suggested.

**Comment by foxxxr** [comment]
I use windows 10 and hate w11 ;)
I spare much time to search solution for w10 before writing the post. 
PS your URL for discussion 536 gives 404.
