### ISSUE TITLE
Microsoft Store subscription not reflecting within app

### ISSUE THREAD

**Issue by richardvaughan25** [emoacht/Monitorian#543]
Hi,

Great software! I pulled the trigger and got subscribed so that I could use keybinds to manipulate the brightness of the monitors, but after purchasing the subscription, it does not reflect in the app. I've tried clicking Reload Subscription Information multiple times, restarte d the pc and nothing.

Can you guys help?

![MS Store Response](https://github.com/emoacht/Monitorian/assets/152636357/fbd0e7db-bbc9-44b7-a84b-c4941bd6bfa4)
![image](https://github.com/emoacht/Monitorian/assets/152636357/e17bb343-2d4f-40f9-a9ae-bd8e55512846)
![image](https://github.com/emoacht/Monitorian/assets/152636357/cdd2709e-b2af-4b07-8aac-58f660b4008d)

**Comment by emoacht** [comment]
I think it would be the issue of Microsoft Store's server which is solely managed by Microsoft.
It this issue still persists, please report again.
