### ISSUE TITLE
Monitors Turnin Off; Speaker Noise; Stripes and Wierd Colors on Monitors

### ISSUE THREAD

**Issue by PlayTics** [emoacht/Monitorian#545]
Hi there,

since i have installed the tool, my monitors are shutting down and turn on again. And this happens quient frequent. As a sideeffect, my speakers are giving noises when this happens.
I dont know whats causing this issue, and sadly i can not give any hint or other informations, tho, this are my specs:
Win 10 Pro, Nvidia Geforce GPU, GF Experience, Powertoys, WP Engine. Monitors are not old and made by 'HP'. 2 Dif, models tho.

I uninstalled the tool for the time being, but the problem is still present. It would be perfect if the cause could be fixed regarding this issue. 

I would also like to get some feedback or ideas on how to fix this problem in my system. Where any drivers installed? Have any changes been made to the registry?
What does this tool change in the system. I would like to redo or remove those changed.

With best regards,
PlayTics

Edit: While writing this, my monitors now also start getting wierd stripes and colors.
Edit 2: Aparently, the issue was... fixed. I got told to power all devices off completly (pull the plugs). Looks like the monitors stuck with something...

**Comment by emoacht** [comment]
I have no idea at all. This app will access the brightness and other settings of a monitor in a way compatible with the industry standard. If it screws a particular monitor, it should be an issue of that monitor. This app won't install a driver nor change the registry directly. To clean up any change made by this app, do factory reset.
