### ISSUE TITLE
option to sync/unison brightness in laptop (plug-in/off power)

### ISSUE THREAD

**Issue by bachig26** [emoacht/Monitorian#546]
currently the brightness reverts to the defined brightness that's been set in when power isn't plugged-in or vice versa.
i hope to see an option to make it uniform around the power change.

**Comment by emoacht** [comment]
What do you mean _reverts_ to the _defined_ brightness that's been set in when _power_ isn't _plugged-in_ and _vice versa_? It is unclear what you mean by each phrase.

**Comment by bachig26** [comment]
> What do you mean _reverts_ to the _defined_ brightness that's been set in when _power_ isn't _plugged-in_ and _vice versa_? It is unclear what you mean by each phrase.

steps:
1. like when you have set the brightness level at 40% during the laptop at power un-plugged state.
2. right after if you have changed the brightness to let's say 30% when the laptop is plugged to power.
3. now if you unplug or detach the power cable, the brightness goes back to 40% instead of staying at 30%.

i was describing this.

**Comment by emoacht** [comment]
Please make clear the power state of the laptop and external monitor. Its confusing.

**Comment by bachig26** [comment]
> Please make clear whether the power state of the laptop or external monitor. Its confusing.

laptop

**Comment by emoacht** [comment]
I still don't understand the complete picture of your setup. How you set the brightness of what monitor at step 1 while the laptop's power is off.
