### ISSUE TITLE
Issue in Gigabyte G34WQC-A

### ISSUE THREAD

**Issue by toti69o** [emoacht/Monitorian#556]
Hello,

I have an issue with the windows app. I plugged a computer to 6 external screen, in my work (I work in Datacenter). I test the free version, and it works like I hope, I decide to pay for Add-On to complete the set up but, unfortunately, the 2 external screen are Gigabyte G34WQC-A and the app works perfectly with both screen, but the brightness percent, does not save. When I try to change the brightness always appears at 100%, even when I have lowered using the app the brightness to the minimum and the brightness is still at the minimum, the application shows 100 and when I go to adjust the brightness I start from 100 and it instantly raises the brightness to 100 and it is very annoying to the eyes. I have taken a screen home, in case it was a computer adjustment, but the same thing happens.

The most curious thing is that if I do it from the keyboard shortcuts, it works perfectly and does not start from 100, but if I press on the taskbar it returns to 100, and when I click on the icon in the taskbar, for a moment it shows the % fine, but it quickly goes up to 100.

The screen is connected via displayport to a gtx-1070 gpu (max-q in the case of the laptop) and has G-sync enabled, I have tried disabling it and the same thing happens.

HDR is always disabled.

The computers have the following version of Windows: Microsoft Windows 11 Pro for Workstations 10.0.22631 N/A Build 22631
Display drivers: https://download.gigabyte.com/FileList/Driver/GIGABYTE_G34WQC_A_HDR_Drivers.zip?v=bbdac7ecc5bf88c259f2da6e83d2f216
Installed version: 1.0.0.0
Nvidia Geforce Game Ready Drivers: 546.33
Screen controller version:  31.0.15.4633

I attach the logs that the program has provided me.
Could the % brightness be forced to be saved in some way or is there an error in the logs? I've been checking, but I can't figure it out.
[operation.log](https://github.com/emoacht/Monitorian/files/13837195/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/13837196/probe.log)
https://github.com/emoacht/Monitorian/assets/55878549/24ad8986-1d10-4ed1-b2b6-960cf9555392

The application is incredible, and the aesthetics of the small controls fit perfectly with the design of Windows 11, a 10.

**Comment by emoacht** [comment]
Thank you for the logs.
According to the probe.log, G34WQC seems not responding to set brightness command as expected.

```
"GetBrightness": "Success: True, Valid: True (Minimum: 0, Current: 100, Maximum: 100)",
"SetBrightness": "Success: True, Match: False (Expected: 94, Actual: 100)"
```
The above indicates that the monitor's brightness was 100 and it did not change whereas this app tried to set it to 94.
You can confirm it by getting the probe.log several times. The brightness which this app tries to set will change each time.

Probably this is the root cause of this issue.
