### ISSUE TITLE
App will not open

### ISSUE THREAD

**Issue by Knightfaux** [emoacht/Monitorian#558]
After the latest update, the tray icon has disappeared and I cannot open the program. I've attempted to uninstall and reinstall to no avail. I've uninstalled and attempted to reinstall via the installer, command line, and Windows App store and no option is working.

**Comment by rowdenb** [comment]
I am seeing the same thing, so I don't think this is a one-off on your system @Knightfaux.

**Comment by CrisFavero** [comment]
+1  my system error log is almost identical to @rowdenb

**Comment by emoacht** [comment]
Thank you for the report.
It should be fixed by e1a5cc05e1803056d3576678060fa550c37734ae

**Comment by CrisFavero** [comment]
Installed new version. confirmed loaded. 
![image](https://github.com/emoacht/Monitorian/assets/342985/f05dddde-30d6-4704-bfb7-2b5bc28b7195)

I now have a different issue but will open a seperate issue  ticket for that later.
