### ISSUE TITLE
Show the window on a global hotkey press and hide it after x sec.

### ISSUE THREAD

**Issue by marektoman** [emoacht/Monitorian#56]
First of all, really thank you for the app.

Global hotkeys are great and work well. However, when changing small increments it takes effort to detect which monitor is active and also at what level the brightness is. The Windows brightness control (notebooks etc.) has an advantage in that it does several steps at once. It performs the increment while showing the indicator, which then disappears after the timeout.

I've tried to bypass it with AHK, but the hiding and minimizing functions somehow break the functionality until the app restarts.

The source doesn't seem to have this since it's a paid feature.

Do you consider it worth implementing?

**Comment by marektoman** [comment]
For the record, I send Alt + Esc to the window via AHK, which hides it without breaking it. That makes the issue solved on my end.

**Comment by emoacht** [comment]
Thank you for feedback.
Could you describe the behavior which you think ideal?
How long should the window remain visible if it automatically show up when the hot keys hit?

**Comment by marektoman** [comment]
I have the timeout set to 1 sec. since the last keypress, which I consider ideal.

One related challenge is that the control window doesn't have the same privilege over full screen video as the native windows overlay so the active app (e.g. game) gets minimized when the control window occurs.

If this is unsolvable, it would be great to keep the current behavior as well. That's actually how I use it right now. I use special hotkeys for my AHK script that handles the window etc. and then I use hotkeys set in the app when gaming.

**Comment by emoacht** [comment]
Try Microsoft Store version Ver 2.1.1.
I have no idea about the privilege you mentioned.
