### ISSUE TITLE
Monitor "iiyama ProLite X486S" + "ASUS PN62S" - DDC/CI commands

### ISSUE THREAD

**Issue by radio222** [emoacht/Monitorian#561]
There is such a problem, there are two identical monitors:
iiyama ProLite X486S.
Program: Monitorian 4.6.4 and below, up to Monitorian 3.10.1.0.

Computer: ASUS PN62S and ASUS UN65U.
Operating system: Windows 11.

On one of the computers:
1) ASUS PN62S with the first monitor (A) iiyama ProLite X486S
Your Monitorian program works great.
Operating system: Windows 10.

2) on another ASUS PN62S computer with a second iiyama ProLite X486S monitor
Your Monitorian program is not working.
Operating system: Windows 11.
Writes: "DDC/CI is not enabled or not supported."

3) if you turn on the first monitor (A) (ProLite X486S) with an ASUS UN65U computer running Windows 10 (1809),
then the Monitorian program works fine.

Please solve the problem in the Monitorian program with the iiyama ProLite X486S monitor on Windows 11.
Another program: ClickMonitorDDC 7.2 works great in this combination (ASUS PN62S with iiyama ProLite X486S monitor).

**Comment by radio222** [comment]
There is such a problem, there are two identical monitors:
iiyama ProLite X486S.
Program: Monitorian 4.6.4 and below, up to Monitorian 3.10.1.0.

Computer: ASUS PN62S and ASUS UN65U.
Operating system: Windows 11.

On one of the computers:
1) ASUS PN62S with the first monitor (A) iiyama ProLite X486S
Your Monitorian program works great.
Operating system: Windows 10.

2) on another ASUS PN62S computer with a second iiyama ProLite X486S monitor
Your Monitorian program is not working.
Operating system: Windows 11.
Writes: "DDC/CI is not enabled or not supported."

3) if you turn on the first monitor (A) (ProLite X486S) with an ASUS UN65U computer running Windows 10 (1809),
then the Monitorian program works fine.

Please solve the problem in the Monitorian program with the iiyama ProLite X486S monitor on Windows 11.
Another program: ClickMonitorDDC 7.2 works great in this combination (ASUS PN62S with iiyama ProLite X486S monitor).

**Comment by emoacht** [comment]
In the second case, probably there would be a hardware issue.
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.

**Comment by radio222** [comment]
I'll send it as you requested
[probe.log](https://github.com/emoacht/Monitorian/files/14008370/probe.log)

**Comment by radio222** [comment]
The file was created on another computer and a similar monitor iiyama ProLite X486S monitor on Windows 10 running Monitorian 4.6.4: 
[probe.log](https://github.com/emoacht/Monitorian/files/14008474/probe.log)

**Comment by emoacht** [comment]
Thanks fo the logs.
The first probe.log clearly indicates that your PLX486S is not capable of DDC/CI. According to the datasheet PLX486S, that model is compatible with DDC/CI. So I guess DDC/CI is disabled for your monitor or there is any issue in the connector or cable.

**Comment by radio222** [comment]
For the experiment, I installed absolutely working three new HDMI cables for ASUS PN62S to the iiyama ProLite X486S monitor, the result is the same in Windows 11, does not work with Monitorian 4.6.4.

What’s interesting is that if I plug in this seemingly problematic iiyama ProLite X486S monitor with the same HDMI cable into another ASUS UN65U computer model (video card: Intel(R) HD Graphics 620) with Windows 10, then the Monitorian 4.6.4 program works fine.

I think that the problem is in the Monitorian 4.6.4 program when connecting the ASUS PN62S between slightly different monitor models:
1) iiyama ProLite X486S
And
2) iiyama ProLite X486 (without S index).

The HDMI connectors to the monitor are fully working in the ASUS PN62S, since this problem exists on similar ASUS PN62S computers (tested on three more absolutely identical new ASUS PN62S models) and the result is the same in conjunction with the iiyama ProLite X486S monitor (with index S), to Unfortunately, Monitorian 4.6.4 does not work in conjunction with ASUS PN62S.
But, again, the same iiyama ProLite X486S monitor (with index S) and another ASUS UN65U computer and the Monitorian 4.6.4 program fully works, which means it fully supports “DDC/CI”.

I am sending a log file from the same, seemingly problematic iiyama ProLite X486S monitor when connected to an ASUS UN65U with Windows 10 + Monitorian 4.6.4, where everything works without problems.

Once again, if the ASUS PN62S computer (with Windows 11) is connected to another monitor: ProLite X486 (without the S index),
then the Monitorian 4.6.4 program works fine.
Miracles.

I am sending additional log files and characteristics of two monitors:
1) iiyama ProLite X486S
And
2) iiyama ProLite X486 (without S index).
Perhaps they will help you figure out the problem.

[Intel(R) UHD Graphics - ASUS PN62S.txt](https://github.com/emoacht/Monitorian/files/14014351/Intel.R.UHD.Graphics.-.ASUS.PN62S.txt)
[probe - Monitorian = Work Ok (iiyama ProLite X486 + ASUS PN62S).log](https://github.com/emoacht/Monitorian/files/14014352/probe.-.Monitorian.Work.Ok.iiyama.ProLite.X486.%2B.ASUS.PN62S.log)
[Report - iiyama ProLite X486 (ENG) + ASUS PN62S.txt](https://github.com/emoacht/Monitorian/files/14014353/Report.-.iiyama.ProLite.X486.ENG.%2B.ASUS.PN62S.txt)
[Report - Intel(R) HD Graphics 620 (Monitor Iiyama ProLite X486S) + ASUS UN65U.txt](https://github.com/emoacht/Monitorian/files/14014354/Report.-.Intel.R.HD.Graphics.620.Monitor.Iiyama.ProLite.X486S.%2B.ASUS.UN65U.txt)
[Report - Intel(R) UHD Graphics - Iiyama ProLite X486 + ASUS PN62S.txt](https://github.com/emoacht/Monitorian/files/14014355/Report.-.Intel.R.UHD.Graphics.-.Iiyama.ProLite.X486.%2B.ASUS.PN62S.txt)
[Report - Monitor Iiyama ProLite X486S + ASUS UN65U.txt](https://github.com/emoacht/Monitorian/files/14014357/Report.-.Monitor.Iiyama.ProLite.X486S.%2B.ASUS.UN65U.txt)

Thank you for your attention.

**Comment by emoacht** [comment]
Thank  you for the logs again.
However, it is clear that unless your monitor responds to the DDC/CI commands as expected, nothing this app can do.

**Comment by radio222** [comment]
How then, if this monitor iiyama ProLite X486S (No. 1) works perfectly with Monitorian 4.6.4 when connected to ASUS UN65U, which means it supports “DDC/CI”.

As I wrote to you above, ClickMonitorDDC 7.2 also works great in this combination (ASUS UN65U and ASUS PN62S) with the iiyama ProLite X486S monitor (No. 1).
