### ISSUE TITLE
App randomly unpins from system tray

### ISSUE THREAD

**Issue by Jordan-4** [emoacht/Monitorian#571]
As I said in the title, i have the icon pinned in the system tray or notification area call it whatever you want, and sometimes it unpins itself. Any way to fix it?

**Comment by emoacht** [comment]
Thank you for reporting.
Then, when exactly you have noticed it? Please indicates exact date and version.

**Comment by Jordan-4** [comment]
there isn't an exact date or moment, I just turn on the pc and sometimes the icon isn't there anymore. I didn't find any particular behaviour. For the version it's 4.6.11.0 download from the microsoft store.

**Comment by emoacht** [comment]
I have updated the Microsoft Store version several times recently. Perhaps you have noticed it.

**Comment by cguinnup** [comment]
According to the detailed comment below, Windows will keep system tray icons pinned between installations into different paths if the app is code signed and uses an icon GUID in addition to the uID: 
https://github.com/electron/electron/pull/21891#issue-555005746

**Comment by emoacht** [comment]
@cguinnup Thank you for the information.
I guess the GUID in question refers to guidItem of [NOTIFYICONDATAA](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataa) structure but it is not utilized in NotifyIcon.

**Comment by emoacht** [comment]
At this moment, it is not technically solvable unless major change of this project. I don't think it is worth for such major change.
