### ISSUE TITLE
Internal monitor (laptop display) shows only after repluging external display

### ISSUE THREAD

**Issue by Ponywka** [emoacht/Monitorian#574]
I use dual monitor setup (laptop display + external display)
Internal display shows only when I unplug external display (and then works fine after replug)

https://www.youtube.com/watch?v=hvJ2h5_4L4Q

[probe_before_replug.log](https://github.com/emoacht/Monitorian/files/14429331/probe_before_replug.log)
[probe_after_replug.log](https://github.com/emoacht/Monitorian/files/14429332/probe_after_replug.log)

**Comment by emoacht** [comment]
Thank you for the logs.
In the first log, your system did not report the information on the internal monitor for one of queries from this app. Unless the system reports on the monitor, there is nothing this app can do.

**Comment by emoacht** [comment]
I have rarely heard about the case where internal monitor is not controllable and thus I bet there would be an hardware issue.

**Comment by Ponywka** [comment]
Today I got this. Don't look to the monitor connected via DP (because it's VGA converter), I'm talk about internal display. The program shows internal monitor is not controllable (but I can control them via "Settings")
![image](https://github.com/emoacht/Monitorian/assets/26777464/ebce188f-ef81-4ea6-962e-f59b2489ef7c)
