### ISSUE TITLE
When the taskbar is on the left side, the interface does not display correctly at the bottom left corner, but appears at the top left corner and cannot be dragged. Please fix it.

### ISSUE THREAD

**Issue by hinum009** [emoacht/Monitorian#576]
ver4.6.0.1

**Comment by emoacht** [comment]
I cannot reproduce it.

**Comment by hinum009** [comment]
> I cannot reproduce it.
win11 22H2 22621.1555
startallback 3.6.5
My guess is that Monitorian doesn't recognize the startallback's taskbar width and length correctly.

**Comment by emoacht** [comment]
I see. I don't know that tool and have no plan to adopt to it.
