### ISSUE TITLE
Feature request: Add the ability to customize common brightness and contrast levels.

### ISSUE THREAD

**Issue by hinum009** [emoacht/Monitorian#577]
It would be more convenient to switch by clicking on the system tray icon.

**Comment by emoacht** [comment]
What is "common" brightness and contast?

**Comment by hinum009** [comment]
> What is "common" brightness and contast?

It's the ability to customize a few gears so that you don't overpull easily

**Comment by hinum009** [comment]
I had no choice but to change from ClickMonitorDDC to Monitorian before I switched to Win11, because the software stopped being maintained and often had compatibility issues. Quite a powerful program, it's a bit of a shame that it's been discontinued. Mouse operation has a lot of very convenient habits hard to let go. I hope I can learn from it.

**Comment by emoacht** [comment]
I don't still understand what this table means. Could you describe what kind of behavior are you expecting this app to do?

**Comment by hinum009** [comment]
> I don't still understand what this table means. Could you describe what kind of behavior are you expecting this app to do?

![image](https://github.com/emoacht/Monitorian/assets/29087287/a403bded-cebc-4b76-a0d2-ec52b3227c0b)
Simply add some gears to the slider that can be adjusted between gears. Now it's easy to overdrag this way with a smooth drag. For example, brightness 55 contrast 45 in daytime mode, brightness 46 contrast 42 in nighttime mode. Now the "Adjustment range" is only valid for brightness, not for contrast.

**Comment by emoacht** [comment]
What do you mean by "gears"? And how do they relate to "overdrag" "with a smooth drag"?
What do you intend to show by the examples?

**Comment by hinum009** [comment]
> What do you mean by "gears"? And how do they relate to "overdrag" "with a smooth drag"? What do you intend to show by the examples?

Sorry, English sucks." gears" means scale or level, the slider is hard to adjust precisely, and the mouse wheel adjusts in multiples of 5, so it's hard to adjust it to a value like 52 or 47.
Probably the easiest and simplest way to achieve this is to apply the "Adjustment Range" to the contrast adjustment as well.

**Comment by hinum009** [comment]
![image](https://github.com/emoacht/Monitorian/assets/29087287/b6749a64-0a92-4bdb-92c9-04997392f624)

**Comment by emoacht** [comment]
Thank you for explanation.
I read though your comments but I could not understand exactly what you are expecting.
So I am sorry but I close this issue.
