### ISSUE TITLE
Default Brightness and contrast

### ISSUE THREAD

**Issue by emoacht** [emoacht/Monitorian#583]
### Discussed in https://github.com/emoacht/Monitorian/discussions/582

<div type='discussions-op-text'>

<sup>Originally posted by **odaialdajani** April  7, 2024</sup>
Hello i would like to set the default values of my monitorian to set all monitors to 55 brightness and 55 contrast, how would achieve tha!
</div>

**Comment by emoacht** [comment]
What do you mean by "default values"? What kind of behavior are you expecting? Please elaborate it.

**Comment by odaialdajani** [comment]
I would like to propose an enhancement regarding default settings in Monitorian. Currently, upon PC startup, users need to manually adjust brightness and contrast settings for their monitors. My suggestion is to implement default settings that automatically apply each time Monitorian launches.

For example:

Set default brightness for all monitors to 50.
Set default contrast for all monitors to 90.
By saving these settings as defaults, users would no longer have to readjust their screens every time they start their PC. This change would significantly improve usability and save time.

I hope this clarifies my request. Please feel free to ask if you need any further information.

Thank you for your attention to this matter!

Best regards, Odai
