### ISSUE TITLE
Brightness is not adjustable on MSI PRO MP243X

### ISSUE THREAD

**Issue by free-gen** [emoacht/Monitorian#584]
There is no DDC item in the monitor settings. Changing the slider does not change the brightness. But value always displays correctly. That is, if in the monitor settings the brightness = 70, then in Monitorian the scale is always set to 70. 
This means that the program somehow receives this value, but for some reason does not send other value. Can this be fixed? Or does my monitor just not support DDC?

**Comment by free-gen** [comment]
In ECO mode the program started working. But there is no access to contrast settings.

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__?  How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.
