### ISSUE TITLE
Cmd Get Set Load

### ISSUE THREAD

**Issue by Jack74r** [emoacht/Monitorian#585]
Hi
I'm trying to use the /get /set command and set up /load time to have automatic scheduled times. 
So I've added to the global variables 
I run in cmd
C:\Program Files (x86)\Monitorian>
monitorian /set all +10

But this just opens Monitorian but do nothing

The get doesn't return any value.

I'm in version 4.6 (latest readme version)

How does get or set work, can I use / load time on 4.6?

Thanks

**Comment by emoacht** [comment]
Hi, what is the version?
Commands by command-line options are, as indicated in readme, parts of add-on features of Microsoft Store version.
FYI, the path is not necessary when sending command.
