### ISSUE TITLE
DEFAULT SETTINGS

### ISSUE THREAD

**Issue by odaialdajani** [emoacht/Monitorian#587]
It would greatly improve user experience if there were default settings established for the PC, so that upon startup, these settings are automatically applied without the need for manual adjustments each time. This would streamline the process and save time for users who frequently find themselves configuring the same settings. Additionally, it seems that this message has been written multiple times, indicating a recurring issue or concern. Establishing default settings could potentially address this frustration and enhance the overall usability of the system.

**Comment by odaialdajani** [comment]
FOR BOTH CONTRAST AND BRIGHTNESS!!!!

**Comment by odaialdajani** [comment]
INSTEAD OF MANUALLY ADJUSTING EACH TIME PC LAUNCHES!

**Comment by emoacht** [comment]
I have already asked you about what do you mean by "default values" and what kind of behavior are you expecting. You are expected to explain about them.

**Comment by odaialdajani** [comment]
I would like to propose an enhancement regarding default settings in Monitorian. Currently, upon PC startup, users need to manually adjust brightness and contrast settings for their monitors. My suggestion is to implement default settings that automatically apply each time Monitorian launches.

For example:

Set default brightness for all monitors to 50.
Set default contrast for all monitors to 90.
By saving these settings as defaults, users would no longer have to readjust their screens every time they start their PC. This change would significantly improve usability and save time.

I hope this clarifies my request. Please feel free to ask if you need any further information.

Thank you for your attention to this matter!

Best

**Comment by emoacht** [comment]
Let's use this issue to discuss.

Thank you for the explanation.
If you want to set brightness and contrast when this app starts, this app already has command-line options (a part of add-on features) usable for such purpose. Open the hidden menu and put the following text in "Command-line Arguments".

```
/set brightness all 50 /set contrast all 90
```

That's it.

Besides that, some points are still unclear to me.

- Why you need such function in the first place? The most people want to keep the last settings when they stop using PC and resume with the same settings. There would be no need to "reset" the settings.

    *  You share your PC with other people and don't like the settings by other people?
    *  Your kids screw up your PC in the night time and so you need to "restore" the settings when you start working in the morning?
    *  You frequently change brightness in the day and so want to "reset" anyway when you start a new day in the morning? 

- The most people don't restart PC daily. They just suspend and resume PC. Thus a function which performed only when this app starts is not so useful.
- This app should "reset" a monitor when it is connected or turned on after this app starts? In addition, some monitors are "slow starter" and might not be ready (controllable) when this app starts even if they are already connected to PC. This app cannot "reset" such monitors if it try to do only when it starts. In addition, some monitors often change their state between controllable and uncontrolable while the change is rarely noticed by the user. If this app "reset" such monitors when they turn to be controllable, they are "reset" seemingly recklessly by this app. Therefore, it is not easy to define the exact conditions to "reset".

Thinking about these things, I am guessing that a function to perform "reset' at scheduled time in the day could suffice such as time command which recently added to this app.

**Comment by odaialdajani** [comment]
Thank you for your detailed response and for providing the command-line options. I appreciate your efforts to address my concerns.

To clarify, I'm not familiar with setting up brightness and contrast through command-line options. Could you please provide some guidance on how to implement these commands?

Regarding your inquiries:

1. This PC is solely used by me, so there's no issue with others tampering with settings.
2. Each time I start my PC, I find that the brightness and contrast settings revert to default, requiring me to readjust them manually. This occurs despite having set them previously.
Considering your points about the usage patterns of most users, I understand the rationale behind not implementing a default reset feature. However, in my case, having to redo the settings upon each startup is inconvenient and time-consuming.

Could you please advise on how to address this issue? Your assistance would be greatly appreciated.

Thank you once again for your attention to this matter.

Best regards,
Odai

**Comment by emoacht** [comment]
Thank you for the explanation.
I have already explained how to set the command-line option when this app starts.

> Open the hidden menu and put the following text in "Command-line Arguments".
> /set brightness all 50 /set contrast all 90

If you are interested in time command, please read [Time Commands](https://github.com/emoacht/Monitorian/blob/master/docs/COMMANDS.md#time-commands)

> Each time I start my PC, I find that the brightness and contrast settings revert to default

You may try "Restore brightness on reconnection" in Microsoft Store version. It is only for the brightness  though.

**Comment by emoacht** [comment]
See [Probe](https://github.com/emoacht/Monitorian#probe)

**Comment by odaialdajani** [comment]
Happy days I found it and I have entered this text in it
/set brightness all 55 /set contrast all 70

however I couldn't find the submit button i press enter it enters a new line I press anywhere else nothing happens, what do I do after having the text written inside the hidden menu text box, how do I get it to submit?
![image](https://github.com/emoacht/Monitorian/assets/77544618/def2b262-6922-479f-8b38-eca7922715fa)

**Comment by emoacht** [comment]
The text in this text box is treated as command-line arguments when this app starts.

**Comment by odaialdajani** [comment]
I did exactly that hit the close button re-opened Monitorian and unfortunately this is the result
![image](https://github.com/emoacht/Monitorian/assets/77544618/5b10e69d-f6dd-4a65-9ee2-0d6f555f9aa4)


when in fact this was the prompt 
![image](https://github.com/emoacht/Monitorian/assets/77544618/bc3bc254-0225-42b8-9d5e-0b5b158bf065)

**Comment by emoacht** [comment]
Could you open command prompt and type in the following and hit return?

```
monitorian /set brightness all 50 /set contrast all 90
```
What is shown?

**Comment by odaialdajani** [comment]
![image](https://github.com/emoacht/Monitorian/assets/77544618/755d3590-f98c-4d83-a3a0-d8f1b1bca4d3)

nothing happens so I press anywhere on the screen to close the menu nothing happens, I close monitorian and reopen it nothing happens, something is not right it seems! does it need updating?

**Comment by odaialdajani** [comment]
Quick Update

I uninstalled the version I had installed from the web, and installed the one from the Microsoft store, and glad to say it works brilliantly and also has the restore on reconnection - Thank you so much for all your support and assistance! Now its a brilliant experience!
