### ISSUE TITLE
Monitorian without admin priviledges ?

### ISSUE THREAD

**Issue by jlhervy** [emoacht/Monitorian#590]
Hello, 

I would like to install monitorian in for my user on the windows PC that I use at work. However I do not have administrator permissions, and monitorian asks for them. 

Are they mandatory ? Would there be a way to install/modify monitorian such that it doesn't require those rights ?

Thanks,

**Comment by emoacht** [comment]
This app doesn't require administrator permissions.
If you are asked, it could be other reason such as the policy.

**Comment by SigmaTel71** [comment]
The installer does as its installation defaults to `C:\Program Files (x86)\`, but you can unpack the installer with any archiver, e.g. 7-Zip can handle Windows Installer packages. You need to extract these files and put them somewhere, then launch the executable like you would do normally.
<details>![image](https://github.com/emoacht/Monitorian/assets/17989678/3c4f7a99-b318-44cf-98ed-4cfa39b050df)</details>

**Comment by jlhervy** [comment]
Thanks ! 

Indeed it did work, but not with 7z. 
I used the msiexec windows command to extract the .msi in my user space, and I can now launch monitorian. 

Thanks for your help.

**Comment by gr4v1ty69** [comment]
I ahve tried but get an error
![image](https://github.com/user-attachments/assets/40820557-fa57-4705-b057-bd3d4add9f0f)

**Comment by AndreyLalaev** [comment]
@gr4v1ty69, not sure if it is still relevant, but MSI file should be in a different directory (not in the same you are unpacking it to). For example:
`msiexec.exe /a C:\Users\user\Downloads\Monitorian.Installer.msi /qb TARGETDIR=C:\Users\user\Monitorian`
