### ISSUE TITLE
With update 4.6.12.0, contrast on external monitor is reset to "0" on boot and wake up from sleep

### ISSUE THREAD

**Issue by ddiggles** [emoacht/Monitorian#591]
Just noticed this behavior today.

Version 4.6.12.0, if my screens or computer go to standby / sleep / power off, upon resuming (or awakening monitor by moving mouse), the contrast on my external monitor goes to 0.  I'm having to manually set it back to where I want it every time.

Windows 11 Pro, MS store version.  External monitor connected thru DP from USB-C hub (into laptop)

EDIT: doesn't seem to be every time.  But has happened twice so far.

**Comment by emoacht** [comment]
Than you for reporting.
Have you enabled "Restore brightness on reconnection"?

**Comment by ddiggles** [comment]
Yup I do have that enabled.

I didn't have "enable adjusting contrast" checked before.  I enabled it so I could quickly adjust back if it went to 0 (without using monitor OSD).  Since enabling, the issue hasn't presented itself again - however still monitoring (he he).

**Comment by githubyouser** [comment]
I'm seeing the exact same problem. At first I was afraid something was wrong with my monitor, but after disabling Monitorian and power cycling the monitor, all was well. Thanks to @ddiggles I realized what the issue was, and now I can reset the contrast in Monitorian instead of taking such drastic measures. :)

**Comment by emoacht** [comment]
This issue is due to loading previous data when the user has enabled "Restore brightness on reconnection" before Ver 4.6.12.
Once the contrast is adjusted, it should not happen again.
Ver 4.6.13 which fixed this issue for the time being is out.
