### ISSUE TITLE
Brightness show 100 after closing windows

### ISSUE THREAD

**Issue by kkazzakov** [emoacht/Monitorian#592]
I have Redmi g24 external monitor on my laptop. The program works great, but when i set brightness on my external monitor and closing window it shows brightness level 100 on external monitor, even though it's not

**Comment by emoacht** [comment]
What do you mean by _closing window it shows brightness level 100 on external monitor_?
You closed this app's window? How you can read it?

**Comment by kkazzakov** [comment]
![screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024 05 10-16_37_40](https://github.com/emoacht/Monitorian/assets/29127138/b6d48066-20e6-4a8c-80bf-cd333e248c24)

**Comment by emoacht** [comment]
Your monitor seems uncontrollable.
If you want to investigate your monitor's issue, could you post __probe.log__? How to produce that logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.
