### ISSUE TITLE
Compatible Ambient Light Sensors?

### ISSUE THREAD

**Issue by AJolly** [emoacht/Monitorian#593]
Any idea where I can buy or build an ambient light sensor that all work with this for a desktop? Any idea where I can buy or build an ambient light sensor that will work with this for a desktop?

For some reason it's been incredibly hard to find anything, I'm happy to For some reason it's been incredibly hard to find anything, I'm happy to even build something with an ESP if that's what I need to do

**Comment by emoacht** [comment]
Please edit your post. Otherwise, I will delete it.

**Comment by AJolly** [comment]
I'd be happy to edit it, but what needs changing, or what would be a better place to ask this q?

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md).
I recommend at least removing duplicated sentences and add explanations.
