### ISSUE TITLE
Couldn't control display, even though supported DDC/CI.

### ISSUE THREAD

**Issue by HumanMus1c** [emoacht/Monitorian#598]
Displays
X41Q
Name: X41Q
Internal name: HKC230C
Communication Method: DDC/CI
Current Brightness: 100
Max Brightness: 100
Brightness Normalization: 0-100

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) in readme.

**Comment by HumanMus1c** [comment]
[probe.log](https://github.com/user-attachments/files/15578862/probe.log)

**Comment by emoacht** [comment]
Thank you for probe log. Could you post __operation.log__ as well?

**Comment by HumanMus1c** [comment]
"Please wait for the run log to record more information."
