### ISSUE TITLE
change contrast in unison

### ISSUE THREAD

**Issue by robflushing** [emoacht/Monitorian#601]
can you add to change the contrast in unison. would be very handy.

**Comment by emoacht** [comment]
Have you read https://github.com/emoacht/Monitorian/issues/279#issuecomment-1015520134 ?

**Comment by robflushing** [comment]
Hadnt seen the comment. But figured i couldnt be the first. Love
monitorian. Use it daily. Well i dare to ask🤣. Thank you for your reply.
Should you code it in the future i would be a grateful user.😘

Op vr 21 jun. 2024 20:16 schreef emoacht ***@***.***>:

**Comment by robflushing** [comment]
Already asked and answered
