### ISSUE TITLE
Brightness slider does not show up

### ISSUE THREAD

**Issue by Jaksonas** [emoacht/Monitorian#604]
What the title says. When I click on the icon in the tray, only the name of my monitor pops up, but no slider at all. What could be the problem?
<img width="269" alt="Screenshot 2024-07-13 024010" src="https://github.com/user-attachments/assets/9e38334e-4bd9-41cc-883a-009dbf04a05d">

**Comment by emoacht** [comment]
Thank you ro reporting.
What is your OS version?
And could you post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by Jaksonas** [comment]
Thanks for answering so quickly. Posting below. 
[probe.log](https://github.com/user-attachments/files/16200340/probe.log)

**Comment by Jaksonas** [comment]
> Thanks for answering so quickly. Posting below. [probe.log](https://github.com/user-attachments/files/16200340/probe.log)

Sorry, forgot to mention my OS, it is Win 11, 23H2 (build 22631.3880)

**Comment by emoacht** [comment]
Thank you for the log and OS information.
Are you using any tool which manipulates the taskbar of desktop?

**Comment by Jaksonas** [comment]
Yes, I am, Start11. You think it is possible to run together with it?

Linkėjimai/ Kind regards,

Vilius

**Comment by emoacht** [comment]
Most probably. That kind of tool may mess up the elements inside the taskbar. I cannot reproduce it though.

**Comment by Jaksonas** [comment]
Maybe some particular settings in Start11 that causes this? There are a lot of settings, some quite unintuitive to reach.

Linkėjimai/ Kind regards,

Vilius

**Comment by emoacht** [comment]
It is possible.

**Comment by emoacht** [comment]
Could you run a console app to check the windows on the desktop and post the result?
The code of the app is shown in the gist https://gist.github.com/emoacht/6b38452df693493f967f29c965684f81

**Comment by Jaksonas** [comment]
Hello, again, I managed to fix it: I just lowered the taskbar's size (width). Now a slider pops up normally, when I click on you program. However, I would like to use a wider taskbar like before together with Monitorian. Think you could adjust the code?

Linkėjimai/ Kind regards,

Vilius

**Comment by emoacht** [comment]
What is "wider" taskbar? I think a Taskbar can be taller but cannot be wider.
Anyway, I don't know what is happening and so I asked to run the console app.

**Comment by Jaksonas** [comment]
Yes, sorry, meant taller (in Start11 the setting is called 'width').

Ok, so, what exactly do I do when opening the console? Copy something? I am not exactly savvy in this area, sorry.

Linkėjimai/ Kind regards,

Vilius

**Comment by emoacht** [comment]
Run it and the result wil be shown. You can redirect the output to a file 
```
[path of console app] > [path of file to redirect]
```

And please stop posting by email.
