### ISSUE TITLE
Change Refresh Rate using the application

### ISSUE THREAD

**Issue by WyvernCoder** [emoacht/Monitorian#605]
From my perspective, adding this option is a good idea.

My laptop has always enabled power saving mode, and the refresh rate will be set to the lowest rate. 

It won't be recovered after plugging in. 

![image](https://github.com/user-attachments/assets/1b7e1c44-b513-4409-bdae-92a687d2613c)

**Comment by emoacht** [comment]
Thank you for the suggestion.
But technically, I have no idea on how to get available refresh rates of a specific monitor.

**Comment by emoacht** [comment]
I have researched ways to get refresh rates with a video controller and a specified monitor combination, but have not found any.
If you find it, please let me know.
