### ISSUE TITLE
Stopped working, crashes

### ISSUE THREAD

**Issue by dzid26** [emoacht/Monitorian#610]
<img width="291" alt="image" src="https://github.com/user-attachments/assets/4d4f0269-b421-4497-a472-f234cb52eb44">

[exception.log](https://github.com/user-attachments/files/16332359/exception.log)
Based on log message, I guess I disabled some service?  But it doesn't say which one.

**Comment by emoacht** [comment]
Thank you for reporting.
This error (0x80070422) seems to be raised when WMI service cannot be started.

Two questiions:
1. Have you disabled WMI service?
2. Your PC is laptop?

**Comment by dzid26** [comment]
Yes, I had the WMI disabled because it keeps using between 0-5% cpu which adds to overall constant CPU usage and laptop heating. 

After enabling WMI and restarting Windows, Monitorian started to work again.

**Comment by dzid26** [comment]
That explains why I was getting only external monitor control in Twinkle app! Hah.

Maybe it would be wise to try/catch missing WMI and indeed just control external monitors in that case. 

I hate WMI cpu usage with HP laptop with HP drivers. I hate Intel 11th gen and Windows too. (It burns my skin.)

Anyway, thanks, for the interesting input.
