### ISSUE TITLE
Add-on Features not loading after the payment

### ISSUE THREAD

**Issue by kalilmd** [emoacht/Monitorian#611]
Hello There,

I already paid for the subscription. It's showing on my Microsoft store. But the app won't load the features even after restarting or re-load commands.

Is there anything I need to do to get the features I paid for with the subscription?

Thanks

![Screenshot 2024-07-23 093709](https://github.com/user-attachments/assets/333a70a9-3cbe-4b72-beea-1b4c5df1b90a)
![Screenshot 2024-07-23 093930](https://github.com/user-attachments/assets/ca77738e-b9c7-4c13-a3e0-2de4ae5ab9e2)
![Screenshot 2024-07-23 094026](https://github.com/user-attachments/assets/adf092e3-a25c-4239-9be6-270e04e8d996)

**Comment by emoacht** [comment]
No action is necessary after the purchase.
Said that, I have no idea how long it will take for the Microsoft Store server to reflect the status on the responses of API that this app relies. It is under the sole control of Microsoft.

**Comment by kalilmd** [comment]
> No action is necessary after the purchase. Said that, I have no idea how long it will take for the Microsoft Store server to reflect the status on the responses of API that this app relies. It is under the sole control of Microsoft.

Is there anything I can do to contact Microsoft support about this? Or should I just wait and wait, and if nothing happens cancel the subscription?

**Comment by emoacht** [comment]
Clicking "Reload subscription infortmation" or uninstalling and re-installing this app may make a difference.
Other than that, it is up to you.
