### ISSUE TITLE
Any idea support external BLE HID Light Sensor with external monitor only

### ISSUE THREAD

**Issue by qdsp6sw** [emoacht/Monitorian#612]
I bought a light sensor that can be clipped directly onto an external monitor.
It communicates with the computer via Bluetooth and can be identified as a HID light sensor, so its brightness value can be obtained simply using 
`LightSensor.GetDefault().GetCurrentReading()`
However, since the brightness of the external monitor cannot be directly controlled by Windows, the automatic brightness of Windows cannot be used directly. I would like to ask if the following software has the opportunity to support the automatic brightness of this sensor?

**Comment by emoacht** [comment]
I have no plan. In the first place, the way how the adaptive brightness works is somehow complicated. See [Adaptive brightness](https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/sensors-adaptive-brightness). So you can get the value from a sensor (it may report the change of value very often) and then you will face the challenge of how to use the value taking into account the characteristics of that sensor.

Having said that, you can develop a tool which sends commands to this app to set brightness (add-on features of Microsoft Store version).
