### ISSUE TITLE
Monitorian Can't Detect Dell Monitors

### ISSUE THREAD

**Issue by KaiLi0114** [emoacht/Monitorian#614]
Hi emoacht,

I'm using Monitorian to adjust the brightness of 4 monitors. Monitorian can successfully detect my LG and another portable monitor, but can't detect my 2 Dell monitors (DELL S2721QS and DELL SE3223Q). I'm sure DDC/CI is enabled, .NET 4.8 installed and I'm running a Windows 11. I went through your intro page and believe that Dell monitors should have no problem to be detected. Would you mind giving me any suggestions on how to fix the problem? Thank you and have a great day!

Best regards,
Kai

**Comment by emoacht** [comment]
I guess it is related to connector or hub. if any.
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and [Detection of external monitors](https://github.com/emoacht/Monitorian#detection-of-external-monitors) and then post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by KaiLi0114** [comment]
Hi emoacht,
Thank you so much for your prompt reply. Yeah, I'm using two DP to HDMI converters for my Dell monitors and I think it's because the converters don't support DDC/CI. 
Have a great day!
Best,
Kai
