### ISSUE TITLE
Brightness shortcut keys not working in-app (gaming fullscreen)

### ISSUE THREAD

**Issue by Jaksonas** [emoacht/Monitorian#616]
Hello,

Is there any reason why shortcut keys are not working while gaming fullscreen?

Also, what is the difference between system-wide and in-app keys?

Thanks.

**Comment by emoacht** [comment]
Hot keys (usable system-wide) can be used even if this app is not shown as long as this app is running. Only one app can use a specific hot key combination at a time.
Shortcut keys (usable inside app) can be used only if the app is shown and acticated.

**Comment by Jaksonas** [comment]
Ok, thanks, I see. 

And any reason why none of the combinations are working while gaming?

**Comment by emoacht** [comment]
I have no idea but I have read about game programs that disable the hot keys of other apps.
