### ISSUE TITLE
Monitor Chiq CH32F600 Incorrect percentages in brightness and contrast changes

### ISSUE THREAD

**Issue by YK-SNM** [emoacht/Monitorian#618]
Hello! The program works but the brightness goes up to level 89 and at 90 it goes down to 0% brightness.
With the contrast at level 0 and 1 it is at 100%. When I go up from level 2 to 17 it goes up gradually to 100% and at 18 to 0% contrast again. I upload the probe.log.
[CH32F600 probe.log](https://github.com/user-attachments/files/16630623/CH32F600.probe.log)

**Comment by emoacht** [comment]
Thank you for reporting and the log.
The log indicates the maximum brightness of your monitor is 100. So, if you cannot set the brightness to 100 as you witnessed, it must be quite strange and there is something weird happening in your monitor. The same goes for the contrast.

**Comment by Yashimaru-snm** [comment]
It's weird what happens. In the brightness level 0 of the program shows 20% in the monitor's OSD and goes up by 1% until level 100 reaches show 182% in the OSD. With the contrast level 1 of the program shows 224% in the OSD and goes up 16% each level. If I make these changes manually with the monitor buttons they change from 0 - 100% as they should.
It works anyway and is more comfortable to use than the monitor buttons.

I upload the logs to levels 0 and 100, although they show that the values ​​in GetBrightness are correct.

Thanks for taking the time to review it.

[0% probe.log](https://github.com/user-attachments/files/16799428/0.probe.log)
[100% probe.log](https://github.com/user-attachments/files/16799430/100.probe.log)

**Comment by emoacht** [comment]
Thank you for the logs.
Your monitor is really weird and I do not think there would be something this app can do.
So, I close this issue.
