### ISSUE TITLE
Allow decreasing of monitor brightness using percentage button

### ISSUE THREAD

**Issue by Kaedin** [emoacht/Monitorian#62]
Hi Dev,

This is actually a feature request than an issue but I'd like to propose following:

Currently, if user clicks the button where screen brightness percentage is shown with LMB, the brightness is increased by 10%. It would be nice to have a counteraction for this e.g. that the brightness would be decreased by the same amount when clicking the button with RMB.

![image](https://user-images.githubusercontent.com/26382655/69831187-f4063880-1230-11ea-8fe1-820e143512f3.png)

Thank you for your consideration!

Best regards,
Kaedin

**Comment by emoacht** [comment]
Thank you for you suggestion.
First, do you have any particular reason to introduce such behavior?
Second, left and right mouse buttons have each specific meaning.
Third, the behavior that left mouse button to increase - go right in slider and right mouse button to decrease - go left in slider are confusing.

**Comment by Kaedin** [comment]
First: It would just be nice to have a counteraction to the already available LMB functionality.
- This can be achieved by going beyond 100% with LMB click after which the brightness returns to 0% but it isn't nice to browse through the whole scale.
- This can be achieved by using the scrollbar either drag and release or adjusting via mouse scrolling. However, I personally find both of those previous methods pretty "uncomfortable" to use because you cannot really adjust the value with precision and the screen reflects to the adjustment awkwardly.
-> It's just much more enjoyable, faster and reliable to perform the adjustment via press of a button because the output is more predictable. E.g. I can estimate that 2 clicks result in a 20% brightness adjustment. While performing the same via dragging or scrolling, it always depends on the accuracy of your mousehand.

Second: Currently, performing LMB on the indicator rectangle is bound to increase brightness via 10%.
-> There seems to be no actions triggered when performing RMB as above. Is there something which would conflict with this binding?

Third: I'm not saying that these bindings would be obvious. LMB is usually linked to toggling something and I couldn't think of any other good way to quickly and effortlessly performing a counteraction to LMB functionality than RMB.
-> Maybe you'd have a better suggestion? :)

**Comment by emoacht** [comment]
Thank you for explanation.
However, I would say using right mouse button for this purpose is bad idea. It definitely contradicts most users' expectation and confusing as I already wrote. Simple and easily understandable UI is this app's priority. Adding bad UI is worse than nothing.
Unless any good idea coming out, I close this issue.
