### ISSUE TITLE
Cintiq 16 unrecognised

### ISSUE THREAD

**Issue by Dprasni** [emoacht/Monitorian#620]
Seems like the app doesn't recognise my Cintiq 16, i don't have this issue with similar apps

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by Dprasni** [comment]
[probe.log](https://github.com/user-attachments/files/16912992/probe.log)
Here you go.

**Comment by emoacht** [comment]
Thank you for the log.
The capabilities that your monitor (Cintiq 16) responded do not include the capability for luminance and thus it is regarded as uncontrollable.
On the other hand, your monitor responded to a command for luminance. So you may use `/preclear` option. See https://github.com/emoacht/Monitorian/issues/270#issuecomment-998347584

**Comment by Dprasni** [comment]
Worked, thanks 👍
