### ISSUE TITLE
Mouse cursor stuttering & lagging on every Windows unlock & Monitorian launch after enabling iGPU & installing Intel iGPU drivers

### ISSUE THREAD

**Issue by wwwjj2** [emoacht/Monitorian#622]
I was using Monitorian for years and it's been totally fine. I used only my GTX 1060, no iGPU enabled. Until I enabled iGPU in BIOS and installed iGPU drivers from Intel website.

Now every time Monitorian is launched, I get crazy mouse cursor stuttering on every Windows unlock or every time I launch monitorian. It lasts for about 10-15 seconds.

During the lagging, the CPU usage by Monitorian increases. Exiting monitorian fixes the issue. Seems like a conflict with Intel Grapics Drivers?

Theres'a a video I've recorded that illustrates the issue (its 30 FPS but the difference is quite noticable, I think. At least to my eyes its really stuttering, a lot of mouse cursor lagging): https://github.com/user-attachments/assets/83a8ff0c-1d1d-4ebd-b4a0-a748429bd251
Or YouTube: https://youtu.be/u5ixia07tFg

I tried deleting intel graphics command center (leaving the drivers itself intact), rebooted and it didn't help.

Monitorian version 4.7.0.0, tried both Windows Apps version & msi Installer.

Specs: i7-8700K with Intel® UHD Graphics 630, GTX 1060 (6GB), 48 GB RAM, Windows 10 Pro 22H2

**Comment by emoacht** [comment]
Does it happen if this app starts on sign in and this app's menu or window is not shown yet?

**Comment by wwwjj2** [comment]
> Does it happen if this app starts on sign in and this app's menu or window is not shown yet?

I've just checked it rebooting my PC, and yes, it happens in any case, even if you never open the app's menu. It always happens in about 5 seconds after every sign in (from powering the PC on, from Signing out & then signing in, from locking Windows & signing in), and lasts for about 10 to 15 seconds. It also happens with every launch of Monitorian after fully closing it (same story: 5 seconds of delay -> start of stuttering which lasts 10-15 seconds). Is there any way to capture logs or whatever to try to find the cause?

**Comment by emoacht** [comment]
You can get __operation.log__.  How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme. But I don't know it could help.
This app calls a number of APIs when it starts. I have no idea which cause the issue at all.

**Comment by nthnlws** [comment]
Also having this same stuttering issue on Monitorian 4.7.5.0.

Specs: i7-10700 with Intel® UHD Graphics 630, RTX 3060Ti, 32 GB RAM, Windows 11 23H2

**Comment by wwwjj2** [comment]
> You can get **operation.log**. How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme. But I don't know it could help. This app calls a number of APIs when it starts. I have no idea which API causes the issue.

So, I've reproduced the issue multiple time while recording the operation log. But I guess it doesn't say much: [operation.log](https://github.com/user-attachments/files/17254380/operation.log)

**Comment by emoacht** [comment]
Could you turn off "Transparency effects" in the OS's settings of Personalization > Colors and check if it makes any difference?

**Comment by nthnlws** [comment]
Changing setting did not change lag.

**Comment by emoacht** [comment]
I close this issue for now. I don't think there would be something this app can do.
