### ISSUE TITLE
Monitorian is not Starting on Computer Startup

### ISSUE THREAD

**Issue by seriaati** [emoacht/Monitorian#623]
I am using a laptop, the OS is Windows 11, I can provide more hardware details if needed.
The Monitorian app is not starting up when the laptop is booted, it also does not appear in the "startup items" section of the task manager.
I have tried the "repair" session in the Monitorian installer, did not help.

**Comment by emoacht** [comment]
Did you checked "Start on sign in"?

**Comment by seriaati** [comment]
🤦 Sorry, didn't notice that you can right click on it.
