### ISSUE TITLE
Command Line Stopped Working

### ISSUE THREAD

**Issue by Draghmar** [emoacht/Monitorian#625]
Hi
I'm using Monitorian (4.7.5.0) to set brightness based on HA events where additional tool launches CMD with payload to set brightness based on external lux sensor. This all worked fine but yesterday it stopped for some reason. I checked Monitorian manually and it doesn't work. I still can click on systray and change brightness there using slider. But when trying to do things like `/get all` for example, I'm getting empty result.
```
PS C:\Users\***\AppData\Local\Microsoft\WindowsApps> .\Monitorian.exe /get all

PS C:\Users\***\AppData\Local\Microsoft\WindowsApps>
```

**Comment by lawrencefoley** [comment]
@Draghmar I had the same issue. Uninstalling it and then [re-installing it via `winget`](https://github.com/emoacht/Monitorian?tab=readme-ov-file#download) resolved the issue for me.
Not sure if there was a Windows update or something that broke something. 🤷 

```shell
winget install Monitorian -s msstore
```

**Comment by ewersp** [comment]
Noticed the same issue here recently. The fix from @lawrencefoley worked, thanks!

**Comment by davewatson91** [comment]
I just updated to 4.8.0, and found that the CLI stopped working. It appears that the executable at `C:\Users\***\AppData\Local\Microsoft\WindowsApps\Monitorian.exe` is no longer present. I installed via WinGet similarly, and the executable in AppData returned (with the updated version).

**Comment by magcode** [comment]
[https://github.com/Crozzers/screen_brightness_control](https://github.com/Crozzers/screen_brightness_control) is a good, free alternative if its really just about command line monitor brightness control.
