### ISSUE TITLE
[REQUEST] Sync Brightness/contrast

### ISSUE THREAD

**Issue by Pbroc** [emoacht/Monitorian#626]
Hi,

Would it be possible to add an option to enable the ability to slide the brightness cursor alone and at the same time modify the contrast to have the exact same value than the brightness? 

Thanks

**Comment by emoacht** [comment]
Thank you for the suggestion. But in most cases, the optimal value of contrast for a specific value of brightness won't match the value of the brightness. Let's say, when the brightness is 50, the optimal contrast might be 30 or 40 or 60 depending on each monitor and each user. So I don't think a feature to sync brightness and contrast is useful in practice.

I do understand the demand to automatically adjust the contrast when the brightness is changed. In such case, [Conditional command](https://github.com/emoacht/Monitorian/blob/master/docs/COMMANDS.md#conditional-commands) (add-on feature of Microsoft store version) would be useful. Settings the whole set of commands could be cumbersome but it offers the maximum flexibility.

**Comment by Pbroc** [comment]
Yeah I know, but in my case, my monitor output frame at higher speed when the brightness match the contrast (mouse cursor way smoother), of course it's an edge case I understand.

Meanwhile I've find a way to do it using Windows shortcuts on the desktop, target field:

C:\Users\username\AppData\Local\Microsoft\WindowsApps\Monitorian.exe /set contrast 20 /set 20
C:\Users\username\AppData\Local\Microsoft\WindowsApps\Monitorian.exe /set contrast 50 /set 50

And so on...

It's a bit diy, but that work nicely
