### ISSUE TITLE
Monitor reboot

### ISSUE THREAD

**Issue by Bribbo38** [emoacht/Monitorian#628]
I just installed Monitorian and I can adjust my second monitor just fine (an old HP Compaq) but my main (Samsung odyssey G5) just randomly reboot, when I get back my second screen it shows that it's disconnected and after a moment it connects back.

Both monitor are connected to my 4070 super with Display Port. And I have all the latest driver (if they make a difference)

Edit: I just notice that my main monitor goes from 0 to 50, but Monitorian show 0-100, I don't know if it can be a problem

**Comment by emoacht** [comment]
Thank you for reporting.
But I have no clue on this. It seems to be a hardware issue.
