### ISSUE TITLE
Monitor brightness reset after monitor restart/refresh rate change/g-sync state change

### ISSUE THREAD

**Issue by Devocub** [emoacht/Monitorian#63]
After monitor restart/refresh rate change/g-sync state change brightness of display goes back to value set inside of display by OSD. However if i change it from monitorian it shows correct value in OSD but seem to be not saved. So proposal - force monitorian brightness after scan/rescan. Also maybe smooth transition?

**Comment by emoacht** [comment]
I don't really understand the situation. Could you elaborate more?
In general, the change set by this app is persistent.

**Comment by Devocub** [comment]
1. Set brightness to, for example, to 30% from monitor OSD menu
2. Run monitorian and change it to 100%
3. Turn off -> turn on display, or change refresh rate, or enable/disable g-sync
4. Monitor brightness is back to 30% (monitorian also shows 30%)

It's not bug, it just how monitor works. And it can be easily fixed I guess.

**Comment by emoacht** [comment]
Thank you for explanation.
It is difficult because this app cannot tell whether the brightness change is caused as a side effect of changing those settings or it is done intentionally by the user from the monitor's OSD menu.
As far as I know, there is no technical solution. So I close this issue.

**Comment by Devocub** [comment]
> It is difficult because this app cannot tell whether the brightness change is caused as a side effect of changing those settings or it is done intentionally by the user from the monitor's OSD menu.

You definitely can distinguish the things.
  
  
I fixed it by adding 2 lines of code at https://github.com/emoacht/Monitorian/blob/master/Source/Monitorian.Core/AppControllerCore.cs#L194
```c#
// Check if brightness has changed and return it to our values
if (oldMonitor.Brightness != item.Brightness)
    item.SetBrightness(oldMonitor.Brightness);
```

**Comment by emoacht** [comment]
To be clear, I am not talking about the difference of brightness itself but the reason which causes such difference.
