### ISSUE TITLE
[REQUEST] Poweroff button

### ISSUE THREAD

**Issue by maurirope** [emoacht/Monitorian#632]
Hello my friend from the interwebs, your software very nice!!! Feel very blessed to be user, so simple yet so wonderful, easy life, easy change brightness spinn the wheeeeeel.

now is it a possible thing that maybe cna be achieved to have power off button also? what do you think about it ?

**Comment by emoacht** [comment]
Please read https://github.com/emoacht/Monitorian/issues/436 and https://github.com/emoacht/Monitorian/issues/398
