### ISSUE TITLE
Slider hidden behind windows taskbar

### ISSUE THREAD

**Issue by prounlocks** [emoacht/Monitorian#634]
Happened on win 10 22H2
After load i see only header "monitorian",  and slider control hidden

**Comment by prounlocks** [comment]
![image](https://github.com/user-attachments/assets/91c7a97b-f08d-4d00-a5d2-64624eddf7fd)

**Comment by emoacht** [comment]
It is suggested that there is no monitor reachable by this app.

Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.
