### ISSUE TITLE
[Request] Polling brightness in unison mode

### ISSUE THREAD

**Issue by seungw-choo** [emoacht/Monitorian#635]
Hi, first of all, thank you all for this great app. I am using two monitors support DDC/CI, enjoying this app a lot!
One suggestion to add auto refresh (polling) to get brightness info from one monitor that supports auto brightness and apply it to another monitor(s)
My main monitor supports auto brightness feature and I really enjoy this feature (dell U4025QW) But one another monitor does not.
So when I put unison mode in the app, and when I manually click and activate the app, two monitors' brightness are synchronized.

Here is current situation:
So when brightness changes (becoming bright), 
1. Main monitor will boost brightness, while my second doesn't
2. When I click the Monitorian and when context menu is activated, my second monitor also would boost brightness

It would be nice if Monitorian itself can retrieve brightness info from main monitor every few time (<1s) and apply that to non-auto brightness monitor(s)

Thanks!

**Comment by emoacht** [comment]
Thank you for suggestion.
I always wanted to avoid polling.
To consider the possibility, could you post probe.log? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by seungw-choo** [comment]
Sorry for not responding it back. I tried to generate the log but I could not able to make it. (The reporting manual you gave me was hard to understand for me)
Is 'completed' mean that the feature is implemented in the latest realse?

**Comment by seungw-choo** [comment]
[operation.log](https://github.com/user-attachments/files/17798768/operation.log)
[probe.log](https://github.com/user-attachments/files/17798769/probe.log)

Hi, here is the log you requested.
I think there was a bug in generating logs.
Could you consider implementing the feature?

**Comment by emoacht** [comment]
Thank you for the log.
What I am particularly interested in is VCP code 66. It is there but I cannot understand its value. Need further research.

**Comment by emoacht** [comment]
I forgot to mention.
Could you elaborate why you think _there was a bug in generating logs_?

**Comment by seungw-choo** [comment]
When I clicked 'make operation log' or 'probe into monitors', something did seemed to be happened. But right after when I clicked copy log, it did nothing.
Few days later, I tried it again and I could copy log to the desktop. I don't know what caused this bug.
