### ISSUE TITLE
Restart Button

### ISSUE THREAD

**Issue by p1ho** [emoacht/Monitorian#64]
Hello, sometimes when I swap monitor when my laptop is asleep messes with monitor detection. A simple fix is restarting the program, but the workflow is a bit cumbersome.

I was wondering if it's possible to add a restart button in the right click menu.
(Maybe right above "CLOSE")

Thanks!

**Comment by emoacht** [comment]
Thank you for the suggestion.
However, I don't support adding Restart button because such thing has to be solved without restarting. I am interested in how log does it take to be stable after the resume in your case in order to think about fine-tuning of rescan intervals after the resume.

**Comment by p1ho** [comment]
Thanks for the quick reply!

I just tested (unplug and plug). the new monitor shows up in about 5-7s after the 2nd monitor starts displaying. I think maybe I was just impatient and thought the program stopped working.

Feel free to close. If I catch the issue again where it doesn't show up after a long time, I can try to gather more information.

**Comment by emoacht** [comment]
I see.
In such case, display settings change event will be fired and then this app is expected to rescan 3 times, namely 1, 5, 10 seconds after that event. The exact timing varies depending on the time for each scan. If it takes longer than 10 seconds, one more rescan might be necessary.

**Comment by p1ho** [comment]
I think the 3 rescans are fine. If the rescan after 10 seconds doesn't work, I think a lot of users might just assume the program stopped working, and would restart it. That said, I've paid more attention to the timing now, so far it's working as designed.

**Comment by emoacht** [comment]
Thank you for the update.
I close this issue. If you find any further update, feel free to post again.

**Comment by emoacht** [comment]
If this issue happens again, try Ver 2.4.0 with making operation log as described in readme. The operation log would provide much better information to track what really happens.

**Comment by p1ho** [comment]
Will do, thank you! Knowing the refresh rates, it has been working fine for me
