### ISSUE TITLE
Typo in Resources.resx

### ISSUE THREAD

**Issue by Sopor** [emoacht/Monitorian#643]
https://github.com/emoacht/Monitorian/blob/9a5dd177a4549b65293a1046d22c932c3d0c9305/Source/Monitorian.Core/Properties/Resources.resx#L142

I only want to tell you that `operation` is misspelled.

I also think you should change the `Close` to `Quit` (maybe even Quit Monitorian) because that will mislead users thinking that it will close the menu, but instead it will quit the application.

**Comment by emoacht** [comment]
Thank you for reporting.
The typo is fixed in e271eaf5912bf1a59ded867017d30281343369e0
Regarding the word of close, it it opinon-based.
