### ISSUE TITLE
Apply ngen to installer

### ISSUE THREAD

**Issue by MagicAndre1981** [emoacht/Monitorian#653]
It would be nice if you could [ngen MonitorianPlus.exe after setup](https://wixtoolset.org/docs/v3/howtos/files_and_registry/ngen_managed_assemblies/) to improve performance.

**Comment by emoacht** [comment]
Microsoft Store version does not use WiX.
And in most times, this app waits for the response from external monitors. If you feel this app is slow, it means that your monitors are slow.

**Comment by MagicAndre1981** [comment]
it is not really slow for me, but I want all .net apps to be ngened . Maybe update to .net9 and [use AOT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=windows%2Cnet9plus) 🤔

**Comment by emoacht** [comment]
If migrated to .NET, the download size of this app will become a hundred times bigger (this is not an exaggeration).
Since the practical benefit from the migration would be negligible, there is no compelling reason for it.

**Comment by emoacht** [comment]
Applied NGen to installer of standard version by 6dc4152d1dfc25802ba7e289516c86382042f212

**Comment by MagicAndre1981** [comment]
thanks. Got the update installed with winget and yes the exe is ngened during setup 👍

**Comment by emoacht** [comment]
To be clear, the version which is installed by winget is Microsoft Store version.

**Comment by MagicAndre1981** [comment]
no, it is the normal [installer version](https://github.com/microsoft/winget-pkgs/blob/ab367fd6f693885880d0e50da4722c8bcf76cf51/manifests/e/emoacht/Monitorian/4.10.0/emoacht.Monitorian.installer.yaml#L18) and I saw that ngen was called from msiexec.exe

**Comment by emoacht** [comment]
I see. I have not noticed that. It is not under my control.
