### ISSUE TITLE
Opening the panel slider will automatically reset

### ISSUE THREAD

**Issue by a81n9** [emoacht/Monitorian#656]
Each time you open the panel slider value, it will be reset, and the screen brightness display is normal

https://github.com/user-attachments/assets/ff23a255-b453-4fff-be86-2a130614e469

**Comment by emoacht** [comment]
Does your monitor's brightness actually change when you move the slider?
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__ and __operation.log__? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by a81n9** [comment]
Yes, my screen brightness does change.
When I reopen the panel, the slider will be reset but the screen brightness is not reset.

https://github.com/user-attachments/assets/2c61b9ff-5823-4056-afb1-b9a6bce02938

```
[Date: 2024/11/26 8:13:26 Ver: 4.9.1.0]
{
  "System": "Manufacturer: Dell Inc., Model: Vostro 3881, OS: 10.0.19045.0",
  "Device Context - DeviceItems": [
    {
      "DeviceInstanceId": "DISPLAY\\PHLC306\\4&29418c43&0&UID198203",
      "Description": "Generic PnP Monitor",
      "DisplayIndex": 1,
      "MonitorIndex": 0
    }
  ],
  "DisplayMonitor - DisplayItems": [
    {
      "DeviceInstanceId": "DISPLAY\\PHLC306\\4&29418c43&0&UID198203",
      "DisplayName": "PHL 241V8LB",
      "NativeResolution": {
        "_height": 1080,
        "_width": 1920
      },
      "PhysicalSize": {
        "_height": 11.653543472290039,
        "_width": 20.748031616210938
      },
      "PhysicalDiagonalLength": 23.7967625,
      "IsInternal": false,
      "ConnectionDescription": "HDMI"
    }
  ],
  "Display Config - DisplayItems": [
    {
      "DeviceInstanceId": "DISPLAY\\PHLC306\\4&29418c43&0&UID198203",
      "DisplayName": "PHL 241V8LB",
      "IsInternal": false,
      "RefreshRate": 59.94006,
      "ConnectionDescription": "HDMI",
      "IsAvailable": true
    }
  ],
  "Device Installation - InstalledItems": [
    {
      "DeviceInstanceId": "DISPLAY\\PHLC306\\4&29418C43&0&UID198203",
      "Description": "通用即插即用监视器",
      "IsRemovable": true
    }
  ],
  "Monitor Configuration - PhysicalItems": [
    {
      "Key": {
        "DisplayIndex": 1,
        "MonitorRect": "Location:0,0, Size:1920,1080"
      },
      "Value": [
        {
          "Description": "Generic PnP Monitor",
          "MonitorIndex": 0,
          "Capability": {
            "IsHighLevelBrightnessSupported": false,
            "IsLowLevelBrightnessSupported": true,
            "IsContrastSupported": true,
            "IsPrecleared": false,
            "CapabilitiesString": "(prot(monitor)type(LCD)model(241V8)cmds(01 02 03 07 0C E3 F3)vcp(02 04 05 08 0B 0C 10 12 14(01 04 05 06 07 08 0A 0B) 16 18 1A 52 54(00 01) 60(01 11) 62(00 01) 6C 6E 70 72(05 78 FB 50 64 78 8C A0) 86(02 08) 87 8D(00 01) AC AE B2 B6 C0 C6 C8 CA(01 02) CC(01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 12 14 16 17 1A 1E 24) D6(01 04 05) DC(00 01 05 0B 0E E3) DF E9(00 02) EB(00 01 02 03) F0(00 01) FD FF)mswhql(1)asset_eep(40)mccs_ver(2.2))",
            "CapabilitiesReport": "Luminance: True, Contrast: True, Temperature: True, Input Source: True, Speaker Volume: True, Power Mode: True",
            "CapabilitiesData": null
          },
          "GetBrightness": "Success: True, Valid: True (Minimum: 0, Current: 0, Maximum: 100)",
          "SetBrightness": "Success: True, Match: False (Expected: 13, Actual: 0)",
          "GetContrast": "Success: True, Valid: True (Minimum: 0, Current: 50, Maximum: 100)",
          "SetContrast": "Success: True, Match: True (Expected: 70, Actual: 70)"
        }
      ]
    }
  ],
  "MSMonitorClass - DesktopItems": [ ],
  "ElapsedTime": [
    "DeviceItems    -> 0.014",
    "DisplayMonitorItems -> 0.013",
    "DisplayConfigItems -> 0.013",
    "InstalledItems -> 0.012",
    "PhysicalItems  -> 7.361",
    "DesktopItems   -> 0.117"
  ]
}
```

**Comment by a81n9** [comment]
> Thank you for the log. Could you post operation.log as well?

Yes, I can.
It currently prompts me `Wait for more information to be recorded to operation log.`

**Comment by a81n9** [comment]
Sorry, because I didn’t use it during this time, I forgot about this ...
I will test for a few more days, and I will provide you with `operation.log` soon afterwards

**Comment by a81n9** [comment]
> @a81n9 I think you should able to copy operation.log already.

[Date: 2024/12/5 8:10:48 Ver: 4.9.1.0]
Enabled

[Date: 2024/12/5 8:12:21 Ver: 4.9.1.0]
ScanAsync [2024/12/5 8:12:11]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,1920,1080,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": 0,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2024/12/5 8:45:37 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionLock 0)

[Date: 2024/12/5 8:46:23 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Dimmed 0)

[Date: 2024/12/5 8:46:28 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Dimmed 1)

[Date: 2024/12/5 8:46:33 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Dimmed 2)

[Date: 2024/12/5 8:46:35 Ver: 4.9.1.0]
ScanAsync [2024/12/5 8:46:28]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": Empty,
      "IsInternal": false,
      "IsReachable": false,
      "IsBrightnessSupported": false,
      "IsContrastSupported": false,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": 0,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2024/12/5 8:46:39 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Off 0)

[Date: 2024/12/5 8:50:07 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher On 0)

[Date: 2024/12/5 8:50:11 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 0)

[Date: 2024/12/5 8:50:12 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher On 1)

[Date: 2024/12/5 8:50:16 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 1)

[Date: 2024/12/5 8:50:17 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher On 2)

[Date: 2024/12/5 8:50:18 Ver: 4.9.1.0]
ScanAsync [2024/12/5 8:50:12]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,1920,1080,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": 0,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2024/12/5 8:50:21 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 2)

[Date: 2024/12/5 8:50:24 Ver: 4.9.1.0]
ScanAsync [2024/12/5 8:50:21]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,1920,1080,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": 0,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2024/12/5 9:02:03 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionLock 0)

[Date: 2024/12/5 9:02:49 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Dimmed 0)

[Date: 2024/12/5 9:02:54 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Dimmed 1)

[Date: 2024/12/5 9:02:59 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Dimmed 2)

[Date: 2024/12/5 9:02:59 Ver: 4.9.1.0]
OnMonitorAccessFailed
Status: DdcFailed
Message: Low level, Code: -1071241847, Message: An operation failed because a DDC/CI message had an invalid value in its command field.


[Date: 2024/12/5 9:02:59 Ver: 4.9.1.0]
ScanAsync [2024/12/5 9:02:54]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": Empty,
      "IsInternal": false,
      "IsReachable": false,
      "IsBrightnessSupported": false,
      "IsContrastSupported": false,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 4,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2024/12/5 9:03:04 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher Off 0)

[Date: 2024/12/5 9:20:06 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher On 0)

[Date: 2024/12/5 9:20:10 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 0)

[Date: 2024/12/5 9:20:11 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher On 1)

[Date: 2024/12/5 9:20:15 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 1)

[Date: 2024/12/5 9:20:16 Ver: 4.9.1.0]
OnMonitorsChangeInferred (PowerWatcher On 2)

[Date: 2024/12/5 9:20:17 Ver: 4.9.1.0]
ScanAsync [2024/12/5 9:20:11]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,1920,1080,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": 0,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

[Date: 2024/12/5 9:20:20 Ver: 4.9.1.0]
OnMonitorsChangeInferred (SessionWatcher SessionUnlock 2)

[Date: 2024/12/5 9:20:26 Ver: 4.9.1.0]
ScanAsync [2024/12/5 9:20:20]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
      "Description": "PHL 241V8LB",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "MonitorRect": 0,0,1920,1080,
      "IsInternal": false,
      "IsReachable": true,
      "IsBrightnessSupported": true,
      "IsContrastSupported": true,
      "IsPrecleared": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1,
      "Contrast": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\PHLC306\4&29418c43&0&UID198203",
        "Description": "PHL 241V8LB",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "MonitorRect": 0,0,1920,1080,
        "IsInternal": false,
        "IsReachable": true,
        "IsBrightnessSupported": true,
        "IsContrastSupported": true,
        "IsPrecleared": false,
        "Brightness": 0,
        "BrightnessSystemAdjusted": -1,
        "Contrast": -1
      },
      "Name": "PHL 241V8LB",
      "IsUnison": false,
      "IsControllable": true,
      "IsConfirmed": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

**Comment by emoacht** [comment]
Thank you for the logs.
Your monitor always return 0 in response to the command to query the brightness. It is the cause of the issue and your monitor seems to have something wrong.

**Comment by a81n9** [comment]
> Thank you for the logs. Your monitor always return 0 in response to the command to query the brightness. It is the cause of the issue and your monitor seems to have something wrong.

My display model is: PHILIPS PHLC306 PHL241V8LB(24 -inch)

The slider is reset each time the panel is reopened, but the brightness of the display is not reset, and dragging the brightness of the slider display will still change

**Comment by a81n9** [comment]
> So your monitor always returns false value (0) when this app sends a command to report the brightness. This app cannot handle such monitor. That is what is happening now.

Thank you for your reply
