### ISSUE TITLE
Brightness change smoothing

### ISSUE THREAD

**Issue by 1LyRa** [emoacht/Monitorian#657]
Hi!

I have a Xiaomi G34WQI and app works fine for changing its brightness, but I noticed that brightness changes in steps, which is not visually appealing (my laptop monitor on the other hand changes brightness smoothly).

Is it possible to implement some brightness change smoothing in the app or is it my monitor limitation?

**Comment by emoacht** [comment]
It sounds like your monitor's issue.
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__ and __operation.log__? How to produce these logs is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by 1LyRa** [comment]
[operation.log](https://github.com/user-attachments/files/17914024/operation.log)
[probe.log](https://github.com/user-attachments/files/17914026/probe.log)

Logs attached.
Also I recorded video to show what I'm talking about (laptop monitor on the bottom, external on the top).
You can see that laptop monitor goes to target brightness going through all brightness levels before that, but external monitor jumps straight to target brightness.

https://github.com/user-attachments/assets/f6fb0d5b-6e9c-4b35-9df5-636a4e30f984

**Comment by emoacht** [comment]
Thank you for the logs.
Then, are you changing the value by hot keys?

**Comment by 1LyRa** [comment]
In the video I change value with mouse scroll wheel, but usually I use light sensor in my laptop or Windows brightness slider (and sync this to external monitor using Unison function of Monitorian).

**Comment by emoacht** [comment]
The lenght of a step for a notch of mouse wheel is 5. It is normal in the case of standard version.

**Comment by emoacht** [comment]
The length of a step per mouse wheel is specific to this app. It is intentional and not due to hardware limitation.

If you drag the slider thumb by mouse or touch, you can move it from 0 to 100 very quickly. But in the case of mouse wheel, if the lenght of a step is, let's say 1, you will need to roll the wheel 100 notches to move 0 to 100. It is why the length of a step is set to 5.

**Comment by 1LyRa** [comment]
Sorry, I don't understand why do we still talk about mouse wheel, as I said before, the behavior is the same even when I set brightness with ambient light sensor.

**Comment by emoacht** [comment]
Okay so you no longer has a question on this app.

**Comment by 1LyRa** [comment]
So you can't/won't add an artificial smoothing option to the app?
