### ISSUE TITLE
MSI Monitor request

### ISSUE THREAD

**Issue by Lncvrt** [emoacht/Monitorian#658]
I have a MSI G32CQ4 and it doesn't seem to work with this app. My MSI G241 does work though.

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md) and post __probe.log__? How to produce the log is explained in [Reporting](https://github.com/emoacht/Monitorian#reporting) section of readme.

**Comment by emoacht** [comment]
Perhaps I guess your monitor had a bad connection or so.

**Comment by emoacht** [comment]
I have no idea What are you talking about.
