### ISSUE TITLE
Icon Redesign

### ISSUE THREAD

**Issue by BlueCricket971** [emoacht/Monitorian#661]
The current Monitorian icon feels a bit inconsistent and could benefit from a more uniform design. Perhaps a refreshed icon with a cleaner look that could fit more seamlessly with Windows’ UI style? It’d be great to see an update that makes it more visually appealing! From a design perspective the un-aligned rectangles shining out make it fee a little un-polished. Just a thought, it be great to see a new icon. 

![image](https://github.com/user-attachments/assets/8e7207b2-cf66-46cf-9927-1082d65b204c)

**Comment by emoacht** [comment]
What point do you think the icon is inconsistent? Please elaborate it.
The main purpose of the icon of this app is to be shown in the notification area. It must be as less blurry as possible at 16x16 size.

**Comment by BlueCricket971** [comment]
I think that the little bars shining out should be better aligned with each other, symmetrically. Also uniform in size, some are thicker, shorter, thinner, they are all different sizes.

**Comment by emoacht** [comment]
Have your ever draw a pixel art of 16/x16 size?

**Comment by emoacht** [comment]
Have your ever draw a pixel art of 16x16 size?
You cannot draw a line of 1 thickness at the horizontal and vertical center because the width and height is not odd number.

**Comment by BlueCricket971** [comment]
You don't have to painstakingly draw it by hand in a 16 x 16 format. Draw in a comfortable size and downscale it to 16 x16, that's worked plenty of times for me and the icons still look good.

**Comment by emoacht** [comment]
You don't understand the main purpose of this icon and the way to avoid blurry lines.
I close this issue.
