### ISSUE TITLE
Whole area for mouse wheel control

### ISSUE THREAD

**Issue by ionGL** [emoacht/Monitorian#662]
If "enable changing contrast" is not enabled, could adjusting the brightness with the mouse wheel when the cursor is anywhere in the monitor's whole box be an improvement?
You would not have to place the cursor on the line for the wheel control to activate.

**Comment by emoacht** [comment]
What do you mean "the monitor's whole box"?

**Comment by ionGL** [comment]
The whole monitorian window. If you would move the wheel over the monitor name or wherever inside this box, changing the value should be easier. Right now the cursor must be on the line or very close to it.
![box](https://github.com/user-attachments/assets/e39ba71c-5155-44af-aeca-60d34fdde567)

**Comment by ionGL** [comment]
With multiple monitors, the detection point would be the line between them. Once the curser is anywhere in the monitor's window, the wheel would change brightness
![box](https://github.com/user-attachments/assets/3ddae9f2-eac4-46ec-b0d8-ae37c97ef9de)
.

**Comment by emoacht** [comment]
Thank you for the explanation.
But the the area is too large. I increased the backrgound height of slider in b181bbdc36355226c398fa5f37a3aea9aa4ba10f
