### ISSUE TITLE
Rename Monitor

### ISSUE THREAD

**Issue by bachig26** [emoacht/Monitorian#664]
Add an option to rename the default monitor name appears in the Monitorian to an custom one.

**Comment by emoacht** [comment]
Could you read [Contributing Guidelines](https://github.com/emoacht/Monitorian/blob/9aeb4238af22c60ccc03051f144edd1a5ee9acdb/CONTRIBUTING.md)?
See [Remarks](https://github.com/emoacht/Monitorian/tree/9aeb4238af22c60ccc03051f144edd1a5ee9acdb?tab=readme-ov-file#remarks).
