### ISSUE TITLE
App doesn't show the monitors

### ISSUE THREAD

**Issue by sutr90** [emoacht/Monitorian#67]
When I start the application I get an icon in the tray area, which allows me to open the context menu:
![ctx-menu](https://user-images.githubusercontent.com/1327101/71977069-2d5e9a80-3218-11ea-8f49-4697a1b7c927.png)

The application itself doesn't show at all. I can only see the app title:
![main](https://user-images.githubusercontent.com/1327101/71977109-48c9a580-3218-11ea-9c78-2c0b3094ecf1.png)

I have two monitors connected and I'm using Intel integrated graphics card. The Intel command center application shows that both monitors support DDC:
![dipslay1](https://user-images.githubusercontent.com/1327101/71977251-9a723000-3218-11ea-970d-27d1adb66248.png)

![display2](https://user-images.githubusercontent.com/1327101/71977272-a6f68880-3218-11ea-9b48-cdace3f7a05c.png)

Other applications to communicate using DDC doesn't work as well. All show that no DDC capable display is connected.

Does it mean that Monitorian will not work?

**Comment by emoacht** [comment]
Thanks for your report.
Your monitors are Lenovo T24i-10? According to the manual, they seem to support DDC/CI.
First of all, I would recommend if the DDC/CI function is on.
Then, check the log section of readme and post scan log and operation log. They will give some information on what is happening to these monitors.

**Comment by sutr90** [comment]
I did not found a way to enable the logging. Triple click on the app title did not work for me. So I have fired up VS2019 a debugged the application.

This is in the `operation.log`:
```
[Date: 09.01.2020 9:59:07 Ver: 2.4.0.0]
Initiated

[Date: 09.01.2020 9:59:07 Ver: 2.4.0.0]
ScanAsync [09.01.2020 9:59:07]
{

}

[Date: 09.01.2020 10:05:15 Ver: 2.4.0.0]
OnMonitorsChangeInferred (DisplayWatcher)

[Date: 09.01.2020 10:05:15 Ver: 2.4.0.0]
ScanAsync [09.01.2020 10:05:15]
{

}
```

I have then debugged further, and here are the results of the relevant parts of code:
`DisplayInformation.cs#95`
```
var devices = await DeviceInformation.FindAllAsync(DisplayMonitor.GetDeviceSelector(), new[] { deviceInstanceIdKey });
```
returns 0 items

After that I have disabled the Win10 version detection and run the detection with following results:
`DeviceContext.cs#246`
In the first for cycle it correctly enumarates 3 devices:
```
 | display | {Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE} | Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE
  | DeviceID | "" | string
  | DeviceKey | "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Video\\{B5706605-591A-11E8-85F9-82A5C6FC946D}\\0000" | string
  | DeviceName | "\\\\.\\DISPLAY1" | string
  | DeviceString | "Intel(R) HD Graphics 630" | string
  | StateFlags | DISPLAY_DEVICE_ACTIVE | Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE_FLAG
  | cb | 424 | uint

 | display | {Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE} | Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE
  | DeviceID | "" | string
  | DeviceKey | "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Video\\{B5706605-591A-11E8-85F9-82A5C6FC946D}\\0001" | string
  | DeviceName | "\\\\.\\DISPLAY2" | string
  | DeviceString | "Intel(R) HD Graphics 630" | string
  | StateFlags | DISPLAY_DEVICE_ACTIVE \| DISPLAY_DEVICE_PRIMARY_DEVICE | Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE_FLAG
  | cb | 424 | uint

 | display | {Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE} | Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE
  | DeviceID | "" | string
  | DeviceKey | "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Video\\{B5706605-591A-11E8-85F9-82A5C6FC946D}\\0002" | string
  | DeviceName | "\\\\.\\DISPLAY3" | string
  | DeviceString | "Intel(R) HD Graphics 630" | string
  | StateFlags | 0 | Monitorian.Core.Models.Monitor.DeviceContext.DISPLAY_DEVICE_FLAG
  | cb | 424 | uint

But the second call to the `EnumDisplayDevices(display.DeviceName, j, ref monitor, EDD_GET_DEVICE_INTERFACE_NAME)` with provided device name returns `false` every time.

I'm at lost here. :(

**Comment by emoacht** [comment]
I see. So your monitors seem not being recognized by your PC.
Are they directly connected to your PC? Or through USB or any adapter?

**Comment by sutr90** [comment]
Both monitors are connected directly to PC.One is attached using HDMI cable the other is attached using DisplayPort.

I have tried changing the cables around, and nothing changed. I have a suspicion this has something to do with the integrated GPU.

**Comment by emoacht** [comment]
It's quite odd. It is far beyond this app's capabilities.
There might be something wrong in hardware settings.

**Comment by sutr90** [comment]
Okay, thank for your time. I will probably investigate on my own, if I find something I will report back.

In the meantime, I think the app should show a simple message "no supported monitors found". Then it doesn't look broken at least. :)

I was looking at the codebase and I think creating "virtual" device item with the message would be enough. What do you think?

**Comment by sutr90** [comment]
I've got it!!

I was messing around in the system device manager and I have noticed, that the monitors are using TeamViewer driver (WTF?!).
![teamviewer driver](https://user-images.githubusercontent.com/1327101/72139933-d380e080-338f-11ea-9e74-f8ccf23851f5.png)

I have then reinstalled the driver to one found on Lenovo website, and everything started to work! This is the weirdest thing...

**Comment by emoacht** [comment]
Congratulations!
Regarding your suggestion, in my view, this is an irregular case and usually, at least one monitor is found regardless of whether it is controllable or not. Therefore, uncontrollable monitor message would be sufficient.
