### ISSUE TITLE
Controversial device support (Dell U2412HM)

### ISSUE THREAD

**Issue by ellegance** [emoacht/Monitorian#72]
Hi, @emoacht 
Your tool looks very promising, but unfortunately it does not support Dell U2412HM. According to Dell official website that's true, U2412HM does not support DDC/CI. But I have setting in "Other Settings" section named "DDC/CI" and it is enabled. Moreover, I can control brightness via ScreenBright utility
https://www.softpedia.com/get/Desktop-Enhancements/Other-Desktop-Enhancements/ScreenBright.shtml

But, speaking honestly, it is not as stylish as yours. Is it possible to add support of this monitor to your utility? Maybe you can provide unofficial build with spoofed DDC/CI official check, which just sends commands to change brightness, and I get to you with feedback?

Thanks

**Comment by emoacht** [comment]
Hi, ellegance
Could you show the monitor's probe.log?

**Comment by ellegance** [comment]
I tried to search for log files, but could not find any (probe.log, operation.log, exception.log). Does log creation depends on some system service or OS version (win 7 is used). Right now behavior of Monitorian with this monitor is following: near 10 run/close cycles of Monitorian app is required to get it working (slidebar appears), the rest ~9 times I get "Dell U2412M(DisplayPort) This monitor is not controllable". ScreenBright at the same time works flawlessly.

**Comment by emoacht** [comment]
Did you follow the instruction in Development section of readme to get probe.log?
It's OS independent and works on Windows 7.

**Comment by ellegance** [comment]
I missed that section, now attaching logs:

`[Date: 02-05-2020 12:28:05  Ver: 2.4.0.0]
{
  "Device Context - DeviceItems": [
    {
      "DeviceInstanceId": "DISPLAY\\DELA07B\\5&1f691e58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "DisplayIndex": 1,
      "MonitorIndex": 0
    }
  ],
  "Monitor Configuration - PhysicalItems": [
    {
      "Key": {
        "DisplayIndex": 1
      },
      "Value": [
        {
          "Description": "Dell U2412M(DisplayPort)",
          "MonitorIndex": 0,
          "IsHighLevelSupported": false,
          "IsLowLevelSupported": false,
          "Capabilities": null
        }
      ]
    }
  ],
  "Device Installation - InstalledItems": [
    {
      "DeviceInstanceId": "DISPLAY\\DELA07B\\5&1F691E58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "IsRemovable": true
    }
  ],
  "MSMonitorClass - DesktopItems": [ ],
  "DisplayMonitor - DisplayItems": null,
  "ElapsedTime": [
    "DeviceItems -> 8",
    "PhysicalItems -> 1028",
    "InstalledItems -> 3",
    "DesktopItems -> 92",
    "DisplayItems -> 3"
  ]
}`

**Comment by ellegance** [comment]
And here I reproduced multiple run close of Monitorian to get it working, please see operation.log:

> [Date: 02-05-2020 12:31:48  Ver: 2.4.0.0]
Enabled

[Date: 02-05-2020 12:32:13  Ver: 2.4.0.0]
Initiated

[Date: 02-05-2020 12:32:13  Ver: 2.4.0.0]
ScanAsync [02-05-2020 12:32:13 ]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "IsReachable": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "UnreachableMonitorItem",
        "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
        "Description": "Dell U2412M(DisplayPort)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "IsReachable": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1
      },
      "Name": "Dell U2412M(DisplayPort)",
      "IsUnison": false,
      "IsControllable": false,
      "IsLikelyControllable": false,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 02-05-2020 12:32:22  Ver: 2.4.0.0]
Initiated

[Date: 02-05-2020 12:32:23  Ver: 2.4.0.0]
ScanAsync [02-05-2020 12:32:22 ]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "IsReachable": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "UnreachableMonitorItem",
        "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
        "Description": "Dell U2412M(DisplayPort)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "IsReachable": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1
      },
      "Name": "Dell U2412M(DisplayPort)",
      "IsUnison": false,
      "IsControllable": false,
      "IsLikelyControllable": false,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 02-05-2020 12:33:04  Ver: 2.4.0.0]
Initiated

[Date: 02-05-2020 12:33:06  Ver: 2.4.0.0]
ScanAsync [02-05-2020 12:33:04 ]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "IsReachable": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "UnreachableMonitorItem",
        "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
        "Description": "Dell U2412M(DisplayPort)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "IsReachable": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1
      },
      "Name": "Dell U2412M(DisplayPort)",
      "IsUnison": false,
      "IsControllable": false,
      "IsLikelyControllable": false,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 02-05-2020 12:33:13  Ver: 2.4.0.0]
Initiated

[Date: 02-05-2020 12:33:14  Ver: 2.4.0.0]
ScanAsync [02-05-2020 12:33:13 ]
{
  "Items": [
    {
      "Type": "UnreachableMonitorItem",
      "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "IsReachable": false,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "UnreachableMonitorItem",
        "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
        "Description": "Dell U2412M(DisplayPort)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "IsReachable": false,
        "Brightness": -1,
        "BrightnessSystemAdjusted": -1
      },
      "Name": "Dell U2412M(DisplayPort)",
      "IsUnison": false,
      "IsControllable": false,
      "IsLikelyControllable": false,
      "ControllableCount": 3,
      "IsByKey": false,
      "IsSelected": false,
      "IsTarget": true
    }
  ]
}

[Date: 02-05-2020 12:33:20  Ver: 2.4.0.0]
Initiated

[Date: 02-05-2020 12:33:21  Ver: 2.4.0.0]
ScanAsync [02-05-2020 12:33:20 ]
{
  "Items": [
    {
      "Type": "DdcMonitorItem",
      "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
      "Description": "Dell U2412M(DisplayPort)",
      "DisplayIndex": 1,
      "MonitorIndex": 0,
      "IsReachable": true,
      "Brightness": -1,
      "BrightnessSystemAdjusted": -1
    }
  ],
  "Monitors": [
    {
      "Item": {
        "Type": "DdcMonitorItem",
        "DeviceInstanceId": "DISPLAY\DELA07B\5&1f691e58&1&UID2097424",
        "Description": "Dell U2412M(DisplayPort)",
        "DisplayIndex": 1,
        "MonitorIndex": 0,
        "IsReachable": true,
        "Brightness": 50,
        "BrightnessSystemAdjusted": -1
      },
      "Name": "Dell U2412M(DisplayPort)",
      "IsUnison": false,
      "IsControllable": true,
      "IsLikelyControllable": true,
      "ControllableCount": 5,
      "IsByKey": false,
      "IsSelected": true,
      "IsTarget": true
    }
  ]
}

**Comment by emoacht** [comment]
Thanks, ellegance
But what do you mean by "multiple run close of Monitorian to get it working"? What exactly you did?

**Comment by ellegance** [comment]
By "multiple run close of Monitorian to get it working" I meant closing from tray by right click -> Close, and then starting from Start menu. I supposed that if Monitorian says that "This monitor is not controllable", it means that during current run of Monitorian it will not work with monitor, so restart needed.

Why monitor responds differently - I don't know. During reproduce nothing except relaunch of Monitorian was done.

**Comment by emoacht** [comment]
I close this issue because it seems to relate to #75
