### ISSUE TITLE
This monitor is not controllable - Internal Generic PNP Monitor 

### ISSUE THREAD

**Issue by vdnick** [emoacht/Monitorian#73]
Hi friends,

I'm using an Lenovo T450 that it has the display changed before I buy it.
I can't adjust the brightness in windows, not just with this program...

In linux it's working. Maybe someone here can help me...

SoftMCCS reports that DDC/CI - not supported (missing dptx services).

Thank you

**Comment by emoacht** [comment]
Hi, vdnick.
Are you talking about internal display of ThinkPad T450? If so, DDI/CI is nothing to do with that.
It sounds like driver or other hardware issue. I think you should consult with ThinkPad community.
