### ISSUE TITLE
Add 'Detect display button'

### ISSUE THREAD

**Issue by richardmalone** [emoacht/Monitorian#75]
Awesome software, love it.

I have moved across from the similar, but not quite as good app Win10_BrightnessSlider. In that app there is a menu item 'Detect displays' which must poll connected monitors for DDC etc. This is useful because if I use a KVM for a while, then switch back I lose the second monitor. If I close Monitorian and then restart it detects it fine.

I guess an even better way would be to add a poll DDC command to the CLI, then install a task schedule to run at station unlock to poll again as the first thing you do when you switch KVM is unlock the device.

Small additional point--black icon for when windows is in light mode!

Even smaller additional point--provide an alternative to subscription! Happy to pay for a year of the licence in one go, but I don't want to have to remember to cancel it if I stop using your software.

Otherwise, good software, almost great!

**Comment by Dansel** [comment]
I, too, would appreciate a solution along these lines. I've noticed that after a period of sleep I sometimes loose my second monitor. An application restart will find it, but a quick option to re-detect displays would undeniably be both faster and easier.

**Comment by emoacht** [comment]
Okay guys.
Maybe adding a button in hidden menu would be a compromise.
