### ISSUE TITLE
App obscured by Taskbar

### ISSUE THREAD

**Issue by ljcorsa3** [emoacht/Monitorian#77]
App window pops up above button and cannot be moved. which is problem when taskbar is on the left side.  Window contents are obscured.

![Screenshot 2020-06-21 03 17 39](https://user-images.githubusercontent.com/11082181/85219365-10a2c300-b371-11ea-919b-f8fb1fab461f.png)

**Comment by emoacht** [comment]
Thank you for reporting.
I have noticed Windows 10's own components look wired sometimes but never seen this pattern.
Could you describe how to reproduce it?

**Comment by ljcorsa3** [comment]
Sorry for the confusing screenshot; it includes part of the left monitor, while the taskbar is vertical and pinned to the left-edge of the primary right-side monitor.  The position of the non-primary monitor does not change the behavior.  Monitorian secondary menu pops up partly obscured by the taskbar.
![Snap35](https://user-images.githubusercontent.com/11082181/88977467-f9b69100-d28b-11ea-9029-a3f7a31b216a.jpg)

**Comment by emoacht** [comment]
Thank you for your information.
But I cannot reproduce it.
