### ISSUE TITLE
Support for contrast?

### ISSUE THREAD

**Issue by NickStrupat** [emoacht/Monitorian#78]
Thank you for the great work on this utility! I had been using [ClickMonitorDDC](https://clickmonitorddc.bplaced.net/) before finding Monitorian. It is clunkier but it has constrast controls which is quite nice.

I'm wondering if you've thought about adding contrast support to your tool?

**Comment by emoacht** [comment]
Thank you for your suggestion.
But what do you mean by contrast support?

**Comment by emoacht** [comment]
I might consider this issue if there are enough number of requests.

**Comment by kenberkeley** [comment]
I am a Mac user and using https://github.com/MonitorControl/MonitorControl which supports contrast adjustment.
Recently I switched to Windows 10 and found @emoacht 's great App but lacks contrast adjustment 😂 😂 😂

**Comment by emoacht** [comment]
There are mainly two points to think about:

1. The necessity for most users
2. There is no common way to set the contrast of internal monitors.

**Comment by soneji** [comment]
I would also like to see this if it is possible. Thanks :)
