### ISSUE TITLE
Question: How do you store settings?

### ISSUE THREAD

**Issue by Dansel** [emoacht/Monitorian#80]
The wast majority of monitors use EEPROM to store settings. EEPROM has ~100000 writes in it before it dies. If you write settings as you drag the slider going from 0-100 would be one hundred writes if you write for every increment. Or do you write only when you release the slider? Or a couple of seconds later?

I'm asking because if I change my brightness twice a day that's ~150 writes a day: about two years of changes before the ROM dies. Obviously not immediate but far shorter than then expected lifetime of a monitor.

That said: this software is much appreciated. Very useful and very lean. Thanks.

**Comment by emoacht** [comment]
Thank you for your question. It is a interesting point.
The monitor brightness is updated every 50 milliseconds when moved. So, the number of times depends on how fast the slider is moved. If you are fast enough to move 0 to 100 within 100 milliseconds, the settings will be written two times.

**Comment by ljcorsa3** [comment]
What happens when the EEPROM gets exhausted, e.g., is the monitor stuck in the last setting forever?

I ask because I adjust frequently using the +/- 4 hotkeys, so one tweak might be several writes.  Yikes!

**Comment by Dansel** [comment]
@ljcorsa3 Honestly unsure. I guess it would depend on how everything is implemented? Best case would be to have to monitor stuck at whatever the last setting is. Worst case would likely be the monitor being bricked.

@emoacht Is it possible to implement a slowmode? Just a checkbox that changes the write to whenever you let go of the slider?

**Comment by emoacht** [comment]
@Dansel I am not sure it would be worth implementing.
For the time being, you can set brightness directly by command-line option of add-on features.

**Comment by emoacht** [comment]
I enabled to defer update of brightness while input device (mouse, stylus, touch) is moving by command-line option `/defer`. Please note this does not work for mouse while because there is no clear end point in wheel.
https://github.com/emoacht/Monitorian/commit/f90b7e25840c9f5c620c557f9d71ef5204cd11fd https://github.com/emoacht/Monitorian/commit/e535bacb6ca2d9b75bdf7134d72157ee4e86e810

**Comment by Dansel** [comment]
That is great to hear. Thanks!
