### ISSUE TITLE
Maintain min/max per monitor

### ISSUE THREAD

**Issue by ljcorsa3** [emoacht/Monitorian#82]
I have two non-identical monitors, one seems natively much brighter.  So MAX might be 100 on the dimmer, 50 on the brighter while MIN might be 30 on the dimmer, and 6 on the dimmer.

When moving them together, they both get clipped to MIN=0, MAX=100 if you adjust the sliders beyond 0 or 100 a couple of times (I use hotkeys so am not looking), after which they move in unison forever.

Feature request?  Have some way to restrict the range of the sliders to a settable persistent pair (or more) of MIN, MAX values per monitor, or to set a scaling factor.

Thanks!!

**Comment by emoacht** [comment]
Thank you for your suggestion.
Maybe in future version.

**Comment by emoacht** [comment]
Implemented and released for testing.
To use this function, check `Change adjustable range` in the menu.
https://github.com/emoacht/Monitorian/releases/tag/2.7.0-Installer

**Comment by emoacht** [comment]
This function is included and released in the latest version.

**Comment by ljcorsa3** [comment]
A belated Thank You!  Well done!
