### ISSUE TITLE
External monitor is not detected in some laptops

### ISSUE THREAD

**Issue by JayJayLo** [emoacht/Monitorian#86]
The external monitor AOC 20E1H (DDC/CI compatible) is not detected in a Dell Latitude 5480, while it is detected in Lenovo G50-80. Same display configuration, both laptops running Windows 10 (build above 14303). Any suggestion?

**Comment by emoacht** [comment]
Try get probe.log as described in [Probe](https://github.com/emoacht/Monitorian#probe) section of Readme. It can provide some information on their compatibility.

**Comment by JayJayLo** [comment]
Thank you, emoacht! Please find attached the probe.log.
[probe.log](https://github.com/emoacht/Monitorian/files/5144435/probe.log)

**Comment by emoacht** [comment]
Thank you for reporting.
According to the log, the AOC monitor does not indicate itself as DDC/CI compatible. I have no idea why though.

**Comment by JayJayLo** [comment]
Thank you for your reply. It's strange because when I connect the monitor to the other laptop I have, it is immediately detected.

**Comment by emoacht** [comment]
Well, the detection of a monitor by OS and the capabilities through DDC/CI are different issues.
