### ISSUE TITLE
"This monitor is not controllable" after a display driver update from Intel. 

### ISSUE THREAD

**Issue by Wasifatehi** [emoacht/Monitorian#87]
Hey, my PC had a driver update from Intel related to Display, after that it's showing that "this monitor isn't controllable". So as It was set at low brightness, the level stayed the same. Now I can't do anything. I tried to install the latest version of Monitorian, it isn't installing. But I've managed to install an older version that is installed but it still saying the same. I did roll back to the previous driver update but still isn't working at all.

**Comment by emoacht** [comment]
Thank you for reporting.
Could you post probe.log and operation.log? They might give some information on what is happening.

**Comment by Wasifatehi** [comment]
[Date: 31-Aug-20 5:00:54 PM Ver: 2.4.0.0]
{
  "Device Context - DeviceItems": [
    {
      "DeviceInstanceId": "DISPLAY\\HPN3541\\4&1bde9742&0&UID214571",
      "Description": "Generic PnP Monitor",
      "DisplayIndex": 1,
      "MonitorIndex": 0
    }
  ],
  "Monitor Configuration - PhysicalItems": [
    {
      "Key": {
        "DisplayIndex": 1
      },
      "Value": [
        {
          "Description": "Generic PnP Monitor",
          "MonitorIndex": 0,
          "IsHighLevelSupported": false,
          "IsLowLevelSupported": false,
          "Capabilities": null
        }
      ]
    }
  ],
  "Device Installation - InstalledItems": [
    {
      "DeviceInstanceId": "DISPLAY\\HPN3541\\4&1BDE9742&0&UID214571",
      "Description": "Generic PnP Monitor",
      "IsRemovable": true
    }
  ],
  "MSMonitorClass - DesktopItems": [ ],
  "DisplayMonitor - DisplayItems": [
    {
      "DeviceInstanceId": "DISPLAY\\HPN3541\\4&1bde9742&0&UID214571",
      "DisplayName": "HP 22f",
      "IsInternal": false,
      "ConnectionDescription": "HDMI",
      "PhysicalSize": 22.9565029
    }
  ],
  "ElapsedTime": [
    "DeviceItems -> 1",
    "PhysicalItems -> 3",
    "InstalledItems -> 2",
    "DesktopItems -> 40",
    "DisplayItems -> 10"
  ]
}

........................................................................................................
[Date: 31-Aug-20 5:02:23 PM Ver: 2.4.0.0]
Enabled

[Date: 31-Aug-20 5:02:24 PM Ver: 2.4.0.0]
Enabled

[Date: 31-Aug-20 5:02:52 PM Ver: 2.4.0.0]
Enabled

**Comment by Wasifatehi** [comment]
![image](https://user-images.githubusercontent.com/48348796/91713794-43a4d680-ebac-11ea-8e08-ebda982a615f.png)

It's being shown while installing.

**Comment by emoacht** [comment]
Thank you for the log.
It seems that your monitor does not return its capabilities by DDC/CI to this app and so is not controllable.
BTW, I have never seen that warning in installing. I have no idea whether it relates to this issue though.

**Comment by Wasifatehi** [comment]
Okay, but the app was working correctly earlier before the update. Maybe I'm having some kind of system OS malfunctioning. I don't know! Whatever! Thank u for responding.
