### ISSUE TITLE
Control Brightness with native OS keys

### ISSUE THREAD

**Issue by ForzaAaRon** [emoacht/Monitorian#88]
Would it be possible to control the display brightness with the OS key shortcuts? The app doesn't seem to be able to map the native brightness keys.

**Comment by emoacht** [comment]
What do you mean by native brightness keys?
If you are taking about special keys assigned for brightness in some keyboards, like keys at F1 and F2 of surface type cover, they are not in the list of possible [keys](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.key).
Do you know how to capture them?

**Comment by JacobDB** [comment]
@emoacht not OP, and not sure how all of this works, but would it be possible to emulate a monitor which has native support for the native Windows feature?

**Comment by emoacht** [comment]
@JacobDB IMHO, this is matter of interaction between keyboard and OS and it is implemented in the layer of keyboard driver. It means that it would be quite hard to interrupt it.
