### ISSUE TITLE
Add 'Rescan' as a button to the normal interface?

### ISSUE THREAD

**Issue by marcucciboy2** [emoacht/Monitorian#90]
Hi, I think that the rescan functionality is valuable enough that it shouldn't be tucked away into a hidden menu. Initially I came to request a refresh ability but after finding that one already exists, I have created a mock-up of how I was picturing it:

![mockup][1]

[1]: https://i.imgur.com/wNQ8aod.png

**Comment by emoacht** [comment]
I am negative to add such button because I add the rescan for exceptional cases.

**Comment by marcucciboy2** [comment]
Understood. I suggested it because I have to manually reset the app often after waking my computer from sleep as the app tends to lose connection to one of my monitors. But honestly now that I know where rescan is it's not a big deal.

**Comment by emoacht** [comment]
@marcucciboy2 If you are experiencing such issues so often, operation log would be helpful to investigate the situation.
