### ISSUE TITLE
Manually add detected monitors that erroneously don't report backlight capabilities?

### ISSUE THREAD

**Issue by anohren** [emoacht/Monitorian#91]
I'm successfully adjusting backlight on my Dell 2209WA using https://github.com/kfix/ddcctl on macOS. With Monitorian on Windows 10 on a Macbook Air (2012) the display is not even listed -- only the internal display is shown.

<details>
<summary><b>Probe.log</b></summary><div>

```
[Date: 2020-09-30 23:44:42 Ver: 2.4.0.0]
{
  "Device Context - DeviceItems": [
    {
      "DeviceInstanceId": "DISPLAY\\DELF010\\4&3353f8f0&0&UID51249920",
      "Description": "Dell 2209WA(Analog)",
      "DisplayIndex": 1,
      "MonitorIndex": 0
    },
    {
      "DeviceInstanceId": "DISPLAY\\APP9CDF\\4&3353f8f0&0&UID68092928",
      "Description": "Generic PnP Monitor",
      "DisplayIndex": 2,
      "MonitorIndex": 0
    }
  ],
  "Monitor Configuration - PhysicalItems": [
    {
      "Key": {
        "DisplayIndex": 1
      },
      "Value": [
        {
          "Description": "Dell 2209WA(Analog)",
          "MonitorIndex": 0,
          "IsHighLevelSupported": false,
          "IsLowLevelSupported": false,
          "Capabilities": null
        }
      ]
    },
    {
      "Key": {
        "DisplayIndex": 2
      },
      "Value": [
        {
          "Description": "Generic PnP Monitor",
          "MonitorIndex": 0,
          "IsHighLevelSupported": false,
          "IsLowLevelSupported": false,
          "Capabilities": null
        }
      ]
    }
  ],
  "Device Installation - InstalledItems": [
    {
      "DeviceInstanceId": "DISPLAY\\DELF010\\4&3353F8F0&0&UID51249920",
      "Description": "Dell 2209WA(Analog)",
      "IsRemovable": true
    },
    {
      "DeviceInstanceId": "DISPLAY\\APP9CDF\\4&3353F8F0&0&UID68092928",
      "Description": "Allmän PnP-bildskärm",
      "IsRemovable": false
    }
  ],
  "MSMonitorClass - DesktopItems": [
    {
      "DeviceInstanceId": "DISPLAY\\APP9CDF\\4&3353F8F0&0&UID68092928",
      "Description": "Allmän PnP-bildskärm",
      "BrightnessLevels": [
        0,
        7,
        13,
        20,
        27,
        33,
        40,
        47,
        53,
        60,
        67,
        73,
        80,
        87,
        93,
        100
      ]
    }
  ],
  "DisplayMonitor - DisplayItems": [
    {
      "DeviceInstanceId": "DISPLAY\\DELF010\\4&3353f8f0&0&UID51249920",
      "DisplayName": "DELL 2209WA",
      "IsInternal": false,
      "ConnectionDescription": "DisplayPort",
      "PhysicalSize": 22.0012169
    },
    {
      "DeviceInstanceId": "DISPLAY\\APP9CDF\\4&3353f8f0&0&UID68092928",
      "DisplayName": "Color LCD",
      "IsInternal": true,
      "ConnectionDescription": "Internal",
      "PhysicalSize": 13.2833624
    }
  ],
  "ElapsedTime": [
    "DeviceItems -> 9",
    "PhysicalItems -> 579",
    "InstalledItems -> 10",
    "DesktopItems -> 69",
    "DisplayItems -> 20"
  ]
}
```
</div></details>

Assuming that `Cababilities: null` is the issue, would it be possible to just list all connected displays regardless of their capabilities and indicate they're unsupported so that I know what the problem is, and at the same time offer an override to use the monitor anyway when I know it can handle the commands? Or does the API you use make this impossible?

**Comment by emoacht** [comment]
@anohren Thank you for your information.
I agree that the inability of the monitor to correctly report its capabilities causes the issue. Still, technically it is possible to try to change brightness whether or not it responds as expected.
I am not sure what would be best solution for such case at this moment.

**Comment by anohren** [comment]
Considering your stated ambition in #3 I think my suggestion would solve that in an intuitive way as well; list the "incompatible" monitors as usual, with a short info text, and a button or context menu with an override option. Maybe require enabling the feature in the debug menu if you think the override is dangerous or unsightly. 

Even if you don't have the override option in place it will still make your application appear less broken by clearly showing that it sees all monitors, and hinting at that it's the hardware that is at fault.

**Comment by emoacht** [comment]
Thank you for the suggestion.
I think when some of DDC/CI commands fail, it will suggest the same could happen to other commands. So I would like to make clear which function succeeds and which fails. Could you try the attached and post the result?
[MonitorVcpProbe.zip](https://github.com/emoacht/Monitorian/files/5347918/MonitorVcpProbe.zip)

**Comment by anohren** [comment]
I tried it. It did not produce any obvious results. 

When run using powershell I was unable to stop it in task manager.

**Comment by emoacht** [comment]
I see. How about this one?
Please note that if succeeds, monitor brightness will change slightly and then back.
[MonitorVcpProbe.zip](https://github.com/emoacht/Monitorian/files/5359151/MonitorVcpProbe.zip)

**Comment by anohren** [comment]
Test
´´´
[Display: 0, Monitor: 0]
Description: Dell 2209WA(Analog)
GetMonitorCapabilities False - IsHighLevelSupported: False
GetCapabilitiesStringLength False - CapabilitiesStringLength: 0
CapabilitiesRequestAndCapabilitiesReply False - IsLowLevelSupported: False
CapabilitiesString: ?ëß
CapabilitiesReport - Luminance: False, Contrast: False, Speaker Volume: False
GetBrightness False - Minimum: 0, Current: 0, Maximum: 0
SetBrightness True
[Display: 1, Monitor: 0]
Description: Generic PnP Monitor
´´´

**Comment by emoacht** [comment]
Thank you for the result.
It shows the failure of function "GetBrightness" to get the brightness from the monitor in question. This function is essential to access the monitor through DDC/CI and it means that the monitor cannot be controlled.
Maybe there is something which hinder DDC/CI commands.

**Comment by anohren** [comment]
> Maybe there is something which block DDC/CI commands.

Probably Windows. Because ScreenBright has worked in earlier versions (but not anymore for some reason) and it works fine to send backlight commands on macOS with the same hardware.

**Comment by emoacht** [comment]
So you have executed it on a Mac using BootCamp?
I don't know much about hardware compatibility of BootCamp.

**Comment by anohren** [comment]
Yes. I'd imagine it's the same as on any other intel platform with intel HD graphics and stock drivers, so you can treat it as any machine.

**Comment by emoacht** [comment]
As there seems to be no further input, I close this issue.
Regarding your suggestion, I am reluctant to add UI elements for such purpose because it will not solve the real issue of monitors and not constructive. Rather, I would like to focus the core functionality of this app.

**Comment by anohren** [comment]
> As there seems to be no further input, I close this issue.

Sorry, were you expecting more information? I was not aware.

**Comment by emoacht** [comment]
Never mind. I just kept this issue open for someone who may have experience in BootCamp.

BTW, I just remember that in the latest version, even if a monitor fails to respond to capabilities test, still this app will try to access the monitor and after the bunch of failures, determine that the monitor is uncontrollable.

**Comment by anohren** [comment]
> I just kept this issue open for someone who may have experience in BootCamp.

Out of curiosity, what aspects of a Windows installation on arbitrary Intel/Apple hardware do you imagine is fundamentally different from a Windows installation on arbitrary hardware from any other manufacturer?

> BTW, I just remember that in the latest version, even if a monitor fails to respond to capabilities test, still this app will try to access the monitor and after the bunch of failures, determine that the monitor is uncontrollable.

Do you mean latest version as in a version that was not released when the issue was created?
