### ISSUE TITLE
Eizo CX241 not working

### ISSUE THREAD

**Issue by braunie143** [emoacht/Monitorian#92]
Hello, why does my Eizo CX241 is showen as "not controllable"?

**Comment by emoacht** [comment]
Hello. I have no idea but probe.log may give some clue.

**Comment by braunie143** [comment]
Where could I find this file (path)? I don't see it in the installation path.

**Comment by emoacht** [comment]
You can find the explanation in [Probe](https://github.com/emoacht/Monitorian#probe) section of readme.

**Comment by braunie143** [comment]
[probe.log](https://github.com/emoacht/Monitorian/files/5342934/probe.log)
I am not able to interpret this log. Does anyone?

**Comment by emoacht** [comment]
Thank you for the log.
It clearly shows that DDC/CI is not enabled between the monitor. It's the reason why the monitor cannot be handled.
