### ISSUE TITLE
iiyama PLE2483H does not respond

### ISSUE THREAD

**Issue by thomaslouisdegans-adeo** [emoacht/Monitorian#97]
DDC/CI is enabled but the monitor does not respond.

[probe.log](https://github.com/emoacht/Monitorian/files/5466265/probe.log)

**Comment by emoacht** [comment]
@thomaslouisdegans-adeo Thank you for the report.
Could you describe as detailed as possible?

**Comment by thomaslouisdegans-adeo** [comment]
@emoacht I’d love too, What kind of information do you need?

For now the screen is working but always at 100% brightness.

**Comment by emoacht** [comment]
I mean, when, what and how the problem happens. Right now there is no clue on what is really happening at all.

**Comment by thomaslouisdegans-adeo** [comment]
Like I said, everything looks fine, the monitor appears in the list at 100% brightness.
but when I change it nothing happens and the dialer goes back to 100% when I launch the app again.

**Comment by emoacht** [comment]
Does it happens in Ver 2.6 as well?

**Comment by thomaslouisdegans-adeo** [comment]
Should I downgrade to test this?

**Comment by emoacht** [comment]
Could you make an operation.log as described in readme, rescan a few time and post it?

**Comment by thomaslouisdegans-adeo** [comment]
There you go: [operation.log](https://github.com/emoacht/Monitorian/files/5475335/operation.log)

**Comment by emoacht** [comment]
Thank you for the log.
So the value (100) of brightness is correct? In other words, it is the brightness set by OSD menu?

**Comment by emoacht** [comment]
Could you try this (Ver 2.7.4) and post probe.log again?
https://github.com/emoacht/Monitorian/releases/download/2.7.4-Installer/MonitorianInstaller274.zip

**Comment by thomaslouisdegans-adeo** [comment]
> 
> 
> Thank you for the log.
> So the value (100) of brightness is correct? In other words, it is the brightness set by OSD menu?

100% is correct but brightness isn’t set by the OSD Menu, the option is grayed out (as well as others) because DDC/CI is on.
![IMG_20201103_111109](https://user-images.githubusercontent.com/58738416/97975873-10f4a580-1dca-11eb-84e7-a0524bcc184d.jpg)
![IMG_20201103_111120](https://user-images.githubusercontent.com/58738416/97975885-18b44a00-1dca-11eb-8fab-5148e64944f4.jpg)
[operation.log](https://github.com/emoacht/Monitorian/files/5480683/operation.log)
[probe.log](https://github.com/emoacht/Monitorian/files/5480685/probe.log)

**Comment by emoacht** [comment]
Thank you for the logs.
I found that when set brightness function was called, it indicated success but in reality, it failed. The below in probe.log shows that the function tried to set brightness at 90 and returned success while the actual brightness remained at 100.

```
"SetBrightness": "Success: True, Match: False (Expected: 90, Actual: 100)"
```

It means that either the function or the monitor itself returns false response whereas the brightness is not changed. This is the root cause of this issue. It's quite tricky and I don't think I can do anything for such monitor.

Regarding the OSD menu, I have never seen a monitor whose own adjustment capabilities are locked in DDC/CI is on. Too bad.

**Comment by thomaslouisdegans-adeo** [comment]
The worst thing is... if I disable DDC/CI, the controls stay locked 😨 
That was the reason I discovered Monitorian in the first place.

Welp, thanks for the support, I’ll try to live with this monitor for now 😅
