### ISSUE TITLE
Slider style doesn't match rest of Windows.

### ISSUE THREAD

**Issue by nathanielcwm** [emoacht/Monitorian#98]
Windows as of 20H2 uses an oblong slider while this program uses a square slider.

![image](https://user-images.githubusercontent.com/22572406/97784079-e8588a00-1bd6-11eb-841f-6523fd637cbd.png)
![image](https://user-images.githubusercontent.com/22572406/97784085-ee4e6b00-1bd6-11eb-9dc8-64ad6ecc0497.png)

**Comment by emoacht** [comment]
I have already responded in the previous issues.

**Comment by nathanielcwm** [comment]
Could I get a link as I'm unable to find the previous discussion on this.
