### ISSUE TITLE
Monitor not detected

### ISSUE THREAD

**Issue by captrohitsaxena** [emoacht/Monitorian#99]
Hi There,

I have a 2 Monitor Setup connected to my Lenovo Thinkpad x270 laptop via the following setup

Internal Laptop Display 
USB C to DP - Dell P2719H (DP)
HDMI - Dell SE2216H (HDMI)

Probe detects all the Monitors correctly, however, cannot manage the HDMI Dell SE2216H. DDC/CI is enabled and have tried all common tricks such as restarting, drivers update etc options. No errors either.

Probe file attached.

[probe.log](https://github.com/emoacht/Monitorian/files/5470323/probe.log)

**Comment by emoacht** [comment]
Thank you for the log.
It shows that DDC/CI is not enabled with Dell SE2216H. You can see the difference from Dell P2719H in "Monitor Configuration - PhysicalItems". It did not respond to DDC/CI commands at all.

```
"Description": "Dell SE2216H (HDMI)",
"MonitorIndex": 0,
"IsHighLevelSupported": false,
"IsLowLevelSupported": false,
"CapabilitiesString": null,
"CapabilitiesReport": "Luminance: False, Contrast: False, Speaker Volume: False",
"GetBrightness": false,
"SetBrightness": false
```

**Comment by captrohitsaxena** [comment]
![IMG_20201102_110205](https://user-images.githubusercontent.com/73771951/97839904-19d17280-1d09-11eb-8137-012bb37f7702.jpg)

Hi there, 

I checked the probe again and even repeated it after changing the cable but it remained the same. Went ahead and took a picture of the settings where it shows DDC/CI is enabled for the monitor.

Any other guidance that you may have for this?

**Comment by emoacht** [comment]
Hi,
So you connects the monitor directly to the ThinkPad's HDMI connector? If so, it will be hardware compatibility issue between the monitor and the ThinkPad and I will not be the right person you can consult with.

**Comment by emoacht** [comment]
Could you try this and post probe.log again?
https://github.com/emoacht/Monitorian/releases/download/2.7.4-Installer/MonitorianInstaller274.zip

**Comment by captrohitsaxena** [comment]
![image](https://user-images.githubusercontent.com/73771951/97950808-1ba93d80-1dbe-11eb-8d72-b4092350cc2a.png)

unable to run the installer.

**Comment by emoacht** [comment]
I see.
Probably it is because it is not digitally signed. Anyways, if you cannot skip the anti virus software, it is not  I will not be able to continue looking into this issue.

**Comment by captrohitsaxena** [comment]
[probe.log](https://github.com/emoacht/Monitorian/files/5479390/probe.log)
here you are. Had to get some IT Support to skip.

**Comment by emoacht** [comment]
Thank you but you seems to execute the older version. It should be Ver 2.7.4.

**Comment by captrohitsaxena** [comment]
[probe.log](https://github.com/emoacht/Monitorian/files/5479890/probe.log)
Here it is.

Also, I tried connecting the other Monitor which is getting detected (DP) through HDMI and it wasn't recognized.
Will it be fair to think that this could be a Laptop HDMI Port Compatibility issue? I am using a Lenovo x270 running on Windows 10 64 Bit with 16 Gigs of RAM

**Comment by emoacht** [comment]
Thank you for the log.
The result of the monitor in question is unchanged but I could confirm the difference between the two monitors.

> Will it be fair to think that this could be a Laptop HDMI Port Compatibility issue?

Honestly, I have no idea.
